### ISSUE TITLE
Swift version does not specify

### ISSUE THREAD

**Issue by owsis** [darwin-morocho/flutter-facebook-auth#1]
**Error**
`- 'flutter_facebook_auth' does not specify a Swift version and none of the targets ('Runner') integrating it have
    the 'SWIFT_VERSION' attribute set. Please contact the author or set the 'SWIFT_VERSION' attribute in at least one of
    the targets that integrate this pod.`

**Environment**
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-ID)
    • Flutter version 1.9.1+hotfix.2 at /Users/ows/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/ows/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone X • 810C1776-8BF2-4252-B51A-E44EED411A81 • ios • iOS 12.1 (simulator)

• No issues found!

**Comment by blastmasta** [comment]
Any solution for this?

**Comment by darwin-morocho** [comment]
> Any solution for this?

this is a problem of your ios project
for more info https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482

**Comment by darwin-morocho** [comment]
> > Any solution for this?
> 
> this is a problem of your ios project
> for more info [ko2ic/image_downloader#9 (comment)](https://github.com/ko2ic/image_downloader/issues/9#issuecomment-471608482)

If you have other dependencies  please don't delete Podfile.lock

**Comment by owsis** [comment]
I have follow step instruction. But still error in `SWIFT_VERSION`

**Comment by darwin-morocho** [comment]
> I have follow step instruction. But still error in `SWIFT_VERSION`

When you create your flutter project you need select swift as a language.

You can simply remove ios folder and run this command
`$ flutter create -i swift `

This will rebuild the project with swift integration.

For more info check https://github.com/fluttercommunity/flutter_contacts/issues/19
