### ISSUE TITLE
Unable to compile 

### ISSUE THREAD

**Issue by Kedar-27** [darwin-morocho/flutter-facebook-auth#100]
`AccessToken accessToken = await FacebookAuth.instance.login();`

A value of type 'LoginResult' can't be assigned to a variable of type 'AccessToken'.
Try changing the type of the variable, or casting the right-hand type to 'AccessToken'.

**Comment by Kedar-27** [comment]
![Screen Shot 2021-05-22 at 1 37 13 AM](https://user-images.githubusercontent.com/30876876/119192743-3d3dee00-ba9e-11eb-8319-8808a43a2646.png)

**Comment by Kedar-27** [comment]
Tried pub get , flutter clean etc

**Comment by darwin-morocho** [comment]
> Tried pub get , flutter clean etc

Hi @Kedar-27  please go to https://facebook.meedu.app/#/migration-guide

**Comment by ventr1x** [comment]
For some additional info: Flutter dev tools are atrocious at managing packages (among other things). E.g. no matter what I upgrade or remove, pub cache will randomly build with older versions. For this reason it will also not ever show any missing or changed methods. It will inject old cached indexed plugin versions.
So delete your entire cache folder, like /Users/*/.pub-cache/; best at every single SDK or plugin upgrade.
