### ISSUE TITLE
A value of type 'LoginResult' can't be assigned to a variable of type 'AccessToken'. 

### ISSUE THREAD

**Issue by anburocky3** [darwin-morocho/flutter-facebook-auth#101]
I used the following codes:
```dart
  Future<UserCredential> signInWithFacebook() async {
    // Trigger the sign-in flow
    final AccessToken result = await FacebookAuth.instance.login();

    // Create a credential from the access token
    final facebookAuthCredential = FacebookAuthProvider.credential(result.token);

    // Once signed in, return the UserCredential
    return await FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
  }
```

I asking me to cast it in `AccessToken` when I did, 
![image](https://user-images.githubusercontent.com/15264938/119573897-8362bc80-bdd2-11eb-8b7f-439eadcf578d.png)

The following error occurs:
 `[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'LoginResult' is not a subtype of type 'AccessToken' in type cast`

**Comment by darwin-morocho** [comment]
> I used the following codes:
> 
> ```dart
>   Future<UserCredential> signInWithFacebook() async {
>     // Trigger the sign-in flow
>     final AccessToken result = await FacebookAuth.instance.login();
> 
>     // Create a credential from the access token
>     final facebookAuthCredential = FacebookAuthProvider.credential(result.token);
> 
>     // Once signed in, return the UserCredential
>     return await FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
>   }
> ```
> 
> I asking me to cast it in `AccessToken` when I did,
> ![image](https://user-images.githubusercontent.com/15264938/119573897-8362bc80-bdd2-11eb-8b7f-439eadcf578d.png)
> 
> The following error occurs:
> `[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'LoginResult' is not a subtype of type 'AccessToken' in type cast`


Hi you can check the breaking changes in the new version of this plugin here https://facebook.meedu.app/#/migration-guide

**Comment by anburocky3** [comment]
Thanks @darwin-morocho  your documentation cleared my problem. Wonderful documentation. 


I have a doubt, even if I installed facebook app, still it is using browser (login dialog) to login? Why is that?

I see apps when we click `Login with Facebook`, it will open in facebook app and they have to click allow and it will automatically does the work.

Currently my app is in debug mode, so not working with facebook app?

**Comment by darwin-morocho** [comment]
> Thanks @darwin-morocho your documentation cleared my problem. Wonderful documentation.
> 
> I have a doubt, even if I installed facebook app, still it is using browser (login dialog) to login? Why is that?
> 
> I see apps when we click `Login with Facebook`, it will open in facebook app and they have to click allow and it will automatically does the work.
> 
> Currently my app is in debug mode, so not working with facebook app?

https://github.com/darwin-morocho/flutter-facebook-auth/issues/99#issuecomment-845089214

**Comment by anburocky3** [comment]
Thanks, got it. I was using `nativeWithFallback` and when I login, I receive this:

![image](https://user-images.githubusercontent.com/15264938/119581437-2c63e400-bde0-11eb-92bc-32f2851f9df3.png)

Note: I have added key hash to facebook developers. My app is in development stage.

**Comment by darwin-morocho** [comment]
> Thanks, got it. I was using `nativeWithFallback` and when I login, I receive this:
> 
> ![image](https://user-images.githubusercontent.com/15264938/119581437-2c63e400-bde0-11eb-92bc-32f2851f9df3.png)
> 
> Note: I have added key hash to facebook developers. My app is in development stage.
please check your key hash in your facebook console annd when your app is in dev mode you only can use the facebook developer account to try the login

**Comment by anburocky3** [comment]
I created key hash again and did a hot restart. Now it is working. But it is kind of shaggy? (shaggy i meant was, after approving facebook permissions, it is pausing(looks like) and after a second or couple of second, it is redirecting.) 

Can we improve this workflow with smooth transition?

**Comment by darwin-morocho** [comment]
> I created key hash again and did a hot restart. Now it is working. But it is kind of shaggy? (shaggy i meant was, after approving facebook permissions, it is pausing(looks like) and after a second or couple of second, it is redirecting.)
> 
> Can we improve this workflow with smooth transition?

This a default behavior of the facebook sdk we cannot do any more

**Comment by anburocky3** [comment]
Thanks for your time, I will do some kind of state management and make it smooth. Thanks. Closing it.
