### ISSUE TITLE
MissingPluginException(No implementation found for method

### ISSUE THREAD

**Issue by mzl1988** [darwin-morocho/flutter-facebook-auth#102]
After many experiments and (flutter_udid: ^2.0.0 image_picker: ^0.7.5+3) together, an error will occur

**Comment by darwin-morocho** [comment]
> After many experiments and (flutter_udid: ^2.0.0 image_picker: ^0.7.5+3) together, an error will occur

Please follow the issue template

**Comment by mzl1988** [comment]
![image](https://user-images.githubusercontent.com/11645762/120296039-4f1f5c80-c2fa-11eb-963d-4b144f9cb8a6.png)
flutter_facebook_auth: ^3.4.0
shared_preferences: ^2.0.6
flutter_udid: ^2.0.0
 image_picker: ^0.7.5+3
Before flutter_facebook_auth is used, everything is normal. After using it, (shared_preferences, flutter_udid, image_picker)MissingPluginException(No implementation found for method)

**Comment by mzl1988** [comment]
solved

**Comment by fadiadib** [comment]
On which version is this solved? I am using an older version and it is causing the error with shared_preference and package_info

**Comment by darwin-morocho** [comment]
> On which version is this solved? I am using an older version and it is causing the error with shared_preference and package_info

Is not an issue. The problem is that you have not configured the plugin on Android yet or your android configuration is wrong

**Comment by darwin-morocho** [comment]
> > On which version is this solved? I am using an older version and it is causing the error with shared_preference and package_info
> 
> Is not an issue. The problem is that you have not configured the plugin on Android yet or your android configuration is wrong

https://facebook.meedu.app/#/android
