### ISSUE TITLE
Login Error: There is an error in logging you into this application. Please try again later.

### ISSUE THREAD

**Issue by dalton5** [darwin-morocho/flutter-facebook-auth#103]
Hi,

I have an issue in the login with facebook. My keyhashes are good.

When I login with webonly it works well.

`loginBehavior: LoginBehavior.webOnly`

When I login with the app

`LoginBehavior.nativeWithFallback`

I have the error: Login Error: There is an error in logging you into this application. Please try again later.

How can I fix the error?

Thanks,

**Comment by darwin-morocho** [comment]
> Hi,
> 
> I have an issue in the login with facebook. My keyhashes are good.
> 
> When I login with webonly it works well.
> 
> `loginBehavior: LoginBehavior.webOnly`
> 
> When I login with the app
> 
> `LoginBehavior.nativeWithFallback`
> 
> I have the error: Login Error: There is an error in logging you into this application. Please try again later.
> 
> How can I fix the error?
> 
> Thanks,

Is a common error that Windows users think they have the key hashs ok. But on Windows in the most cases you will need to get your key hash using native code

**Comment by darwin-morocho** [comment]
here you have more info https://stackoverflow.com/questions/39051517/login-error-there-is-an-error-in-logging-you-into-this-application-please-try

**Comment by dalton5** [comment]
> > Hi,
> > I have an issue in the login with facebook. My keyhashes are good.
> > When I login with webonly it works well.
> > `loginBehavior: LoginBehavior.webOnly`
> > When I login with the app
> > `LoginBehavior.nativeWithFallback`
> > I have the error: Login Error: There is an error in logging you into this application. Please try again later.
> > How can I fix the error?
> > Thanks,
> 
> Is a common error that Windows users think they have the key hashs ok. But on Windows in the most cases you will need to get your key hash using native code
> 
> https://developers.facebook.com/docs/facebook-login/android/advanced

Thanks. I say I my hashes are good because it works with the web version. But I am going to double check.

**Comment by darwin-morocho** [comment]
Closed by inactivity
