### ISSUE TITLE
Null object error when getting user data

### ISSUE THREAD

**Issue by uggrin** [darwin-morocho/flutter-facebook-auth#104]
Hi, I'm using this plugin and I find it works pretty well, so far.

I log in with the user and get access token, I check if the user is logged in and print the access token too. But I can't get the user data for some reason.

When I call:
`final userData = await FacebookAuth.i.getUserData(fields: 'name,email');`
I get an error:
`PlatformException(FAILED, Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference, null, null)`

I am trying exactly as the full example provided, and still get the same result.

Thanks!

**Comment by darwin-morocho** [comment]
> Hi, I'm using this plugin and I find it works pretty well, so far.
> 
> I log in with the user and get access token, I check if the user is logged in and print the access token too. But I can't get the user data for some reason.
> 
> When I call:
> `final userData = await FacebookAuth.i.getUserData(fields: 'name,email');`
> I get an error:
> `PlatformException(FAILED, Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference, null, null)`
> 
> I am trying exactly as the full example provided, and still get the same result.
> 
> Thanks!
HI, i will check

**Comment by uggrin** [comment]
> 
> 
> > Hi, I'm using this plugin and I find it works pretty well, so far.
> > I log in with the user and get access token, I check if the user is logged in and print the access token too. But I can't get the user data for some reason.
> > When I call:
> > `final userData = await FacebookAuth.i.getUserData(fields: 'name,email');`
> > I get an error:
> > `PlatformException(FAILED, Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference, null, null)`
> > I am trying exactly as the full example provided, and still get the same result.
> > Thanks!
> > HI, i will check

Thanks for replying.

After struggling for almost whole day, now it works. I literally didn't change anything on that line. And out of nowhere now I am getting the expected response...

Everything is working as intended. Sorry for the inconvenience.

Thanks!

**Comment by k1ycee** [comment]
@darwin-morocho Hi I am currently having this same issue on android 11, something about the deprecation of In app webviews in  android 11 and we should move to using custom tabs.
