### ISSUE TITLE
getUserData returns null when testing with real user

### ISSUE THREAD

**Issue by uggrin** [darwin-morocho/flutter-facebook-auth#105]
Hi, me again :)

So today I was testing my app again, and apparently the method returns user data properly only with fake test users (the ones you can add through Fb developer)... I tested with actual user and it doesn't work, it returns null.

`FacebookAuth.instance.getUserData();`

I hope you can look into it :)

Thanks in advance!

**Comment by darwin-morocho** [comment]
if your app is in development mode in your Facebook developers console you only can test the login flow using the Facebook developer account

**Comment by uggrin** [comment]
> 
> 
> if your app is in development mode in your Facebook developers console you only can test the login flow using the Facebook developer account

I found out what was the problem... Apparently the first frame will always return Null. I have fixed the flow now, but thanks anyway.

I can't find anything to handle declined permissions though? I see there's a method to return a list of declined permissions, but nothing more than that.

Thanks a lot!

**Comment by darwin-morocho** [comment]
The AccessToken class has two fields (only Android and iOS, on web these fields will be null) grantedPermissions and declinedPermissions to check the permissions granted for the user.

On web use FacebookAuth.instance.permissions to check the permissions granted for the user.
