### ISSUE TITLE
Update to iOS 11 -> Pods update

### ISSUE THREAD

**Issue by Ahmadre** [darwin-morocho/flutter-facebook-auth#109]
Actually Facebook SDK has been upgraded since a long time and it would be great if the new FacebookSDK's were used like here:

https://developers.facebook.com/docs/app-events/upgrade-guide/

**Comment by Ahmadre** [comment]
Actual podspec in this package:

```podspec
  s.dependency 'FBSDKCoreKit', '~&gt; 9.1.0'  s.dependency 'FBSDKLoginKit', '~&gt; 9.1.0'  s.platform = :ios, '9.0'
```

**Comment by darwin-morocho** [comment]
Hi according to the changelog the v11.0 was released 9 dyas before https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md

I will check it

**Comment by darwin-morocho** [comment]
Updated on ` flutter_facebook_auth: ^3.5.0`
