### ISSUE TITLE
Apple App Tracking Transparency

### ISSUE THREAD

**Issue by trevordunn** [darwin-morocho/flutter-facebook-auth#112]
In #92 it was mentioned that we can add `<key>FacebookAutoLogAppEventsEnabled</key><false/>` to the info.plist file to disable tracking, but how can we reenable tracking if the user approves it using Apple's new App Tracking Transparency dialog flow?

See Facebook's docs here: https://developers.facebook.com/docs/app-events/gdpr-compliance/#delaying-automatic-event-collection

**Comment by darwin-morocho** [comment]
> In #92 it was mentioned that we can add `<key>FacebookAutoLogAppEventsEnabled</key><false/>` to the info.plist file to disable tracking, but how can we reenable tracking if the user approves it using Apple's new App Tracking Transparency dialog flow?

Hi. you can enabled FacebookAutoLogAppEventsEnabled in your info.plist and you will need to ask to the users about the tracking permission using a plugin like perssion_handler

**Comment by trevordunn** [comment]
In Facebook's docs they recommend disabling `FacebookAutoLogAppEventsEnabled` in the info.plist file first, then asking for tracking permission at runtime, then reenabling analytics. Is there a way to do that last part with this package?

**Comment by darwin-morocho** [comment]
> In Facebook's docs they recommend disabling `FacebookAutoLogAppEventsEnabled` in the info.plist file first, then asking for tracking permission at runtime, then reenabling analytics. Is there a way to do that last part with this package?

This plugin doesn't have that feature yet. You will need to use plataform channels or of you can give me a example url or code using swift  I will add to this plugin in the version

**Comment by trevordunn** [comment]
The facebook link I posted initially has the docs for how it should work. I believe this is what you'd need to expose to Flutter:
`Settings.isAutoLogAppEventsEnabled = true`

**Comment by darwin-morocho** [comment]
> The facebook link I posted initially has the docs for how it should work. I believe this is what you'd need to expose to Flutter:
> `Settings.isAutoLogAppEventsEnabled = true`

Added that feature on  `flutter_facebook_auth: ^3.5.0`

**Comment by trevordunn** [comment]
Thank-you!
