### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth))

### ISSUE THREAD

**Issue by fscopel** [darwin-morocho/flutter-facebook-auth#113]
**Describe the bug**
The bug occurs when calling the login method on the FacebookAuth.instance. 

**Environment**
Add your `flutter doctor -v`
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.1052], locale en-US)
    • Flutter version 2.2.1 at C:\src\flutter
    • Framework revision 02c026b03c (3 weeks ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Fabio\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Fabio\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 91.0.4472.106
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 91.0.864.48

Add your `pubspec.yaml`
name: flutter_order_up
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.2.1
  firebase_auth: ^1.3.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.4
  flutter_facebook_auth: ^3.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

Add your `Info.plist`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
``` 
Center(
            child: SignInButton(
              Buttons.Facebook,
              onPressed: () async {
                // Trigger the sign-in flow
                final result = await FacebookAuth.instance.login();

                if (result.accessToken == null) return;

                // Create a credential from the access token
                final facebookAuthCredential =
                    FacebookAuthProvider.credential(result.accessToken!.token);

                // Once signed in, return the UserCredential
                await FirebaseAuth.instance
                    .signInWithCredential(facebookAuthCredential);

                Navigator.of(context).pushNamedAndRemoveUntil(
                    '/homepage', (Route<dynamic> route) => false);
              },
            ),
          ),
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/1216109/122617420-dd614580-d051-11eb-9f60-cc4e946af535.png)

**Comment by darwin-morocho** [comment]
@fscope the firebase documentation and the plugin's documentation are very clear you need to configure the plugin on Android before run the project again. Please go to facebook.meedu.app to more info

**Comment by fscopel** [comment]
@darwin-morocho I was not aware of the Android configuration piece. Thank you for the direction:
If someone comes looking in the future, here is the link: [https://facebook.meedu.app/#/android](https://facebook.meedu.app/#/android)

**Comment by apoorvpandey0** [comment]
> @Fscope the firebase documentation and the plugin's documentation are very clear you need to configure the plugin on Android before run the project again. Please go to facebook.meedu.app to more info

Hi, I'm facing the same error, I followed the steps given in the docs.
Can you please elaborate what do we mean by "Configuring the plugin on Android"?
I'm running on my Android device and did set up all the files and keys necessary, is there something else?

**Comment by darwin-morocho** [comment]
> > @Fscope the firebase documentation and the plugin's documentation are very clear you need to configure the plugin on Android before run the project again. Please go to facebook.meedu.app to more info
> 
> Hi, I'm facing the same error, I followed the steps given in the docs.
> Can you please elaborate what do we mean by "Configuring the plugin on Android"?
> I'm running on my Android device and did set up all the files and keys necessary, is there something else?

If you has followed all steps in the documentation and you has compiled the the project again maybe you have a wrong configuration

**Comment by apoorvpandey0** [comment]
> > > @Fscope the firebase documentation and the plugin's documentation are very clear you need to configure the plugin on Android before run the project again. Please go to facebook.meedu.app to more info
> > 
> > 
> > Hi, I'm facing the same error, I followed the steps given in the docs.
> > Can you please elaborate what do we mean by "Configuring the plugin on Android"?
> > I'm running on my Android device and did set up all the files and keys necessary, is there something else?
> 
> If you has followed all steps in the documentation and you has compiled the the project again maybe you have a wrong configuration. Check the example folder and change the credentials your own credentials and run the project and let me know if the error persists

Thank you for responding,
Yes, I missed changing the app_id in strings.xml its working now.
