### ISSUE TITLE
problem with path provider

### ISSUE THREAD

**Issue by hassanbasanjide** [darwin-morocho/flutter-facebook-auth#119]
MissingPluginException(No implementation found for method getApplicationSupportDirectory on channel plugins.flutter.io/path_provider)   

hello dear contributor,  when i add this package ,application crash and throw this exception, it seems have some problem with path_provider package ,  i dont know what is going wrong ?

**Comment by fly-qp** [comment]
How did you fix this?

**Comment by darwin-morocho** [comment]
> How did you fix this?

You need to configure the plugin on Android before run the project again. for more info go to facebook.meedu.app

**Comment by fly-qp** [comment]
Thanks Man (-:
