### ISSUE TITLE
Crashlytics Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by slorop41314** [darwin-morocho/flutter-facebook-auth#123]
Crash on some devices.

**Environment**
Add your `flutter doctor -v`
Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-arm, locale
    en-ID)
    • Flutter version 2.2.3 at /Users/albertstanley/development/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/albertstanley/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • ANDROID_HOME = /Users/albertstanley/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    
Add your `pubspec.yaml`
  flutter_facebook_auth: 3.4.1
 
Add your `MainActivity`

package com.and.gokampus

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

Add your `AndroidManifest.xml`
 <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"
            />

         <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" 
            />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
Add your `/app/res/values/strings.xml`
<resources>
    <string name="app_name">goKampus</string>
    <string name="facebook_app_id">xxx(due to security)</string>
    <string name="fb_login_protocol_scheme">xxx(due to security)</string>
</resources>

**Screenshots**
<img width="1128" alt="Screen Shot 2021-07-23 at 11 40 55" src="https://user-images.githubusercontent.com/52713279/126738111-eec57dd4-f1a1-496c-ad82-205807e33423.png">

**Comment by darwin-morocho** [comment]
Unfortunately  this is not an issue of this plugin https://github.com/facebook/facebook-android-sdk/issues/906  I recommend updating the plugin to the last version 3.5.1 because this use the lastest facebook sdk. Maybe facebook fix this issue in the lastest version
