### ISSUE TITLE
FBSDKCoreKit/FBSDKCoreKit.h file not found

### ISSUE THREAD

**Issue by Wolfaks** [darwin-morocho/flutter-facebook-auth#126]
Hello, i have error again:
```
/ios/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKCoreKitImport.h:29:10: error: 'FBSDKCoreKit/FBSDKCoreKit.h' file not found
     #import <FBSDKCoreKit/FBSDKCoreKit.h>
             ^
    <unknown>:0: error: could not build Objective-C module 'FBSDKLoginKit'
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
```
<img width="597" alt="Снимок экрана 2021-07-23 в 17 14 50" src="https://user-images.githubusercontent.com/26388092/126794989-66ea709c-7c58-4714-bb1e-33e5a85762f9.png">

<img width="1013" alt="Снимок экрана 2021-07-23 в 17 16 00" src="https://user-images.githubusercontent.com/26388092/126795136-e73bf0ec-3a95-4f0e-ad0a-2544391a113d.png">
<img width="862" alt="Снимок экрана 2021-07-23 в 17 16 45" src="https://user-images.githubusercontent.com/26388092/126795242-22f44fc1-7b1b-481f-934e-adf1105e1623.png">

This problem is only iOS.

**Comment by darwin-morocho** [comment]
@Wolfaks  For iOS are you using swift or Objective-C?

**Comment by Wolfaks** [comment]
> @Wolfaks For iOS are you using swift or Objective-C?
> 
> Sometimes the error can be fixed using `flutter clean`

I use swift

**Comment by darwin-morocho** [comment]
@Wolfaks  I remember  that you opened a similar issue before and you had a wrong configuration in your swift code

Did you try with `flutter clean` ?

**Comment by Wolfaks** [comment]
> @Wolfaks I remember that you opened a similar issue before and you had a wrong configuration in your swift code
> 
> Did you try with `flutter clean` ?

Last time I downgraded flutter and dart verssions and the problem went away. Today she reappeared on her own. Yes, I've tried cleaning and reinstalling pods many times, but nothing helps.

**Comment by darwin-morocho** [comment]
> > @Wolfaks I remember that you opened a similar issue before and you had a wrong configuration in your swift code
> > Did you try with `flutter clean` ?
> 
> Last time I downgraded flutter and dart verssions and the problem went away. Today she reappeared on her own. Yes, I've tried cleaning and reinstalling pods many times, but nothing helps.

Are you using null safety?

**Comment by Wolfaks** [comment]
After install pods:
<img width="1352" alt="Снимок экрана 2021-07-23 в 19 13 03" src="https://user-images.githubusercontent.com/26388092/126811094-1f30a9e4-079f-4b9a-86a7-5a9be6c1e0fa.png">

Flutter run, before FB error:
<img width="1369" alt="Снимок экрана 2021-07-23 в 19 14 39" src="https://user-images.githubusercontent.com/26388092/126811290-decdfc25-4a0f-4bdb-8bdb-865a0a074c95.png">
<img width="1340" alt="Снимок экрана 2021-07-23 в 19 15 36" src="https://user-images.githubusercontent.com/26388092/126811381-28d4fca4-c1c8-472b-9eba-18fa69d990b5.png">

> Are you using null safety?
No

**Comment by darwin-morocho** [comment]
I am watching that you have null safety dependencies

**Comment by darwin-morocho** [comment]
Maybe this can help you https://developer.apple.com/forums/thread/128535

**Comment by Wolfaks** [comment]
No it didn't work for me

**Comment by darwin-morocho** [comment]
> No it didn't work for me

Sorry I can't help you if your app configuration is wrong

**Comment by Wolfaks** [comment]
The second time the problem is solved by restoring the old code from the repository, running the old code and copying the new code into it.

**Comment by volkangurol** [comment]
I had similar problem in real device, 
`#import <FBSDKCoreKit/FBSDKCoreKit.h>`
put this line in Runner-Bridging-Header.h file
