### ISSUE TITLE
Access token permission ios build error

### ISSUE THREAD

**Issue by Markaleth** [darwin-morocho/flutter-facebook-auth#128]
**Describe the bug**
Stop me if you've heard this one before:
Running the project on an iOS device or simulator fails with the following errors using : _flutter_facebook_auth: ^3.5.0_

Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.5.0/ios/Classes/FacebookAuth.swift:155:46: error: value of type 'AccessToken' has no member 'permissions'
                "grantedPermissions":accessToken.permissions.map {item in item.name},
                                     ~~~~~~~~~~~ ^~~~~~~~~~~
Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.5.0/ios/Classes/FacebookAuth.swift:156:47: error: value of type 'AccessToken' has no member 'declinedPermissions'
                "declinedPermissions":accessToken.declinedPermissions.map {item in item.name},

                
**_Please note that i have attempted the workarounds suggested in the other issues opened on this topic (i.e. make sure my iOS app uses Swift as the default language, not Objective-C) but the issue is still occurring._**

Commenting grantedPermissions and declinedPermissions in flutter_facebook_auth-3.5.0/ios/Classes/FacebookAuth.swift solves the issue. 

![Screenshot 2021-07-28 at 16 11 50](https://user-images.githubusercontent.com/27698715/127327895-740ddd87-1741-4032-902c-a4b500609afa.png)

**Environment**
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale en-RO)
    • Flutter version 2.0.5 at /Users/vladadoreme/Library/flutter
    • Framework revision adc687823a (3 months ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/vladadoreme/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/vladadoreme/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vladadoreme/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone (mobile)             • 00008020-000939402208002E            • ios            • iOS 14.6
    • iPhone 11 Pro (mobile)      • C714D781-2880-47A3-A30F-E4983E9C3696 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 92.0.4515.107

**Comment by darwin-morocho** [comment]
@Markaleth , I couldn't reproduce the issue, sometimes the problem is related with the cache

**Comment by darwin-morocho** [comment]
> @Markaleth , I couldn't reproduce the issue, sometimes the problem is related with the cache

You can clone the example of this plugin and change with your credentials and run the project.
Let me know if the problem persists

**Comment by Markaleth** [comment]
Didn't try the cloning part yet but I did try the following:
- `flutter clean`
- deleting derived data
- deleting Podfile.lock and running pod install again

Would you happen to have any other suggestions for clearing cache layers that i might have missed that may cause this behavior? 

**_Additional info:_**
The iOS project is still using the Objective-C Bridging header. 

If I keep the granted and declined permissions token properties commented, would that have any impact beyond those properties coming up null and thus being inaccessible? 

For my use case permissions are not really needed (not yet at least), so doing without them wouldn't be a problem. 
The flutter part of the plugin where the iOS method channel token response is consumed appears to have those two properties nullable so if they don't interfere with any other functionality, I can just leave them out. 

Thanks for taking the time to answer the thread btw, i really appreciate it 🙏

**Comment by darwin-morocho** [comment]
> Didn't try the cloning part yet but I did try the following:
> 
> * `flutter clean`
> * deleting derived data
> * deleting Podfile.lock and running pod install again
> 
> Would you happen to have any other suggestions for clearing cache layers that i might have missed that may cause this behavior?
> 
> **_Additional info:_**
> The iOS project is still using the Objective-C Bridging header.
> 
> If I keep the granted and declined permissions token properties commented, would that have any impact beyond those properties coming up null and thus being inaccessible?
> 
> For my use case permissions are not really needed (not yet at least), so doing without them wouldn't be a problem.
> The flutter part of the plugin where the iOS method channel token response is consumed appears to have those two properties nullable so if they don't interfere with any other functionality, I can just leave them out.
> 
> Thanks for taking the time to answer the thread btw, i really appreciate it 🙏

When you create the project by default you should use swift as a default language. if your project was created using objective-c enable the Bridging header won't work so in that case I recommend fork the project and remove Permissions on swift or remplace it with a empty list.
