### ISSUE TITLE
Update doc installation - Add client token

### ISSUE THREAD

**Issue by NatsuOnFire** [darwin-morocho/flutter-facebook-auth#129]
Beginning with SDK v13.0 for iOS and Android, set to release in early 2022, a Client Token will be required for all calls to the Graph API.

[https://developers.facebook.com/docs/ios/getting-started#client-token - Step 3](https://developers.facebook.com/docs/ios/getting-started#client-token)

[https://developers.facebook.com/docs/android/getting-started#client-token](https://developers.facebook.com/docs/android/getting-started#client-token)

**Comment by darwin-morocho** [comment]
> Beginning with SDK v13.0 for iOS and Android, set to release in early 2022, a Client Token will be required for all calls to the Graph API.
> 
> [https://developers.facebook.com/docs/ios/getting-started#client-token - Step 3](https://developers.facebook.com/docs/ios/getting-started#client-token)
> 
> https://developers.facebook.com/docs/android/getting-started#client-token

This is not an issue. Also this plugin is for login amd get the user profile data witch by default use the access token
