### ISSUE TITLE
iOS:  dependency were found, but they required a higher minimum deployment target

### ISSUE THREAD

**Issue by tillchen** [darwin-morocho/flutter-facebook-auth#13]
Hi! Thanks for developing this plugin 👍 

One problem on iOS:

When I try to run `pod install`, I get the following:

```sh
[!] CocoaPods could not find compatible versions for pod "flutter_facebook_auth":
  In Podfile:
    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)

Specs satisfying the `flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)` dependency were found, but they required a higher minimum deployment target.
```

I've tried deleting `Podfile.lock` and `pod repo update`, but the problem still persists.

There seems to be a similar issue here:

https://github.com/roughike/flutter_twitter_login/issues/26

Don't know if I should change the minimum iOS version as suggested though. 🤔 

My Flutter env: [✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)

**Comment by darwin-morocho** [comment]
> Hi! Thanks for developing this plugin 👍
> 
> One problem on iOS:
> 
> When I try to run `pod install`, I get the following:
> 
> ```shell
> [!] CocoaPods could not find compatible versions for pod "flutter_facebook_auth":
>   In Podfile:
>     flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)
> 
> Specs satisfying the `flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)` dependency were found, but they required a higher minimum deployment target.
> ```
> 
> I've tried deleting `Podfile.lock` and `pod repo update`, but the problem still persists.
> 
> There seems to be a similar issue here:
> 
> [roughike/flutter_twitter_login#26](https://github.com/roughike/flutter_twitter_login/issues/26)
> 
> Don't know if I should change the minimum iOS version as suggested though. 🤔
> 
> My Flutter env: [✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)

You need set your minimum target version to 9.0 in your Podfile

**Comment by tillchen** [comment]
Thanks for the speedy response! 👍 It indeed solved the issue. I was going to suggest that we can document this. But I just realized it is indeed documented 😅 Sorry for my negligence. 

BTW, your plugin is selected in the official FlutterFire documentation: https://firebase.flutter.dev/docs/auth/social#facebook 🎉 The other plugin `flutter_facebook_login 3.0.0` is actually deprecated due to the usage of UIWebView: https://medium.com/@karlwhiteprivate/flutter-facebook-sign-in-with-firebase-in-2020-66556a8c3586

Thank you again for the good work. 💯 And I'll close issue later:D

**Comment by osmanrami** [comment]
Solved by removing podfile.lock then running `pod desintegrate` then `pod install`

**Comment by YDA93** [comment]
In my case:
1. Delete podfile.lock
2. cd ios
3. pod install --repo-update

**Comment by yossefEl** [comment]
I fixed this by copying the content of a **Podfile** of a recently created app to the app I'm working on 
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
   # Add the library of permissions you need here
   pod 'LBXPermission/Camera'
   pod 'LBXPermission/Photo'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end

```

**Comment by KurbanAli6615** [comment]
You need set your minimum target version to 11.0 in your Podfile.

I have solved by changing target version.
