### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by alex9153** [darwin-morocho/flutter-facebook-auth#131]
When I add this package I receive crash 

MissingPluginException (MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider))

Looks like pathProvider conflicts with flutter_facebook_auth

**Comment by darwin-morocho** [comment]
> When I add this package I receive crash
> 
> MissingPluginException (MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider))
> 
> Looks like pathProvider conflicts with flutter_facebook_auth

Duplicated https://github.com/darwin-morocho/flutter-facebook-auth/issues/124

**Comment by alex9153** [comment]
Your plugin is bullshit. Just not working on android. Come when your hands grow out of the right place.
