### ISSUE TITLE
Getting an error page when providing invalid permissions to FacebookAuth.instance.login

### ISSUE THREAD

**Issue by zeczen** [darwin-morocho/flutter-facebook-auth#132]
When providing invalid values in permissions we directed to error page.

Steps to reproduce:
Login to Facebook using this code:

    logInFacebook() async {
        final LoginResult result = await FacebookAuth.instance.login(
            permissions: ['1234'], loginBehavior: LoginBehavior.webOnly
            // '1234' is random string 
        );
       ....
    }

Expected that the invalid string will be caught with a try-catch, or throwing an error with some details.

Screenshots:

![photo_2021-08-01_23-06-32](https://user-images.githubusercontent.com/54035934/128083877-34e843e2-ea61-4ce5-963f-ad6442b79606.jpg)

**Comment by darwin-morocho** [comment]
this is not an issue. Why are you passing a wrong fields?

**Comment by zeczen** [comment]
No one will do it on purpose but it can certainly happen.
In my case I did: 
`permissions: ['user_id', 'email']`
It took me a while to realize that this is the problem and not something in the process of connecting to Facebook. In my opinion it is better to use ENUM or throw a suitable error, at your discretion.
