### ISSUE TITLE
"Unsupported browser" message on Android WebView

### ISSUE THREAD

**Issue by alexeyinkin** [darwin-morocho/flutter-facebook-auth#135]
I am using Samsung SM-T585 tablet, Android 8.1.0. I get this message when trying to authenticate without the Facebook app installed.
![Screenshot_20210818-162320_Chrome](https://user-images.githubusercontent.com/44893228/129910853-3994a572-96a4-4730-8cc6-ecf73359f120.jpg)
I believe this is an issue on Facebook side of not recognizing the user agent. I am not sure what the user agent is for this webview, but with my other webviews it appears to be
```
Mozilla/5.0 (Linux; Android 8.1.0; SM-T585 Build/M1AJQ; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Safari/537.36
```

I get the same warning when I manually create a webview and navigate to the authentication URL, so it definitely is not an issue of your package. However, with my custom webview I can override the user agent. When I set it to
```
Mozilla/5.0 (Android 8.1.0; Mobile; rv:91.0) Gecko/91.0 Firefox/91.0
```
the warning is gone and the page functions alright.

I suggest you add an option to override user agent in the webview.

**Comment by darwin-morocho** [comment]
Hi @alexeyinkin Actually there is not way to embed the web login using a webview at the current facebook SDK.

So I am closing this
