### ISSUE TITLE
Can't retrieve the user email, however the name and profile image are successfully retrieved.

### ISSUE THREAD

**Issue by NeatFastro** [darwin-morocho/flutter-facebook-auth#136]
**Describe the bug**
Can't retrieve the user email, however the name and profile image are successfully retrieved.
**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AppDelegate.swift`
Add your `MainActivity`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
please add your code

**Comment by darwin-morocho** [comment]
closed by inactivity
