### ISSUE TITLE
Xcode build error

### ISSUE THREAD

**Issue by slorop41314** [darwin-morocho/flutter-facebook-auth#137]
**Describe the bug**
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.5.0+1/lib/flutter_facebook_auth.dart:115:51: Error: The getter 'isAutoLogAppEventsEnabled' isn't defined for the class 'FacebookAuthPlatform'.
     - 'FacebookAuthPlatform' is from 'package:flutter_facebook_auth_platform_interface/src/facebook_auth_plaftorm.dart' ('../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth_platform_interface-2.6.1/lib/src/facebook_auth_plaftorm.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'isAutoLogAppEventsEnabled'.
      Future<bool> get isAutoLogAppEventsEnabled => _.isAutoLogAppEventsEnabled;

**Environment**
Add your `flutter doctor -v`
Flutter version 2.2.3 at /Users/albertstanley/development/flutter
    • Framework revision f4abaa0735 (7 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4
Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1
   
Add your `pubspec.yaml`
  flutter_facebook_auth: ^3.5.0+1

**Comment by darwin-morocho** [comment]
it seems you have cache problems try with the next commands

 flutter clean

or

flutter cache repair

**Comment by darwin-morocho** [comment]
Maybe you had a previous version of this plugin installed in this plugin before?

**Comment by slorop41314** [comment]
Yess, im using the 3.4.1 before,
already do flutter pub cache repair but still get the same error

**Comment by darwin-morocho** [comment]
> Yess, im using the 3.4.1 before,
> already do flutter pub cache repair but still get the same error

Did you follow the migration guide before update to 3.5.0?
https://facebook.meedu.app/#/migration-guide

**Comment by slorop41314** [comment]
Yes, already do it

**Comment by darwin-morocho** [comment]
> Yes, already do it, but still the same error

Please clone the example project and replace with your credentials and let me know if the problem persists

**Comment by darwin-morocho** [comment]
I have run the example project without problems so I couldn't reproduce the issue because is a cache problem.

If you run `flutter clean` and the problem is not fixed maybe you need to delete manually all flutter_facebook_auth downloaded dependencies in ../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/

**Comment by slorop41314** [comment]
I've tried to delete the cache, but still the same.
When i tried pub get, it shows this warning, 
Warning: You are using these overridden dependencies:                   
! flutter_facebook_auth_platform_interface 2.6.1 (2.7.0 available)

**Comment by darwin-morocho** [comment]
> I've tried to delete the cache, but still the same.
> When i tried pub get, it shows this warning,
> Warning: You are using these overridden dependencies:
> ! flutter_facebook_auth_platform_interface 2.6.1 (2.7.0 available)

please add your complete pubspec.yaml

**Comment by slorop41314** [comment]
amplitude_flutter: ^3.2.1
  android_play_install_referrer: ^0.1.1
  camera: ^0.8.1+7
  fl_chart: ^0.36.3
  crypto: ^3.0.1
  cupertino_icons: ^1.0.3
  device_info: ^2.0.2
  dio: ^4.0.0
  dropdown_search: ^0.6.3
  file_picker: ^3.0.3
  firebase_analytics: ^8.2.0
  firebase_core: ^1.3.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  firebase_performance: ^0.7.0+7
  firebase_dynamic_links: ^2.0.7
  firebase_remote_config: ^0.10.0+3
  flutter_branch_sdk: ^3.3.0
  flutter_facebook_auth: ^3.5.0+1
  facebook_app_events: ^0.13.4
  flutter_local_notifications: ^6.1.0
  geolocator: ^7.3.1 
  get: ^4.3.8
  google_maps_flutter: ^2.0.6
  google_sign_in: ^5.0.5
  image_cropper: ^1.4.1
  mime: ^1.0.0
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.2
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.6
  sign_in_with_apple: ^3.0.0
  grouped_list: ^4.1.0
  url_launcher: ^6.0.7
  uuid: ^3.0.4
  video_player: ^2.1.12
  webview_flutter: ^2.0.10
  native_pdf_view: ^4.1.0
  flutter_cache_manager: ^3.1.2
  dotted_border: ^2.0.0
  bubble_showcase: ^1.0.0
  speech_bubble: ^0.0.9
  intl: ^0.17.0
  sms_autofill: ^2.0.1

**Comment by darwin-morocho** [comment]
> I've tried to delete the cache, but still the same.
> When i tried pub get, it shows this warning,
> Warning: You are using these overridden dependencies:
> ! flutter_facebook_auth_platform_interface 2.6.1 (2.7.0 available)

please add your complete pubspec.yaml file not only your dependencies

**Comment by slorop41314** [comment]
Thanks a lot, theres dependency overrides in the project pubspec.yaml , i didnt notice it before. Now working fine.
