### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by johnnycrystal9x** [darwin-morocho/flutter-facebook-auth#143]
**Describe the bug**
I was using hive_flutter: 1.1.0 and flutter_facebook_auth: 3.5.1, the error appears when I called Hive.initFlutter().

**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AppDelegate.swift`
Add your `MainActivity`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
E/flutter ( 3240): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter ( 3240): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:138:24)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): #2      HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): #3      DBProvider.initializeHive (package:heydjapp/core/data/local/db/db_provider.dart:26:5)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): #4      $initGetIt (package:heydjapp/core/di/injection.config.dart:124:3)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): #5      _initializeAppResources.<anonymous closure> (package:heydjapp/base.dart:40:5)
E/flutter ( 3240): <asynchronous suspension>
E/flutter ( 3240): 

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
> **Describe the bug**
> I was using hive_flutter: 1.1.0 and flutter_facebook_auth: 3.5.1, the error appears when I called Hive.initFlutter().
> 
> **Environment**
> Add your `flutter doctor -v`
> Add your `pubspec.yaml`
> Add your `Info.plist`
> Add your `AppDelegate.swift`
> Add your `MainActivity`
> Add your `AndroidManifest.xml`
> Add your `/app/res/values/strings.xml`
> 
> **To Reproduce**
> E/flutter ( 3240): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
> E/flutter ( 3240): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
> E/flutter ( 3240): 
> E/flutter ( 3240): #1 getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:138:24)
> E/flutter ( 3240): 
> E/flutter ( 3240): #2 HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
> E/flutter ( 3240): 
> E/flutter ( 3240): #3 DBProvider.initializeHive (package:heydjapp/core/data/local/db/db_provider.dart:26:5)
> E/flutter ( 3240): 
> E/flutter ( 3240): #4 $initGetIt (package:heydjapp/core/di/injection.config.dart:124:3)
> E/flutter ( 3240): 
> E/flutter ( 3240): #5 _initializeAppResources. (package:heydjapp/base.dart:40:5)
> E/flutter ( 3240): 
> E/flutter ( 3240):
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots or videos to help explain your problem.

The plugin documentation is really clear about that you need to configure the plugin before run the project.

facebook.meedu.app

**Comment by johnnycrystal9x** [comment]
> > **Describe the bug**
> > I was using hive_flutter: 1.1.0 and flutter_facebook_auth: 3.5.1, the error appears when I called Hive.initFlutter().
> > **Environment**
> > Add your `flutter doctor -v`
> > Add your `pubspec.yaml`
> > Add your `Info.plist`
> > Add your `AppDelegate.swift`
> > Add your `MainActivity`
> > Add your `AndroidManifest.xml`
> > Add your `/app/res/values/strings.xml`
> > **To Reproduce**
> > E/flutter ( 3240): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
> > E/flutter ( 3240): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
> > E/flutter ( 3240):
> > E/flutter ( 3240): #1 getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:138:24)
> > E/flutter ( 3240):
> > E/flutter ( 3240): #2 HiveX.initFlutter (package:hive_flutter/src/hive_extensions.dart:12:18)
> > E/flutter ( 3240):
> > E/flutter ( 3240): #3 DBProvider.initializeHive (package:heydjapp/core/data/local/db/db_provider.dart:26:5)
> > E/flutter ( 3240):
> > E/flutter ( 3240): #4 $initGetIt (package:heydjapp/core/di/injection.config.dart:124:3)
> > E/flutter ( 3240):
> > E/flutter ( 3240): #5 _initializeAppResources. (package:heydjapp/base.dart:40:5)
> > E/flutter ( 3240):
> > E/flutter ( 3240):
> > **Expected behavior**
> > A clear and concise description of what you expected to happen.
> > **Screenshots**
> > If applicable, add screenshots or videos to help explain your problem.
> 
> The plugin documentation is really clear about that you need to configure the plugin before run the project.
> 
> facebook.meedu.app

Thanks, I got it.
