### ISSUE TITLE
Facebook login cancel by user without choosing facebook account 

### ISSUE THREAD

**Issue by prasanthdoc** [darwin-morocho/flutter-facebook-auth#144]
@darwin-morocho  once i cancel facebook login without choosing any facebook account
 show error in the  program

 error: _typeerror  null can't subtype of Map<dynamic,error>

  final LoginResult? result =
                                      await FacebookAuth.instance.login(
                                    permissions: [
                                      'public_profile',
                                      'email',
                                    ],
                                  );
                                  if (result!.status == LoginStatus.success) {
                                    SharedPrefrence().setLoggedIn(true);
                                    final requestData =
                                        await FacebookAuth.i.getUserData(
                                      fields: "email, name",
                                    );
                                    setState(() {
                                      facebookuserObj = requestData;
                                      FacebookSignin();
                                    });
                                  }
                                  ;
                                });

**Comment by darwin-morocho** [comment]
@prasanthdoc please add a valid reproduction code. And  follow the issue template

**Comment by darwin-morocho** [comment]
@prasanthdoc sorry but your code is not enough to reproduce the issue. it seems an error in your code not in this plugin

**Comment by darwin-morocho** [comment]
closed by innactivity
