### ISSUE TITLE
[Urgent] embedded browser is disabled

### ISSUE THREAD

**Issue by callmejm** [darwin-morocho/flutter-facebook-auth#146]
**Describe the bug**
Getting this message from facebook `for your account security logging into from an embedded browser is disabled`

**Environment**
Using flutter 2.2.1
flutter_facebook_auth: ^3.4.0

**To Reproduce**
Login to facebook account

**Screenshots**
![WhatsApp Image 2021-09-11 at 16 14 14](https://user-images.githubusercontent.com/6957533/132969992-0f6be9aa-d21b-4a85-b013-5a5543bfa6df.jpeg)

**Research**
[Deprecating support for FB Login authentication on Android embedded browsers](https://developers.facebook.com/blog/post/2021/06/28/deprecating-support-fb-login-authentication-android-embedded-browsers/)

**Comment by darwin-morocho** [comment]
This is a normal behavior. if you don't have the Facebook app installed on Android a webview will be showed but Facebook can lock thw login if you are using an non secure Android version or if you are using LoginBehavior.WEBVIEW_ONLY

**Comment by jjvillavicencio** [comment]
Some solution? I use the plugin version 3.5.3 and I have the Facebook app installed on the device

![image](https://user-images.githubusercontent.com/4654352/139486960-bd531b81-123f-48a3-8a60-6fd310e7d8ce.png)
