### ISSUE TITLE
Unable to User email after sign in (email :null)

### ISSUE THREAD

**Issue by mohammednabil95** [darwin-morocho/flutter-facebook-auth#147]
I am trying to facebook signin, I followed all the necessary steps to add the code in android and ios based on the documentation. When i try to signin i get all the data like name, photo, user id etc but email i am getting null. I tried with multiple facebook account but still user email i am getting null. What is the reason email is not showing? Below is the code of Facebook signin.

  Future<UserCredential> signInWithFacebook() async {
    // Trigger the sign-in flow
    final LoginResult loginResult = await FacebookAuth.instance.login();

    // Create a credential from the access token
    final OAuthCredential facebookAuthCredential =
        FacebookAuthProvider.credential(loginResult.accessToken!.token);
    final userData = await FacebookAuth.instance.getUserData();
    print(userData);
    // Once signed in, return the UserCredential
    return FirebaseAuth.instance.signInWithCredential(facebookAuthCredential);
  }

Print Response after Sign in 

flutter: {name: Admin, picture: {data: {is_silhouette: true, height: 180, url: https://scontent.fruh4-2.fna.fbcdn.net/v/t1.30497-1/s200x200/84628273_176159830277856_972693363922829312_n.jpg?_nc_cat=1&ccb=1-5&_nc_sid=12b3be&_nc_ohc=xum7jbIRvI8AX8sTB3Y&_nc_ht=scontent.fruh4-2.fna&edm=AP4hL3IEAAAA&oh=5d4516850ff03d8931cfe34a74f37e27&oe=6163EDE5, width: 180}}, id: 204623654976581}

**Comment by darwin-morocho** [comment]
You need to go to your Facebook developers console and ensure that you has enabled public_profile and email

**Comment by abdullah432** [comment]
Same issue, I'm getting emails on a few devices but not on others devices. Not sure what to do

**Comment by darwin-morocho** [comment]
> Same issue, I'm getting emails on a few devices but not on others devices. Not sure what to do

Maybe this can help you https://stackoverflow.com/questions/43313316/facebook-oauth-doesnt-return-email-of-user
