### ISSUE TITLE
Incorrect Spelling of MainActivity in Documentation for Android

### ISSUE THREAD

**Issue by Chetan-Goyal** [darwin-morocho/flutter-facebook-auth#150]
**Describe the bug**
[Here](https://facebook.meedu.app/#/android) , The image describing about **Default Activity Class Name** contains incorrect spelling of `MainActivity` ( not `MainAcivity` )

**Environment**

**To Reproduce**
Visit [https://facebook.meedu.app/#/android](https://facebook.meedu.app/#/android ).

**Expected behavior**
It should be MainActivity

**Screenshots**
https://user-images.githubusercontent.com/15864336/98712455-54b05780-2354-11eb-9509-aa2846af1a2d.png

**Comment by darwin-morocho** [comment]
Hi thanks for your feedback I will fix it soon
