### ISSUE TITLE
Able to Force Re-authenticate on signout

### ISSUE THREAD

**Issue by LiveLikeCounter** [darwin-morocho/flutter-facebook-auth#153]
In the [JS-SDK](https://developers.facebook.com/docs/facebook-login/reauthentication) it is possible to force the user to signin with another or the same Facebook account after the signout. We would like to use the re-authenticate also in this package.

**Describe the bug**
The problem we face now, is that after the signout, with `FacebookAuth.instance.logOut();`, and the user wants to sign in with another Facebook account, it's still default come with the previous user. The only way to overcome this, is to de-instal our app and install it again.

![image](https://user-images.githubusercontent.com/24720382/134128852-a2703023-2722-4be6-b03d-28281ed0ece7.png)
If you click Cancel the Auth-Popup will be cancelled.

**Environment**
Package: `flutter_facebook_auth: ^3.5.1`
We use Firebase Auth as well.

**To Reproduce**
Our Signin method:
```
  Future<UserCredential?> signInWithFacebook(String result) async {
    UserCredential? userCredential;

    try {
      final AuthCredential authCredential =
          FacebookAuthProvider.credential(result);
      userCredential = await firebaseAuth.signInWithCredential(authCredential);

      return userCredential;
    } catch (e) {
      rethrow;
    }
  }
```

Our Sign-out method:
```
  Future<void> signOut(BuildContext context) {
    Future.delayed(const Duration(milliseconds: 250), () {
      FirebaseAuth.instance.signOut().then((dynamic) {
        FacebookAuth.instance.logOut();
        print('[signOut] Succes');
      }).catchError((e, s) {
        print('[signOut] error: $e');
        print('[signOut] stack: $s');
      });
    });

    return Future.value(null);
  }
```

**Expected behavior**
Imho it would be nice to parameterize the logOut-method, for example:
With force to re-authenticate: `FacebookAuth.instance.logOut(reauthenticate: true);`
Without to re-authenticate: `FacebookAuth.instance.logOut(reauthenticate: false);` where the default is false, so there is no change for the exciting implementations.

**Comment by darwin-morocho** [comment]
`reauthenticate` feature is not supported for mobile devices https://github.com/darwin-morocho/flutter-facebook-auth/issues/62#issuecomment-799895330
