### ISSUE TITLE
When we're going to have version 11.2.0

### ISSUE THREAD

**Issue by Bwolfs2** [darwin-morocho/flutter-facebook-auth#155]
**Describe the bug**
Facebook dashboard is calling to update to the last SDK version, when we're going to have version 11.2.0 of the IOS Facebook SDK, right now we're at 11.1.0

**Screenshots**

![image](https://user-images.githubusercontent.com/4654514/134188976-cc7bdc7c-9b03-4c8b-ad64-1b49cf5c4e0a.png)

**Comment by darwin-morocho** [comment]
try` flutter_facebook_auth:^3.5.2`
