### ISSUE TITLE
Version 3.5.1 gradle error

### ISSUE THREAD

**Issue by zaher-code-07** [darwin-morocho/flutter-facebook-auth#156]
/Users/user/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.5.1/android/src/main/java/app/meedu/flutter_facebook_auth/FlutterFacebookAuthPlugin.java:58: error: cannot find symbol
                facebookAuth.logOut(result);
                            ^
  symbol:   method logOut(Result)
  location: variable facebookAuth of type FacebookAuth

**Comment by darwin-morocho** [comment]
try `flutter clean`

**Comment by zaher-code-07** [comment]
I've deleted the whole cache using `dart pub cache clean`  then I tried again, it works
