### ISSUE TITLE
Login Failed : there's an issue with the implementation of Facebook Login

### ISSUE THREAD

**Issue by abakermi** [darwin-morocho/flutter-facebook-auth#161]
**Describe the bug**
issue with implementation of Facebook Login
**Environment**
 `flutter doctor -v` 
```
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.4 20F71 darwin-x64, locale en-QA)
    • Flutter version 2.5.0 at /Users/abdelhakakermi/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (4 weeks ago), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/abdelhakakermi/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1
```
`pubspec.yaml`
`flutter_facebook_auth: ^3.5.2`

**Expected behavior**
login success.

**Screenshots**
<img src="https://user-images.githubusercontent.com/60294727/135826363-2590de8e-857c-49f3-a3a0-e95eae2c3862.png" width="250"/>
.

**Comment by abakermi** [comment]
I have verified the key hash and everything is ok, Login only success with tester account, normal users give me an error

**Comment by darwin-morocho** [comment]
Hi @abakermi if you are trying to test the login flow using facebook account that are not developers  your app needs to be in the mode in your facebook developer console

**Comment by abakermi** [comment]
Hi @darwin-morocho , actually my app is live not in development mode and all permissions are live and working,I was trying the key hash verification  but everything is correct

**Comment by darwin-morocho** [comment]
> Hi @darwin-morocho , actually my app is live not in development mode and all permissions are live and working,I was trying the key hash verification but everything is correct

this is not an issue of this plugin. it seems a missing configuration in your facebook console 

https://github.com/facebook/facebook-android-sdk/issues/616#issuecomment-589016994

**Comment by darwin-morocho** [comment]
> > Hi @darwin-morocho , actually my app is live not in development mode and all permissions are live and working,I was trying the key hash verification but everything is correct
> 
> this is not an issue of this plugin. it seems a missing configuration in your facebook console
> 
> [facebook/facebook-android-sdk#616 (comment)](https://github.com/facebook/facebook-android-sdk/issues/616#issuecomment-589016994)
