### ISSUE TITLE
Update FB Login SDK to version 8.2+ by Oct. 5..?

### ISSUE THREAD

**Issue by marslannasr7koncepts** [darwin-morocho/flutter-facebook-auth#163]
I am using this Plugin on my Android app and just getting this email from Facebook I am bit confuse is this Plugin support latest sdk for both Platforms android and iOS or some change require from my side..

 I am using this Version flutter_facebook_auth: ^3.5.0
 
 Thanks

**Comment by darwin-morocho** [comment]
`flutter_facebook_auth:^3.5.2` uses the facebook android sdk 11.3.0

**Comment by marslannasr7koncepts** [comment]
What about flutter_facebook_auth: ^3.5.0 can you tell me on this version..

**SDK Version as well..? like you mention on 3.5.2**

> `flutter_facebook_auth:^3.5.2` uses the facebook android sdk 11.3.0 and on iOS uses 11.2.0

**Comment by darwin-morocho** [comment]
> What about flutter_facebook_auth: ^3.5.2


flutter_facebook_auth: ^3.5.0 yes  it uses sdk 11.0 on Android

**Comment by darwin-morocho** [comment]
> > What about flutter_facebook_auth: ^3.5.2
> 
> flutter_facebook_auth: ^3.5.0 yes it uses sdk 11.0 on Android

https://github.com/darwin-morocho/flutter-facebook-auth/blob/3.5.0/facebook_auth/android/build.gradle
