### ISSUE TITLE
Error on login with facebook app

### ISSUE THREAD

**Issue by Trteich** [darwin-morocho/flutter-facebook-auth#166]
Hi. Everything works correct when I log in with browser, but attempts to login with facebook app finished with error

'Login Error: There is an error in logging you into this application. Please try again later.'

OS: Android 10/11(no chance to try on IOS, I have no IOS device nearest couple of days)
Plugin: v3.5.2
Flutter doctor:
[√] Flutter (Channel stable, 2.5.2, on Microsoft Windows [Version 10.0.19041.1237], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code (version 1.57.0)
[√] Connected device (4 available)

**Comment by tuanbs** [comment]
When I tested on iOS to login with Facebook app, I got the error `The operation couldn’t be completed. (com.facebook.sdk.login error 304.)`. It works fine when I logged in with browser. Any idea please? Thanks in advance.

**Comment by tuanbs** [comment]
> When I tested on iOS to login with Facebook app, I got the error `The operation couldn’t be completed. (com.facebook.sdk.login error 304.)`. It works fine when I logged in with browser. Any idea please? Thanks in advance.

I solved it by adding `await FacebookAuth.instance.logOut();` before calling `await FacebookAuth.instance.login();`. But not sure if that's the correct way to fix this issue.
