### ISSUE TITLE
Error Login Facebook Android when not installed Facebook App

### ISSUE THREAD

**Issue by jordanjanaq** [darwin-morocho/flutter-facebook-auth#179]
I'm testint in android 9 and the app is closing after I try to login.
In iOS is working fine.

<img width="620" alt="Captura de Pantalla 2021-10-29 a la(s) 16 18 32" src="https://user-images.githubusercontent.com/48919342/139502846-ba248557-0c2d-4275-ab4f-6e9bc72c5af6.png">

![Screenshot_20211029_161739_com android chrome](https://user-images.githubusercontent.com/48919342/139503053-8fc3ec40-dc38-4880-8814-fca9dd275aa5.jpg)

flutter_f
![Screenshot_20211029_161747_com janaq goquick dev](https://user-images.githubusercontent.com/48919342/139503071-3235c77b-0782-4da7-adad-45be08ea9e51.jpg)

acebook_auth: ^3.5.3

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter doctor -v 
[✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale es-419)
    • Flutter version 2.5.2 at /Users/janaq/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 3595343e20 (4 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/janaq/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.57.1)
    • VS Code at /Users/janaq/Downloads/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • MRD LX3 (mobile)  • 5DN6R19228000295                     • android-arm    • Android 9 (API 28)
    • iPhone 7 (mobile) • 44BE9F7D-DC65-4661-B83C-EA95B6892699 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)      • chrome                               • web-javascript • Google Chrome 95.0.4638.54
    ! Error: iPhone de Jordan is not connected. Xcode will continue when iPhone de Jordan is connected. (code -13)

**Comment by darwin-morocho** [comment]
> I'm testint in android 9 and the app is closing after I try to login. In iOS is working fine.
> 
> <img alt="Captura de Pantalla 2021-10-29 a la(s) 16 18 32" width="620" src="https://user-images.githubusercontent.com/48919342/139502846-ba248557-0c2d-4275-ab4f-6e9bc72c5af6.png">
> 
> ![Screenshot_20211029_161739_com android chrome](https://user-images.githubusercontent.com/48919342/139503053-8fc3ec40-dc38-4880-8814-fca9dd275aa5.jpg)
> 
> flutter_f ![Screenshot_20211029_161747_com janaq goquick dev](https://user-images.githubusercontent.com/48919342/139503071-3235c77b-0782-4da7-adad-45be08ea9e51.jpg)
> 
> acebook_auth: ^3.5.3
> 
> environment: sdk: ">=2.12.0 <3.0.0"
> 
> flutter doctor -v [✓] Flutter (Channel stable, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale es-419) • Flutter version 2.5.2 at /Users/janaq/development/flutter • Upstream repository https://github.com/flutter/flutter.git • Framework revision 3595343e20 (4 weeks ago), 2021-09-30 12:58:18 -0700 • Engine revision 6ac856380f • Dart version 2.14.3
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3) • Android SDK at /Users/janaq/Library/Android/sdk • Platform android-31, build-tools 30.0.3 • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS • Xcode at /Applications/Xcode.app/Contents/Developer • Xcode 12.5.1, Build version 12E507 • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.2) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/9212-flutter • Dart plugin can be installed from: 🔨 https://plugins.jetbrains.com/plugin/6351-dart • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
> 
> [✓] VS Code (version 1.57.1) • VS Code at /Users/janaq/Downloads/Visual Studio Code.app/Contents • Flutter extension can be installed from: 🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [✓] Connected device (3 available) • MRD LX3 (mobile) • 5DN6R19228000295 • android-arm • Android 9 (API 28) • iPhone 7 (mobile) • 44BE9F7D-DC65-4661-B83C-EA95B6892699 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator) • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.54 ! Error: iPhone de Jordan is not connected. Xcode will continue when iPhone de Jordan is connected. (code -13)

The app is crashing or what? please be more exact with the problem

**Comment by darwin-morocho** [comment]
in your dart code don't use LoginBehavior.WEBVIEW in that case in the login method use LoginBehavior.nativeWithFallback

**Comment by jordanjanaq** [comment]
Hi, thanks for answering. 

I'm not using "LoginBehavior.WEBVIEW", this is my code:
<img width="595" alt="Captura de Pantalla 2021-10-29 a la(s) 16 46 09" src="https://user-images.githubusercontent.com/48919342/139505166-5c2e4cd6-d16c-41a4-ae93-55e5d73420bd.png">

How can I set LoginBehavior.nativeWithFallback?

Nice library, thank you so much.

**Comment by darwin-morocho** [comment]
> Hi, thanks for answering.
> 
> I'm not using "LoginBehavior.WEBVIEW", this is my code: <img alt="Captura de Pantalla 2021-10-29 a la(s) 16 46 09" width="595" src="https://user-images.githubusercontent.com/48919342/139505166-5c2e4cd6-d16c-41a4-ae93-55e5d73420bd.png">
> 
> How can I set LoginBehavior.nativeWithFallback?
> 
> Nice library, thank you so much.

the **login** method has a parameter called **loginBehavior**

**Comment by jordanjanaq** [comment]
Thank you so much for you help. It seems to work now.

<img width="612" alt="Captura de Pantalla 2021-10-29 a la(s) 17 44 32" src="https://user-images.githubusercontent.com/48919342/139508956-b6072484-0185-4a1f-b798-3acc98eecf83.png">
