### ISSUE TITLE
iOS application crashes when using UIWindowSceneDelegate

### ISSUE THREAD

**Issue by marcotta** [darwin-morocho/flutter-facebook-auth#180]
**Describe the bug**
iOS application crashes when using UIWindowSceneDelegate

**To Reproduce**
Use plugin on an app that uses UIWindowSceneDelegate
Try to login
Crashes trying to retrieve rootViewController from  `UIApplication.shared.delegate?.window`
https://github.com/darwin-morocho/flutter-facebook-auth/blob/f92dcc05f7a6c5129ee959801ab38b424cfce8a0/facebook_auth/ios/Classes/FacebookAuth.swift#L75

**Expected behavior**
Should try to find rootViewController also from main scene

**Comment by darwin-morocho** [comment]
please follow the issue template

**Comment by marcotta** [comment]
**Describe the bug**
iOS application crashes when using UIWindowSceneDelegate

**Environment**
Add your `flutter doctor -v`
[✓] Flutter (Channel unknown, 2.5.2, on macOS 11.6 20G165 darwin-x64, locale en-DE)
    • Flutter version 2.5.2 at /Users/marcotta/flutter
    • Upstream repository unknown
    • Framework revision 3595343e20 (4 weeks ago), 2021-09-30 12:58:18 -0700
    • Engine revision 6ac856380f
    • Dart version 2.14.3

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-12.5.1.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

Add your `pubspec.yaml`
flutter_facebook_auth: ^3.3.3+1

**To Reproduce**
Use plugin on an app that uses UIWindowSceneDelegate
Try to login
Crashes trying to retrieve rootViewController from UIApplication.shared.delegate?.window
https://github.com/darwin-morocho/flutter-facebook-auth/blob/f92dcc05f7a6c5129ee959801ab38b424cfce8a0/facebook_auth/ios/Classes/FacebookAuth.swift#L75

**Expected behavior**
Should try to find rootViewController also from main scene
