### ISSUE TITLE
Swift compile error - only avalible on ios 13

### ISSUE THREAD

**Issue by Horum-dev** [darwin-morocho/flutter-facebook-auth#182]
**Describe the bug**
it worked perfectly, we released the first app version.. than with the next build it fails. Tried to set up minimum os version to 13,14 - don't work. Tried to restart the mac and pod deintegrate..

**Environment**
Add your `flutter doctor -v`
`[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale ru-RU)
    • Flutter version 2.5.3 at /Users/roman/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (3 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/roman/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
`
Add your `pubspec.yaml`
`
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  panorama: ^0.4.1
  http: ^0.13.3
  firebase_auth: ^3.0.2
  connectivity: ^3.0.6
  yandex_mapkit:
    git:
      url: git://github.com/Unact/yandex_mapkit.git
  #  maps_launcher:
  webview_flutter: ^2.0.12
  hive_flutter: ^1.1.0
  audio_service: ^0.18.0
  just_audio: ^0.9.11
  in_app_purchase: ^1.0.8
  dots_indicator: ^2.0.0
  permission_handler: ^8.1.6
  google_sign_in: ^5.0.7
  flutter_facebook_auth: ^3.5.4
  sign_in_with_apple: ^3.0.0
  flutter_login_vk: ^2.0.0
  onesignal_flutter: ^3.2.3
  video_player: ^2.1.14
  carousel_slider: ^4.0.0
  location: ^4.3.0
  #https://wiki.openstreetmap.org/wiki/API
#  flutter_osm_plugin: 0.21.0
  flutter_svg: ^0.22.0
  path_provider: ^2.0.5
 # flutter_sound_lite: ^8.4.1
  auto_size_text: ^3.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3`

**To Reproduce**
Don't know...

**Screenshots**
If applicable, add screenshots or videos to help explain your problem
<img width="1204" alt="Снимок экрана 2021-11-03 в 12 40 48" src="https://user-images.githubusercontent.com/67152395/140037987-074e992e-218b-40d9-8e55-4b5eb22497eb.png">
<img width="1226" alt="Снимок экрана 2021-11-03 в 12 41 15" src="https://user-images.githubusercontent.com/67152395/140038054-c2465c4b-54df-4e94-8eab-42eee9a24fb3.png">
.

**Comment by vixez** [comment]
I have the same issue, it is broken due to 3.5.4 (PR https://github.com/darwin-morocho/flutter-facebook-auth/pull/181) not being compatible with older iOS versions.
As XCode suggests, the `if #available` checks should be added.

**Comment by darwin-morocho** [comment]
In xcode set deployment target to 13 I will add the swift validation code in the next release

**Comment by Horum-dev** [comment]
> In xcode set deployment target to 13 I will add the swift validation code in the next release

setted deployment target to 14.1 and nothing..

manually fixed the issue in the swift file😅

**Comment by darwin-morocho** [comment]
fixed on **3.5.5**

**Comment by vixez** [comment]
Seems to work, thanks 👍
