### ISSUE TITLE
Display "Unsupported request" after logging Facebook

### ISSUE THREAD

**Issue by FunNot404** [darwin-morocho/flutter-facebook-auth#185]
**Description**
Our app was deactivated by Facebook due to this broken. 
We have three platform, website (not flutter app), iOS and Android. Only iOS and Android app were encountering the login issue.
They worked perfectly until we received the deactivation from Facebook. :(
We even checked permissions and dashboard configurations on the Facebook Developer, but we only use basic permission requests (email, public_profile).

Thanks for helping!!

**Implement code**
```=dart
try {
      var result = await (facebookAuth ?? FacebookAuth.instance).login();
      print(result.status);
      if (result.status == LoginStatus.success) {
        final AccessToken accessToken = result.accessToken!;
        print(accessToken.token);
        var value = await RepoHelper.auth.loginFacebook(accessToken.token);
        onSuccess?.call(value?.authToken);
      } else {
        print('onFailed?.call');
        onFailed?.call(result.message);
      }
    } catch (err) {
      print(err.toString());
      onFailed?.call(err.toString());
    }
```

**Screenshots**
![IMG_0869](https://user-images.githubusercontent.com/20190546/141058525-6d927867-7394-41d4-9243-1bb7d71a8429.jpg)
![IMG_0870](https://user-images.githubusercontent.com/20190546/141058532-a50f9ac0-05ee-4204-9975-9ed434bd9267.PNG)

**Environment**
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.5.2 20G95 darwin-x64, locale zh-Hant-TW)
    • Flutter version 2.2.1 at /Users/jasontsai/flutter
    • Framework revision 02c026b03c (6 months ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/jasontsai/Library/Android/sdk
    • Platform android-31, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • RMX2144 (mobile) • d3998c89 • android-arm64  • Android 11 (API 30)
    • Chrome (web)     • chrome   • web-javascript • Google Chrome 95.0.4638.69

• No issues found!

**Comment by FunNot404** [comment]
The situation was solved! 
It's not this plugin issue. 
It seems the app verification from Facebook.
We mailed Facebook and provided some information, 
and Facebook team restored the app today.

Thanks again!

**Comment by hakivin** [comment]
@FunNot404 can you please provide information that you send to Facebook? I just found this same issue and currently can't solve
thank you

**Comment by hakivin** [comment]
> The situation was solved! It's not this plugin issue. It seems the app verification from Facebook. We mailed Facebook and provided some information, and Facebook team restored the app today.
> 
> Thanks again!

@FunNot404 can you please provide information that you send to Facebook? I just found this same issue and currently can't solve
thank you

**Comment by bayysp** [comment]
@FunNot404 I got the same issues just like yours, please provide us how did you fix it.
FYI when I print error logs from dependencies issues I got the message error `com.facebook.sdk.core error 8`

Thank's

**Comment by FunNot404** [comment]
@hakivin Sure!
This envelope was replied to Facebook Team about the policy at first time:
![951EC689-1481-4D43-A8CF-5D339583A4B5](https://user-images.githubusercontent.com/20190546/142165543-016b343e-6f71-44cd-9dd4-f5394ae8a5bc.jpeg)

This is the second mail to reply a screen record from Facebook Team for debugging:
![D3A69AA1-558C-4DAF-88E1-1FAD5FCDEC28](https://user-images.githubusercontent.com/20190546/142165552-08594b75-69ea-4014-bf98-4c8074d437f3.jpeg)

Then Facebook restored our app.

**Comment by FunNot404** [comment]
I still confused why Facebook deactivated our app and restored it after these conversations. Maybe they are seriously reviewing the apps developed by individuality, I guessed 😂
