### ISSUE TITLE
facebook.GraphResponse(30948): {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '111111111...' does not exist, cannot be loaded due to missing permissions

### ISSUE THREAD

**Issue by Zelfapp** [darwin-morocho/flutter-facebook-auth#186]
**Describe the bug**
On Android, app starts up and there are 2 issues I've detailed here in the logs and I cannot sign in to Facebook. As you can see in the screenshot when I attempt to sign in with a test user (my FB app is still in development mode) I get the error in the screenshot.

> **Issue 1**: Starting with v13 of the SDK, a client token must be embedded in your client code before making Graph API calls. Visit https://developers.facebook.com/docs/android/getting-started#client-token to learn how to implement this change.

The [android installation docs](https://facebook.meedu.app/#/android) do not mention a `facebook_client_token`. Once I did the following **Issue 1** disappeared. However, **Issue 2** still exists and I cannot Sign in with facebook.

[Here](https://developers.facebook.com/docs/android/getting-started#app_id) you can see this is now required in strings.xml.

```
<string name="facebook_app_id">Facebook App ID</string>
<string name="facebook_client_token">Facebook Client ID</string>
```

And in AndroidManifest.xml

```
<application android:label="@string/app_name" ...>
    ...
    <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
    ...
</application>
```

> **Issue 2:** E/com.facebook.GraphResponse(31224): {HttpStatus: 400, errorCode: 100, subErrorCode: 33, errorType: GraphMethodException, errorMessage: Unsupported get request. Object with ID '111111111...' does not exist, cannot be loaded due to missing permissions, or does not support this operation.

I'm not sure how to overcome **Issue 2** and I don't see anything docs regarding graph api permissions configurations?

**Environment**
flutter_facebook_auth: ^3.5.6

<details><summary>flutter doctor -v</summary>

```dart
[✓] Flutter (Channel stable, 2.5.3, on Manjaro Linux 5.4.150-1-MANJARO, locale
    en_US.UTF-8)
    • Flutter version 2.5.3 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0-rc2)
    • Android SDK at /home/nate/Android/Sdk
    • Platform android-31, build-tools 31.0.0-rc2
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /home/nate/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /usr/bin/google-chrome-stable

[✓] Android Studio (version 2020.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 62.0.1
    • Dart plugin version 203.8452
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • sdk gphone x86 64 arm64 (mobile) • emulator-5554 • android-x64    •
      Android 11 (API 30) (emulator)
    • Chrome (web)                     • chrome        • web-javascript • Google
      Chrome 95.0.4638.69

• No issues found!
```

</details>

**To Reproduce**
[Using with firebase auth](https://facebook.meedu.app/#/firebase-auth).

Android docs maybe need to be updated? Or, have I made a configuration issue in regards to **Issue 2**? Why is FB trying to auth a user when the app is loading and the user is signed out? I guess that is why there is an error in startup?

![image](https://user-images.githubusercontent.com/11559805/141293388-aedcb4b2-7cb3-4cea-86f5-da4c70149c86.png)

**Expected behavior**
No errors in logs and to be able to login using facebook while my FB app is still in development mode.

**Comment by Zelfapp** [comment]
Regarding **Issue 2** this was resolved by requesting `Advanced Access` in my FB app's Permissions and Features.

![image](https://user-images.githubusercontent.com/11559805/141299724-8270a637-a842-4252-9603-c6cf2beb48c7.png)

Again, on **Issue 1** and **Issue 2** I would suggest updating the install docs for Android. Thanks.

**Comment by danielgomezrico** [comment]
@darwin-morocho why did you close the issue? is this solved?

**Comment by darwin-morocho** [comment]
> @darwin-morocho why did you close the issue? is this solved?

Hi this is not an issue of this plugin for that reason I have closed it
