### ISSUE TITLE
The operation couldn’t be completed. (com.facebook.sdk.core error 8.)

### ISSUE THREAD

**Issue by hakivin** [darwin-morocho/flutter-facebook-auth#187]
**Describe the bug**
on iOS, after called `facebookAuth.login()`, the function returned error like this `The operation couldn’t be completed. (com.facebook.sdk.core error 8.)`. Login success on Android.

**Environment**
Add your `flutter doctor -v`
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-arm, locale
    en-ID)
    • Flutter version 2.5.1 at /Users/refactory-mac/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (9 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/refactory-mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (2 available)
    • iPhone 13 (mobile) • F9649041-40C4-4E45-8D9B-8032E9F1ED82 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)       • chrome                               • web-javascript
      • Google Chrome 96.0.4664.45

• No issues found!

Add your `pubspec.yaml`
flutter_facebook_auth: 3.3.2-no-nullsafety

Add your `Info.plist`
i've followed the [official documentation](https://developers.facebook.com/docs/facebook-login/ios/)
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
  <key>CFBundleURLSchemes</key>
  <array>
    <string>fbAPP-ID</string>
  </array>
  </dict>
</array>
<key>FacebookAppID</key>
<string>APP-ID</string>
<key>FacebookClientToken</key>
<string>CLIENT-TOKEN</string>
<key>FacebookDisplayName</key>
<string>APP-NAME</string>
```

Add your `AppDelegate.m`
is these lines of code affected error?
```
#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
#import <FBSDKCoreKit/FBSDKCoreKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
  [FIRApp configure];
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
    
    BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                  openURL:url
                                                        sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                               annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                    ];
    // Add any custom logic here.
    return handled;
}

@end
```

**To Reproduce**
```
    try {
      String tokenSignIn = '';
      FacebookAuth facebookLogin = FacebookAuth.instance;
      facebookLogin.logOut();
      LoginResult result = await facebookLogin.login();
      tokenSignIn = result.accessToken.token;
      http.Response response = await http.get(
          'https://graph.facebook.com/v2.12/me?fields=id,name,email&access_token=$tokenSignIn');
      Map<String, dynamic> profile = jsonDecode(response.body);
      profile['token'] = tokenSignIn;
    } catch (e) {
      rethrow e;
    }
```

**Comment by darwin-morocho** [comment]
this plugin was. created with swift for ios because I don't know objc considere change the language to swift for ios

**Comment by ariona** [comment]
any update for this issue? i already use swift for my project. still getting `The operation couldn’t be completed. (com.facebook.sdk.core error 8.)`

**Comment by darwin-morocho** [comment]
> 

this is not an issue of this plugin it seems a bad configuration https://github.com/facebook/facebook-ios-sdk/issues/1395#issuecomment-639471504

**Comment by ariona** [comment]
@darwin-morocho i have added what in issue comment and`LSApplicationQueriesSchemes` but still no luck.

**Comment by hakivin** [comment]
@ariona I could partially solve this by downgrade the FBSDKCoreKit version to 8.2.0 for iOS and make it web view only (only for iOS because Facebook SDK policy on android device when logged in with web view)
somehow Facebook SDK has error in SDK 9.xx version

**Comment by darwin-morocho** [comment]
> @darwin-morocho i have added what in issue comment and`LSApplicationQueriesSchemes` but still no luck.

try to use the lastest version of this plugin. if your project doesn't have support for null safety I am sorry I won't adding support  for no null safety projects

**Comment by darwin-morocho** [comment]
Closed because we don't have a response of the creator
