### ISSUE TITLE
Documentation is offline

### ISSUE THREAD

**Issue by teixeirazeus** [darwin-morocho/flutter-facebook-auth#188]
https://facebook.meedu.app
![](https://i.postimg.cc/52cjrh6s/Captura-de-tela-de-2021-11-30-10-56-15.png)

**Comment by darwin-morocho** [comment]
try to cleaning your cache, I have checked it and the website works fine

**Comment by teixeirazeus** [comment]
Thanks for the answer.
By clearing the cache I can get past the loading part. However, I'm on this blank screen.
I use PopOS, updated my system and restarted, to make sure everything is up to date.
If it works for you, I have no idea what's going on.
In the image I tested it with chrome and firefox.
![](https://i.postimg.cc/Df1BMXfs/Captura-de-tela-de-2021-11-30-11-20-40.png)

**Comment by darwin-morocho** [comment]
the website is hosted by github so I'm not sure why you can see it.

**Comment by darwin-morocho** [comment]
try to see the browser logs

**Comment by teixeirazeus** [comment]
> try to see the browser logs

Nice.
![](https://i.postimg.cc/YCTdPfF6/Captura-de-tela-de-2021-11-30-11-25-28.png)

**Comment by teixeirazeus** [comment]
Apparently it can't load vue js
https://cdn.jsdelivr.net/npm/docsify/themes/vue.css

**Comment by darwin-morocho** [comment]
I am using docsify to generate the website template. I will change to docusaurus but that will take a long time

**Comment by teixeirazeus** [comment]
> it seems a problem with your OS. Could you check in your mobile phone?

Yes, same thing.
![](https://i.postimg.cc/rsNqzw1m/Whats-App-Image-2021-11-30-at-11-39-28.jpg)



> I am using docsify to generate the website template. I will change to docusaurus but that will take a long time


I believe this will solve the problem.
Thank you for your help.

**Comment by jimaek** [comment]
The most often cause of jsDelivr not working is an incorrectly configured internal firewall or DNS. If the problem persists please open an issue at https://github.com/jsdelivr/jsdelivr and we will help you debug it

**Comment by darwin-morocho** [comment]
@teixeirazeus Can you check cleaning your cache again? now it should works

**Comment by teixeirazeus** [comment]
@darwin-morocho works.
Thanks :D
