### ISSUE TITLE
FBSDKCoreKit is not updated. Can you please update the same so that it works with other packages?

### ISSUE THREAD

**Issue by dwarimaheshwari** [darwin-morocho/flutter-facebook-auth#189]
CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In Podfile:
    facebook_app_events (from .symlinks/plugins/facebook_app_events/ios) was resolved to 0.0.1, which depends on
      FBSDKCoreKit (~> 12.1.0)

    flutter_facebook_auth (from .symlinks/plugins/flutter_facebook_auth/ios) was resolved to 3.5.3, which depends on
      FBSDKCoreKit (~> 12.0.2)

**Comment by darwin-morocho** [comment]
@dwarimaheshwari check flutter_facebook_auth 3.5.6+1

**Comment by dwarimaheshwari** [comment]
@darwin-morocho working now. Thank you so much.
