### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by KHChanna** [darwin-morocho/flutter-facebook-auth#194]
Thanks for the package !

I have following the setup but can not build in android.

e: /Users/jecy/.gradle/caches/transforms-2/files-2.1/24fa3aa8d2270e5eb067bbe36e9b7563/jetified-kotlin-stdlib-1.5.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/jecy/.gradle/caches/transforms-2/files-2.1/38f92314671ee5340cbd0a5f71832b19/jetified-kotlin-stdlib-jdk7-1.5.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.
e: /Users/jecy/.gradle/caches/transforms-2/files-2.1/77bab1911042ab2c6d5cc0b2e2ee053c/jetified-kotlin-stdlib-common-1.5.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by darwin-morocho** [comment]
This plugin was written with java so the issue is not of this plugin. It seems you need to update your kotlin version and your gradle version

**Comment by KHChanna** [comment]
Thanka.

> This plugin was written with java so the issue is not of this plugin. It seems you need to update your kotlin version and your gradle version

Thanks
