### ISSUE TITLE
iOS: Login Error: There is an error in logging you into this application. Please try again later

### ISSUE THREAD

**Issue by MuhammadFaizan980** [darwin-morocho/flutter-facebook-auth#197]
**Bug Description**
I am using `flutter_facebook_auth: ^3.5.7` for authentication in my project. Auth works fine on **Android** but on **iOS**, I get following issue: **Login Error: There is an error in logging you into this application. Please try again later** in the safari.
Screenshot at: https://i.stack.imgur.com/aPKe7.jpg

**Environment Setup**
Following is my `flutter doctor` output:

    `Doctor summary (to see all details, run flutter doctor -v):
    [✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-arm, locale en-PK)
    [!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
    Run `path/to/sdkmanager --install "cmdline-tools;latest"`
    See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
    Run `flutter doctor --android-licenses` to accept the SDK licenses.
    See https://flutter.dev/docs/get-started/install/macos#android-setup for more 
    details.
    [✓] Xcode - develop for iOS and macOS
    [✓] Chrome - develop for the web
    [✓] Android Studio (version 2020.3)
    [✓] VS Code (version 1.63.0)
    [✓] Connected device (2 available)`

And following is my **info.plist** file

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
    <plist version="1.0">
    <dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(app_name_prefix) who!cares</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(MARKETING_VERSION)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
			    <string>fb797916770737670</string>
				<string>com.googleusercontent.apps.578552594778-7dtdegnpou7f7th64u9ia77u5odmn7oc</string>
			</array>
		</dict>

		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.tentwenty.whocares</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.tentwenty.whocares</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>EKKX3JHL9Y.com.tentwenty.whocares</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.265580074569-rd1uhp5h42rc6opmlashagb5b4cnh9lr</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.tentwenty.whocares.dev</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.tentwenty.whocares.dev</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>EKKX3JHL9Y.com.tentwenty.whocares.dev</string>
			</array>
		</dict>
	</array>
	<key>CFBundleVersion</key>
	<string>$(CURRENT_PROJECT_VERSION)</string>

	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>FirebaseDynamicLinksCustomDomains</key>
	<array>
		<string>https://app.whocares.app</string>
		<string>https://whocares.page.link</string>
	</array>

    <key>FacebookAppID</key>
    <string>797916770737670</string>
    <key>FacebookClientToken</key>
    <string>0ffc854b7fc76f8f60bc4a58f7cb0bc3</string>
    <key>FacebookDisplayName</key>
    <string>WhoCares!</string>
    <key>LSApplicationQueriesSchemes</key>
       <array>
          <string>fbapi</string>
          <string>fb-messenger-share-api</string>
          <string>fbauth2</string>
          <string>fbshareextension</string>
        </array>

	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>NSCameraUsageDescription</key>
	<string>This let's you choose your display picture for the app</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>This let's you choose your display picture for the app</string>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIUserInterfaceStyle</key>
	<string>Light</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<true/>
	<key>io.flutter.embedded_views_preview</key>
	<true/>
    </dict>
    </plist>

**To Reproduce**
N/A

**Expected Behaviour**
User login success,

**Comment by darwin-morocho** [comment]
@MuhammadFaizan980 please follow the issue template

**Comment by darwin-morocho** [comment]
it seems a problem with your facebook developer console. May be this can help you https://github.com/darwin-morocho/flutter-facebook-auth/issues/186#issuecomment-966271124

**Comment by MuhammadFaizan980** [comment]
Done, 

> it seems a problem with your facebook developer console. May be this can help you [#186 (comment)](https://github.com/darwin-morocho/flutter-facebook-auth/issues/186#issuecomment-966271124)

Yeah, issue was with facebook app, would you please add this point to package documentation as well? thanks
