### ISSUE TITLE
The Android platform cannot obtain email information

### ISSUE THREAD

**Issue by szxv587** [darwin-morocho/flutter-facebook-auth#199]
The Android platform cannot obtain email information

**Comment by darwin-morocho** [comment]
> The Android platform cannot obtain email information

Please follow the issue template

**Comment by szxv587** [comment]
I have a question. If the user refuses the email permission, can the permission box pop up for the user to choose when he or she requests login next time?

**Comment by darwin-morocho** [comment]
It can't. The next login time facebook will return the previous permissions. To do that the user needs to manually delete the app from their apps in his facebook account
