### ISSUE TITLE
Does this plugin use UIWebView API's ?

### ISSUE THREAD

**Issue by sallymariehollywood** [darwin-morocho/flutter-facebook-auth#2]
Hi

Thank you for this plugin. I am currently using 

https://github.com/roughike/flutter_facebook_login

But it seems that the author is no longer maintaining and their plugin uses deprecated UIWebView API's - this means that **ANY** new submissions to the APP Store will be refused.

Can you kindly advise if using your plugin uses latest Facebook SDK and **doesnt use** deprecated UIWebView

**Comment by awhitford** [comment]
It appears that it does use `UIWebView`.  😢

**Comment by awhitford** [comment]
Actually, according to [Facebook iOS SDK Release Notes](https://github.com/facebook/facebook-ios-sdk/blob/master/CHANGELOG.md), the `UIWebView` was removed with version 5.5; as long as you are using that version or newer, you may be OK.

**Comment by darwin-morocho** [comment]
I've updated the library to remove UIWebView on iOS
