### ISSUE TITLE
Login with different user

### ISSUE THREAD

**Issue by erperejildo** [darwin-morocho/flutter-facebook-auth#200]
Cannot login with a different user despite I run `await FacebookAuth.instance.logOut();`

Because of this, Apple is complaining and I cannot update my app either for iOS.

Log in works fine with `final LoginResult result = await FacebookAuth.instance.login();`

**Comment by erperejildo** [comment]
flutter_facebook_auth: ^3.5.7

**Comment by darwin-morocho** [comment]
@erperejildo check this https://github.com/darwin-morocho/flutter-facebook-auth/issues/33#issuecomment-730046078

**Comment by erperejildo** [comment]
I don't understand why Apple is complaining about this then. I'll like then to that. Thanks.
I'll post here their answer
