### ISSUE TITLE
Facebook ID

### ISSUE THREAD

**Issue by water-user** [darwin-morocho/flutter-facebook-auth#201]
What the ID in FacebookAuth used for? i mean:

```
final userData = await FacebookAuth.instance.getUserData();
final id = userData['id'];
```

I tried it in facebook url, e.g https://www.facebook.com/profile.php?id=XXXXXXX and the page is not found.

I googled it and doesn't find any answer about it. and if this ID is static or can to be change sometimes.

**Comment by darwin-morocho** [comment]
this is not a valid issue for this plugin
