### ISSUE TITLE
No implementation found

### ISSUE THREAD

**Issue by Brencheva** [darwin-morocho/flutter-facebook-auth#203]
**Describe the bug**
What should I do if I've already run the project without android configuration and faced the error? What should I do to remove the error? I've tried to reinstall the plugin but it hasn't helped

**Comment by darwin-morocho** [comment]
the Facebook sdk throws an exception when the sdk is not configured and this locks the other plugins initialization so the plugin cannot control this. But you can do the Android configuration with fake data to avoid this

**Comment by darwin-morocho** [comment]
> **Describe the bug**
> What should I do if I've already run the project without android configuration and faced the error? What should I do to remove the error? I've tried to reinstall the plugin but it hasn't helped

please read the documentation

**Comment by Brencheva** [comment]
But I already set the configuration. What should I do to make it's working?
--
Sent from Mail.ru app for Android Sunday, 26 December 2021, 04:02PM +01:00 from Darwin Morocho  ***@***.*** :

**Comment by darwin-morocho** [comment]
try with `flutter clean`  Also you must follow the issue template to check what is wrong with your configuration
