### ISSUE TITLE
pub.dev link?

### ISSUE THREAD

**Issue by duzenko** [darwin-morocho/flutter-facebook-auth#204]
Please add link to pub.dev in readme.md for easy navigation from github
See other popular packages for reference

**Comment by darwin-morocho** [comment]
https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth

**Comment by duzenko** [comment]
> https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth

https://github.com/darwin-morocho/flutter-facebook-auth
