### ISSUE TITLE
can't upload my app to appstore due to : New apps that use UIWebView are no longer accepted. Instead, use WKWebView

### ISSUE THREAD

**Issue by AbhayDeligence** [darwin-morocho/flutter-facebook-auth#207]
**Describe the bug**
flutter facebook auth uses webview plugin inbuild and uses UIWebView which is not accepted by apple now.

**Environment**

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^1.2.3
  pin_code_fields: ^2.3.0+3
  swipe_stack: ^1.0.0
  flutter_swiper: ^1.1.6
  intl: ^0.16.1
  firebase_auth: 
  cloud_firestore: 
  # geolocator: ^6.1.13
  location: 
  geocoder: ^0.2.1
  image_picker: ^0.6.3+4
  image_cropper: ^1.2.1
  firebase_storage: ^3.1.3
  path_provider:
  cached_network_image: ^2.0.0
  share: ^0.6.3+6
  firebase_messaging: ^6.0.13
  in_app_purchase: ^0.4.0
  rflutter_alert: ^1.0.3
  agora_rtc_engine: 1.0.5
  permission_handler: ^3.0.0
  flutter_ringtone_player: ^2.0.0
  shimmer: ^1.1.1
  apple_sign_in: ^0.1.0
  url_launcher:
  flutter_mapbox_autocomplete: ^1.0.4
  #firebase_admob: 0.11.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #flutter_facebook_auth: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: "^0.0.1"
  
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "asset/Icon/icon.png" 

flutter_launcher_name:
  name: "PartnerMeets"

**To Reproduce**
Issue : 
 
Dear Developer,
We identified one or more issues with a recent delivery for your app, "PartnerMeet" 1.1.1 (7). Please correct the following issues, then upload again.ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).
Best regards,
The App Store Team

**Comment by darwin-morocho** [comment]
This is not an issue of this plugin. This plugin uses the lastest version of the ios sdk so you have other plugin using uiwebview
