### ISSUE TITLE
Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by shubh66** [darwin-morocho/flutter-facebook-auth#208]
* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.google.protobuf:protobuf-java-util:3.10.0.
     Required by:
         project : > com.android.tools.build:gradle:4.1.1
      > Could not resolve com.google.protobuf:protobuf-java-util:3.10.0.
         > Could not get resource 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.10.0/protobuf-java-util-3.10.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.10.0/protobuf-java-util-3.10.0.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.crypto.tink:tink:1.3.0-rc2.
     Required by:
         project : > com.android.tools.build:gradle:4.1.1
      > Could not resolve com.google.crypto.tink:tink:1.3.0-rc2.
         > Could not get resource 'https://jcenter.bintray.com/com/google/crypto/tink/tink/1.3.0-rc2/tink-1.3.0-rc2.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/crypto/tink/tink/1.3.0-rc2/tink-1.3.0-rc2.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.google.protobuf:protobuf-java-util:3.10.0.
     Required by:
         project : > com.android.tools.build:gradle:4.1.1 > com.android.tools.build:bundletool:0.14.0
      > Could not resolve com.google.protobuf:protobuf-java-util:3.10.0.
         > Could not get resource 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.10.0/protobuf-java-util-3.10.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/protobuf/protobuf-java-util/3.10.0/protobuf-java-util-3.10.0.pom'. Received status code 502 from server: Bad Gateway

**Comment by darwin-morocho** [comment]
You may also need to add the following to your project/build.gradle file.

buildscript {
    repositories {
        mavenCentral()
    }
}

**Comment by shubh66** [comment]
> buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        mavenLocal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


------------------->
[+15261 ms] FAILURE: Build failed with an exception.
[  +20 ms] * What went wrong:
[   +1 ms] A problem occurred configuring root project 'android'.
[        ] > Could not resolve all artifacts for configuration ':classpath'.
[        ]    > Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32.
[   +1 ms]      Searched in the following locations:
[        ]        - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.4.32/kotlin-gradle-plugin-1.4.32.pom
[        ]        - file:/Users/shubh/.m2/repository/org/jetbrains/kotlin/kotlin-gradle-plugin/1.4.32/kotlin-gradle-plugin-1.4.32.pom
[        ]      Required by:
[        ]          project :
[        ]    > Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.10.
[        ]      Searched in the following locations:
[        ]        - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/kotlin-stdlib-jdk8-1.4.10.pom
[        ]        - file:/Users/shubh/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/kotlin-stdlib-jdk8-1.4.10.pom
[        ]      Required by:
[        ]          project : > com.android.tools.build:gradle:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:aaptcompiler:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.lint:lint-gradle-api:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:gradle-api:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > androidx.databinding:databinding-compiler-common:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools.build:builder-model:4.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools:sdk-common:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools:common:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools.build:manifest-merger:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools.analytics-library:tracker:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.lint:lint-gradle-api:27.1.3 > com.android.tools.lint:lint-model:27.1.3
[        ]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools:sdklib:27.1.3 > com.android.tools:repository:27.1.3
[   +6 ms]          project : > com.android.tools.build:gradle:4.1.3 > com.android.tools.build:builder:4.1.3 > com.android.tools:sdk-common:27.1.3 >

--------------------------------------------->
Tried all Gradle version.

**Comment by shubh66** [comment]
> You may also need to add the following to your project/build.gradle file.
> 
> buildscript { repositories { mavenCentral() } }
> 
> Also jcenter now is deprecated and it will be removed on Android [flutter/flutter#82847](https://github.com/flutter/flutter/issues/82847)

Update gradle and place mavenCentral().
