### ISSUE TITLE
App go to route "/" when facebook login finish popup

### ISSUE THREAD

**Issue by heshesh2010** [darwin-morocho/flutter-facebook-auth#213]
Hi ,

I'm runing on   flutter_facebook_auth: ^4.0.1
with flutter environment:
  sdk: '>=2.12.0 <3.0.0' #">=2.7.0 <3.0.0"

when my facebook finish login and backt to same screen i found 
" Route<dynamic> generateRoute(RouteSettings settings)  " called with " / " 

any idea ?

**Comment by darwin-morocho** [comment]
@heshesh2010 sorry but your question is not clear. please add more info or follow the issue template.

**Comment by darwin-morocho** [comment]
Closed by inactivity
