### ISSUE TITLE
Upgrading from 3.57 to 4.0.1 version leads to Android runtime error

### ISSUE THREAD

**Issue by idish** [darwin-morocho/flutter-facebook-auth#215]
**Describe the bug**
I've tried to update the flutter-facebook-auth library from 3.5.7 to 4.0.1 in pubspec.yaml and that caused the following runtime error:

```
FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(18088): Process: mypackage PID: 18088
E/AndroidRuntime(18088): java.lang.NoSuchMethodError: No static method setAppEventAttributionParameters(Lorg/json/JSONObject;Lcom/facebook/internal/AttributionIdentifiers;Ljava/lang/String;Z)V in class Lcom/facebook/internal/Utility; or its super classes (declaration of 'com.facebook.internal.Utility' appears in /data/app/~~qj3MXFV5Rm4BT6fk8qBXXQ==/mypackage-Hn7InsqH0jVx3vZtd3547g==/base.apk)
E/AndroidRuntime(18088): 	at com.facebook.applinks.AppLinkData.fetchDeferredAppLinkFromServer(AppLinkData.java:165)
E/AndroidRuntime(18088): 	at com.facebook.applinks.AppLinkData.access$000(AppLinkData.java:50)
E/AndroidRuntime(18088): 	at com.facebook.applinks.AppLinkData$1.run(AppLinkData.java:151)
```

Reverting back to 3.5.7 version will solve this kind of exception.

**Environment**
Add your `flutter doctor -v:
https://pastebin.com/vwnimYwa

Add your `pubspec.yaml`:
https://pastebin.com/891cKJF0

**Comment by darwin-morocho** [comment]
it seems a cache problem you should try  `flutter clean` after upgrade Also check the migration guide to avoid problems on iOS

**Comment by idish** [comment]
I did flutter clean multiple times, issue still persists.
Also, I'm not developing for iOS yet, but thanks for noting that.

**Comment by msisinni** [comment]
Not related to this issue, but in case anyone else has an issue with updating from 3.5.7 to 4+ with iOS, here's the migration guide: https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/website/docs/migration-guide.md

It was still failing for me with an M1 Macbook. What fixed it was commenting out the library in pubspec.yaml and running `flutter pub get` like it says to do in the migration guide, and running the following (in terminal starting at my flutter project root) after commenting out the library.
```
cd ios/
sudo arch -x86_64 gem install ffi
arch -x86_64 pod install --repo-update
```
Then uncomment the library in pubspec.yaml, run `flutter pub get` again in the project root, and run those 3 lines again.

Also unrelated, but the same steps fixed the same issue with Firebase's Flutter libraries.

**Comment by darwin-morocho** [comment]
closed by inactivity
