### ISSUE TITLE
Is it has Flutter GraphApi interface use to request e.g. /me/ids_for_business graph path messages?

### ISSUE THREAD

**Issue by YuanYQ** [darwin-morocho/flutter-facebook-auth#216]
Is it has Flutter GraphApi interface use to request e.g. /me/ids_for_business graph path messages?  if not ,Can you add it?

**Comment by darwin-morocho** [comment]
Hi this plugin doesn't support that operation because you can use the access token to make a request to the GraphApi using http or dio.
