### ISSUE TITLE
Using old sdk for ios and android

### ISSUE THREAD

**Issue by daiki1003** [darwin-morocho/flutter-facebook-auth#217]
**Describe the bug**
Although [v12.3.2 for iOS](https://github.com/facebook/facebook-ios-sdk/releases/tag/v12.3.2) and [v12.3.0 for Android](https://github.com/facebook/facebook-android-sdk/releases/tag/sdk-version-12.3.0) has been released as the latest version of SDK.
But, `flutter_facebook_auth` package will only be updated to `v12.2.1` and `v12.2.0` respectively.

**Environment**

Add your `flutter doctor -v`
https://pastebin.com/4rDGAkUU

**Comment by darwin-morocho** [comment]
@daiki1003 check `flutter_facebook_auth: ^4.1.0`

**Comment by daiki1003** [comment]
@darwin-morocho 
Thanks :)
