### ISSUE TITLE
is that package working with Windows

### ISSUE THREAD

**Issue by worldwidee** [darwin-morocho/flutter-facebook-auth#219]
is that package working with Windows because,
when i try to login with facebook in my windows app i get this platform err:
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

**Comment by darwin-morocho** [comment]
only Android,ios and web are supported
