### ISSUE TITLE
Upgrade Facebook SDK version to `13.0.0`

### ISSUE THREAD

**Issue by asashour** [darwin-morocho/flutter-facebook-auth#223]
It seems Using version `4.1.1` is using `v12.3.0`, as shown in Facebook app advanced settings.

![image](https://user-images.githubusercontent.com/2410127/158591579-784155d1-644d-420a-9409-a1ade35e1249.png)

**Comment by darwin-morocho** [comment]
@asashour check https://pub.dev/packages/flutter_facebook_auth/changelog#412

**Comment by asashour** [comment]
Thanks a lot for the very quick response.
