### ISSUE TITLE
Scrollbar appears to the left in webview_flutter

### ISSUE THREAD

**Issue by y1row** [darwin-morocho/flutter-facebook-auth#225]
https://github.com/flutter/flutter/issues/100677

As reported here, for some reason, using this plugin and `webview_flutter` at the same time changes the position of the scrollbar display.
Is there any solution to this problem?

**Comment by darwin-morocho** [comment]
This plugin uses the native Facebook sdk so if you are getting an unexpected behavior with flutter view there is nothing what I can do to solve this probably in the next version of Facebook sdk this could be solved

**Comment by y1row** [comment]
Thanks for the reply.
This is not happening in Flutter 2.5.2, just versioned up to Flutter 2.10.3. Should I report this to the Flutter team?

**Comment by darwin-morocho** [comment]
> Thanks for the reply.
> This is not happening in Flutter 2.5.2 and 2.8.2, just versioned up to Flutter 2.10.3. Should I report this to the Flutter team?

Yes,you should

**Comment by y1row** [comment]
I understand. Thank you.
