### ISSUE TITLE
Graph Api

### ISSUE THREAD

**Issue by gulmensedat** [darwin-morocho/flutter-facebook-auth#226]
For Instagram Graph Api, it has separated Consumer and Business type applications. I couldn't find a way to login with http. So using Facebook sdk natively (with updated sdk) https://developers.facebook.com/docs/instagram-api/overview#authentication

We need to get permission for this place,

here is more descriptive:

https://developers.facebook.com/docs/instagram-api/getting-started

instagram_basic
pages_show_list

I need permission to.

But for the same application, I also need to log in personal accounts. I am using firebase. Is there a way to get the above permissions?

**Comment by darwin-morocho** [comment]
@gulmensedat this code should work

```dart
final LoginResult result = await FacebookAuth.instance.login(
    permissions: ['public_profile', 'email', 'pages_show_list', 'instagram_basic'],
);
```

but remember to use these permissions`instagram_basic, pages_show_list` you must send your request in your facebook developer console

**Comment by darwin-morocho** [comment]
closed by inactivity

**Comment by juanagu** [comment]
Hi @darwin-morocho not sure if this is the correct issue for it. But would be possible to add support to https://developers.facebook.com/docs/instagram/business-login-for-instagram ? 

It would be great to have a FacebookAuth.instance.loginForInstagram function.

**Comment by darwin-morocho** [comment]
> Hi @darwin-morocho not sure if this is the correct issue for it. But would be possible to add support to https://developers.facebook.com/docs/instagram/business-login-for-instagram ?
> 
> It would be great to have a FacebookAuth.instance.loginForInstagram function. The main benefit of this new login is the UX on the Facebook SDK. ![Screen Shot 2022-12-29 at 09 36 38](https://user-images.githubusercontent.com/4689126/209953416-a436cc7e-7323-4436-b33b-c0df2987334a.png)

Hi the problem is that currently this plugin has support for android, ios, web and macOS. So to add this New feature Will be  very complicated to support all these Platforms due to in android and ios must be necessary create a custom webview or web can use a third package for that but is not  a good solution

**Comment by yoboitel** [comment]
Hello, any update on this ? 
I’m also using instagram business login flow manually but it doesnt complete. wanted to use your lib but just saw instagram business login is not possible with it, would it be possible to edit it myself to make it work ?
As we just need to add this when creating the login url : setup':{'channel':'IG_API_ONBOARDING'}}
