### ISSUE TITLE
Specs satisfying the `flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)` dependency were found

### ISSUE THREAD

**Issue by cnkygmr** [darwin-morocho/flutter-facebook-auth#230]
[flutter-facebook-auth] 4.2.1

It gives this error
Specs satisfying the `flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)` dependency were found

https://facebook.meedu.app/docs/4.x.x/ios

In your Podfile uncomment the next line (You need set the minimum target to 10.0 or higher)

but in podspec.json 

"platforms": {
    "ios": "11.0"
  },

What is the minimum target version ios?

**Comment by darwin-morocho** [comment]
@cnkygmr since the facebook ios sdk 13.x.x the minimum iOS version must be 11.0
