### ISSUE TITLE
How to check which page the user has given permission?

### ISSUE THREAD

**Issue by Jordan1122** [darwin-morocho/flutter-facebook-auth#231]
Is there a way to get the page id of the access token?

Thank you for your help!

**Comment by darwin-morocho** [comment]
> Is there a way to get the page id of the access token?
> 
> Thank you for your help!

I'm sorry but this question has nothing to do with the authentication process provided by this plugin.

https://stackoverflow.com/questions/7111562/facebook-graph-api-how-to-get-page-id-via-an-access-token

I'm closing this.
