### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by KallepalliTirumalesh** [darwin-morocho/flutter-facebook-auth#233]
Hi, I am facing this issue i have tried flutter clean and have done pub get to i have followed the documentation as it is but i am getting this below error.

Can you please guide me how can i resolve this error i am running on Android Platform.

Thanks

**Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)**

**Comment by darwin-morocho** [comment]
@KallepalliTirumalesh please follow the issue template and add all information requested

**Comment by maxlapides** [comment]
We are also experiencing this issue.

**Describe the bug**

This issue is occurring on Android when we invoke `FacebookAuth.instance.accessToken`:

```
I/flutter ( 1570): Caught error: MissingPluginException(No implementation found for method getAccessToken on channel app.meedu/flutter_facebook_auth)
I/flutter ( 1570): #0      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:175
I/flutter ( 1570): <asynchronous suspension>
I/flutter ( 1570): #1      FacebookAuthPlatformImplementation.accessToken
package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:93
```

**Environment**

```
❯ flutter doctor -v
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-US)
    • Flutter version 2.10.5 at /Users/maxlapides/fvm/versions/2.10.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (11 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/maxlapides/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • SM G975U (mobile)  • R58M3087BMY                          • android-arm64  • Android 10 (API 29)
    • iPhone 13 (mobile) • 8A362B17-9737-4B87-B0E4-77BF160D0A50 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

We are using `flutter_facebook_auth` version 4.3.0

**Comment by darwin-morocho** [comment]
@maxlapides that is a runtime error commonly when you have a wrong Android configuration. Please add your MainActivity  and your AndroidManifest  Also you can check the example folder and compare with your project

**Comment by maxlapides** [comment]
@darwin-morocho Strangely, my app runs fine on flutter_facebook_auth version 4.2.0 without any other changes. Unfortunately, I can't share our code since it is proprietary. Maybe there is some change we need to make in our app code to support version 4.3.0, but in that case I would argue that we should bump the version number of flutter_facebook_auth to 5.0.0 since this would be a breaking change.

**Comment by darwin-morocho** [comment]
since the Facebook sdk 13.2.0 the client token in your AndroidManifest is mandatory maybe here is the problem in your case https://github.com/facebook/facebook-android-sdk/compare/sdk-version-13.1.0...sdk-version-13.2.0

**Comment by maxlapides** [comment]
@darwin-morocho Ah yes, it was the missing client token in AndroidManifest for us. Thanks for your great advice!
