### ISSUE TITLE
Android Build failed with an exception.

### ISSUE THREAD

**Issue by ttpho** [darwin-morocho/flutter-facebook-auth#236]
**Describe the bug**
Build and run Android application with error 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkProdDebugAarMetadata'.
> Could not resolve all files for configuration ':app:prodDebugRuntimeClasspath'.
   > Could not resolve com.facebook.android:facebook-login:13.+.
     Required by:
         project :app > project :flutter_facebook_auth
      > Failed to list versions for com.facebook.android:facebook-login.
         > Unable to load Maven meta-data from https://google.bintray.com/exoplayer/com/facebook/android/facebook-login/maven-metadata.xml.
            > Could not get resource 'https://google.bintray.com/exoplayer/com/facebook/android/facebook-login/maven-metadata.xml'.
               > Could not GET 'https://google.bintray.com/exoplayer/com/facebook/android/facebook-login/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Environment**
Android gradle

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
`

**Comment by darwin-morocho** [comment]
@ttpho I've tried to reproduce de issue without successful. In the example folder I have run
```shell
flutter clean
flutter pub get
flutter build apk
```
and everything is ok

**Comment by ttpho** [comment]
> @ttpho I've tried to reproduce de issue without successful. In the example folder I have run
> 
> ```shell
> flutter clean
> flutter pub get
> flutter build apk
> ```
> 
> and everything is ok
> 
> maybe you have some missing repositories in your `android/build.gradle` or `android/app/build.gradle` please compare them with the example folder



@darwin-morocho Thank you for your answer. 🙇 

The `example\android` used Gradle version `4.2.0`.  Cloud you use the Gradle latest version?

https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth/example/android/build.gradle#L8

**Comment by darwin-morocho** [comment]
> > @ttpho I've tried to reproduce de issue without successful. In the example folder I have run
> > ```shell
> > flutter clean
> > flutter pub get
> > flutter build apk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and everything is ok
> > maybe you have some missing repositories in your `android/build.gradle` or `android/app/build.gradle` please compare them with the example folder
> 
> @darwin-morocho Thank you for your answer. 🙇
> 
> The `example\android` used Gradle version `4.2.0`. Cloud you use the Gradle latest version?
> 
> https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth/example/android/build.gradle#L8

com.android.tools.build:gradle:4.2.0 id not the same as gradle distribution.  You can use the lastest version if you want

**Comment by panchalAlpit** [comment]
@ttpho I'm getting same error, Have you got the solution?

**Comment by panchalAlpit** [comment]
@ttpho I'm getting same error, Have you got the solution?

**Comment by darwin-morocho** [comment]
@ttpho  @panchalAlpit  try to check that you don't have a jcenter reference in yours build.gradle 


Also you can try using an specific of the Facebook sdk in your android/app/build.gradle 
 
com.facebook.android:facebook-login:13.1.0  instead of 13.+

**Comment by ttpho** [comment]
@darwin-morocho Thank you for your answer, I changed `com.facebook.android:facebook-login:13.2.0` (lasted version), it is worked.

Can you update Facebook Lib from your repository?

**Comment by darwin-morocho** [comment]
@ttpho check the version 4.3.4

**Comment by DevMansoor** [comment]
I'm facing the same error but I can't find anywhere `com.facebook.android:facebook-login:13.2.0` in my file I only have `implementation 'com.facebook.android:facebook-android-sdk:latest.release'` in `app\build.gradle`.
