### ISSUE TITLE
LoginBehavior.webOnly not working on Android

### ISSUE THREAD

**Issue by y-rakityanskiy** [darwin-morocho/flutter-facebook-auth#237]
Hi,

Looks like `LoginBehavior.webOnly` is not woking anymore. Although [this option](https://github.com/darwin-morocho/flutter-facebook-auth/blob/4bf13cd4bcad4c5e7156b33ead546451a3406e5a/facebook_auth_platform_interface/lib/src/login_behavior.dart#L6) is present on the Flutter side, the corresponding case statement is just missing in the platform code here:

https://github.com/darwin-morocho/flutter-facebook-auth/blob/730ecca9794c010c96fc851b2c4739b8e3c5f564/facebook_auth/android/src/main/java/app/meedu/flutter_facebook_auth/FacebookAuth.java#L56-L75

Is there a reason for this?

Thanks!

**Comment by darwin-morocho** [comment]
> Hi,
> 
> Looks like `LoginBehavior.webOnly` is not woking anymore. Although [this option](https://github.com/darwin-morocho/flutter-facebook-auth/blob/4bf13cd4bcad4c5e7156b33ead546451a3406e5a/facebook_auth_platform_interface/lib/src/login_behavior.dart#L6) is present on the Flutter side, the corresponding case statement is just missing in the platform code here:
> 
> https://github.com/darwin-morocho/flutter-facebook-auth/blob/730ecca9794c010c96fc851b2c4739b8e3c5f564/facebook_auth/android/src/main/java/app/meedu/flutter_facebook_auth/FacebookAuth.java#L56-L75
> 
> Is there a reason for this?
> 
> Thanks!

that option was removed due to a breaking change in the facebook sdk because that option was deprecated

**Comment by y-rakityanskiy** [comment]
> that option was removed due to a breaking change in the facebook sdk because that option was deprecated. I will remove that option from dart side

Based on [this article](https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews), they deprecated only `WEB_VIEW_ONLY`, but not `WEB_ONLY`. These options are not the same. Also, `WEB_ONLY` is not marked as deprecated in the Facebook SDK code, unlike `WEB_VIEW_ONLY` (you can see this [here](https://github.com/facebook/facebook-android-sdk/blob/0b4ccd544689d55823100132c14395d694131cf1/facebook-common/src/main/java/com/facebook/login/LoginBehavior.kt#L40-L49)). 

@darwin-morocho It would be great if the `WEB_ONLY` option was available again in this plugin. Thanks!

**Comment by y-rakityanskiy** [comment]
Unfortunately, it still doesn't work because `case "WEB_ONLY"` is missing [here](https://github.com/darwin-morocho/flutter-facebook-auth/blob/7a180c7c500581c4c831de4725274f127e96da57/facebook_auth/android/src/main/java/app/meedu/flutter_facebook_auth/FacebookAuth.java#L58). When I call `FacebookAuth.instance.login` with `LoginBehavior.webOnly` on dart side, it eventually turns to `LoginBehavior.NATIVE_WITH_FALLBACK` on Android side. But I expect it to be `LoginBehavior.WEB_ONLY`

**Comment by darwin-morocho** [comment]
the code was added try to use `flutter clean`

**Comment by y-rakityanskiy** [comment]
Everything is fine now. Thank you so much for the quick fix 👍
