### ISSUE TITLE
MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by OttomanDeveloper** [darwin-morocho/flutter-facebook-auth#239]
**Describe the bug**

I followed every document which is available but still, I'm having this issue.
**MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)**

**Environment**
**Add your `flutter doctor -v`**
`
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.19044.1682], locale en-PK)
    • Flutter version 2.10.5 at C:\src\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at I:\AndroidStudio\SDK
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.13)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.32413.511
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] IntelliJ IDEA Community Edition (version 2022.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3
    • Flutter plugin version 67.0.4
    • Dart plugin version 221.5588

[√] VS Code (version 1.67.0)
    • VS Code at C:\Users\Ottoman Coder\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (4 available)
    • M2102J20SG (mobile) • 54b3ec51 • android-arm64  • Android 12 (API 31)
    • Windows (desktop)   • windows  • windows-x64    • Microsoft Windows [Version 10.0.19044.1682]
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 101.0.1210.32

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
`
**Add your `pubspec.yaml`**
`
name: neighbors
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_crashlytics: ^2.7.2
  firebase_storage: ^10.2.15
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^4.3.3
  flutter_svg: ^1.0.3
  get: ^4.6.1
  get_storage: ^2.0.3
  google_fonts: ^2.3.2
  intl: ^0.17.0
  twitter_login: ^4.2.3
  video_player: ^2.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true

flutter:
 
  uses-material-design: true

  assets:
    - assets/backgrounds/home/
    - assets/backgrounds/splash/
    - assets/icons/
    - assets/svg/login/
    - assets/videos/

`
**Add your `Info.plist`**

**Add your `AppDelegate.swift`**

**Add your `MainActivity`**
`
    package com.nebzy.neighbors

    import androidx.core.view.WindowCompat
    import io.flutter.embedding.android.FlutterActivity

    class MainActivity: FlutterActivity() {
    override fun onPostResume() {
        super.onPostResume()
        WindowCompat.setDecorFitsSystemWindows(window, false)
    }
    }
`

**Add your `AndroidManifest.xml`**

           <manifest xmlns:android="http://schemas.android.com/apk/res/android"
           package="com.nebzy.neighbors">

           <uses-permission android:name="android.permission.INTERNET"/>

          <application
           android:label="Nebzy 🏠"
           android:name="${applicationName}"
           android:icon="@mipmap/ic_launcher">
          <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
            <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                
                <data android:scheme="example"
                      android:host="gizmos" /> 
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
       </application>
         
        <queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
        </queries>
        <queries>
        <package android:name="com.facebook.katana" />
        </queries> 
       </manifest>

**Add your `/app/res/values/strings.xml`**

     <?xml version="1.0" encoding="utf-8"?>
      <resources>
      <string name="app_name">Nebzy 🏠</string>
      <string name="facebook_app_id">844493062908338</string>
      <string name="fb_login_protocol_scheme">fb844493062908338</string>
      <string name="facebook_client_token">0b4351cb0a4837210a620f215d7fc9d9</string>
      </resources>

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
@OttomanDeveloper the problem is your AndroidManifest. You have added the meta tags inside the main activity tag  but them must be in the application  tag.


https://facebook.meedu.app/docs/4.x.x/android
