### ISSUE TITLE
PlatformException(FAILED, Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference, null, null)

### ISSUE THREAD

**Issue by k1ycee** [darwin-morocho/flutter-facebook-auth#240]
I'm currently testing the app on android 12 and we keep getting the error 
PlatformException(FAILED, Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.toString()' on a null object reference, null, null)

`[✓] Flutter (Channel beta, 2.2.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.0 at /home/wildone/snap/flutter/common/flutter
    • Framework revision b22742018b (12 months ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /home/wildone/Android/Sdk
    • Platform android-Tiramisu, build-tools 31.0.0-rc4
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 64.0.2
    • Dart plugin version 211.7798
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] Android Studio (version 4.1)
    • Android Studio at /usr/local/android-studio-ide-201.7199119-linux/android-studio
    • Flutter plugin version 56.0.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /usr/local/idea-IU-211.7142.45
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (2 available)
    • CPH2015 (mobile) • 192.168.0.118:5555 • android-arm64  • Android 9 (API 28)
    • Chrome (web)     • chrome             • web-javascript • Google Chrome 100.0.4896.127

• No issues found!`

`package com.example.itojume

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
`

`<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.itojume">
	<application android:label="itojume" android:icon="@mipmap/ic_launcher">
		<activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
			
			<meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
			
			<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		
		<meta-data android:name="flutterEmbedding" android:value="2" />
		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />
		<meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token" />
		<activity android:name="com.facebook.FacebookActivity" android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation" android:label="@string/app_name" />
		<activity android:name="com.facebook.CustomTabActivity" android:exported="true">
			<intent-filter>
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="@string/fb_login_protocol_scheme" />
			</intent-filter>
		</activity>
	</application>
	<queries>
		<provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
	</queries>
</manifest>
`

`  Future facebookSignUp() async {
    try {
      final facebookLoginResult = await FacebookAuth.instance
          .login(permissions: ["public_profile", "email"]);
      final userData = await FacebookAuth.instance.getUserData();
      final facebookCredential = FacebookAuthProvider.credential(
          facebookLoginResult.accessToken!.token);
      // final info =
      await FirebaseAuth.instance.signInWithCredential(facebookCredential);
      final facebookUser = ItojuUser(
        email: userData["email"],
        name: userData['name'],
      );

      await UserDataBase().createUser(facebookUser);
      await FirebaseAuth.instance.currentUser!.sendEmailVerification();
      // return info.user!.uid;
    } on FirebaseAuthException catch (authError) {
      throw CustomAuthException(authError.code, authError.message!);
    } catch (e) {
      throw CustomException(errorMessage: "Unknown Error: $e");
    }
  }`

On an Android 9 you can successfully signup and Login but on the android 12 you can't you just get this error.

![IMG-20220509-WA0011](https://user-images.githubusercontent.com/49368362/167455119-94f5203a-4483-485c-8627-d65c238d8cd6.jpg)

**Comment by darwin-morocho** [comment]
@k1ycee you must call to `getUserData` only if the user is logged.

https://facebook.meedu.app/docs/4.x.x/user-information

**Comment by k1ycee** [comment]
Alright will do.
