### ISSUE TITLE
AAPT: error: resource style/com_facebook_button

### ISSUE THREAD

**Issue by qq1057119720** [darwin-morocho/flutter-facebook-auth#244]
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     AAPT: error: resource style/com_facebook_button (aka com.easygolf.app:style/com_facebook_button) not found.
     error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 42s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by darwin-morocho** [comment]
@qq1057119720 have you tried `flutter clean`
