### ISSUE TITLE
i get bug when login 

### ISSUE THREAD

**Issue by abd1997-coder** [darwin-morocho/flutter-facebook-auth#245]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)
E/flutter (30006): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (30006): <asynchronous suspension>
E/flutter (30006): #1      FacebookAuthPlatformImplementation.login (package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:34:22)

**Comment by darwin-morocho** [comment]
before open an issue please follow the issue template.
