### ISSUE TITLE
after i update flutter to 3.0.0 

### ISSUE THREAD

**Issue by abd1997-coder** [darwin-morocho/flutter-facebook-auth#246]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)
E/flutter (12532): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (12532): <asynchronous suspension>
E/flutter (12532): #1      FacebookAuthPlatformImplementation.login (package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:34:22)

**Comment by darwin-morocho** [comment]
please follow the issue template.

Add additional info about the error is on Android or iOS. 

if the error persists after run `flutter clean`

**Comment by abd1997-coder** [comment]
my app was worked fine until updated the library to the latest version

**Comment by abd1997-coder** [comment]
gradle :
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip
classpath 'com.android.tools.build:gradle:4.0.1'

this gradel i used it.

**Comment by darwin-morocho** [comment]
which version are you using? 

 Also please follow the issue template, if you don't do it I will close any issue about this

**Comment by abd1997-coder** [comment]
i use the 4.3.4 version 
 what template do you need to use it ??

**Comment by darwin-morocho** [comment]
when you open an issue you have the all info required to allow me check the issue.

Also always try with flutter clean

**Comment by abd1997-coder** [comment]
I found a solution, this library forces me to use a java file instead of kotlin file please fix this issue
