### ISSUE TITLE
iOS problem

### ISSUE THREAD

**Issue by EDApps3** [darwin-morocho/flutter-facebook-auth#247]
Building in iOS throw error in Xcode 'facebook_auth-Swift.h' file not found using flutter_facebook_auth: ^5.0.0-dev.1 while switching back to flutter_facebook_auth: ^4.3.4 solve the problem

**Comment by darwin-morocho** [comment]
> Building in iOS throw error in Xcode 'facebook_auth-Swift.h' file not found using flutter_facebook_auth: ^5.0.0-dev.1 while switching back to flutter_facebook_auth: ^4.3.4 solve the problem

to use `5.0.0-dev.1` you need to follow the migration guide to delete the previous references to flutter_facebook_auth: ^4.3.4 

https://facebook.meedu.app/docs/4.x.x/migration-guide

**Comment by darwin-morocho** [comment]
> did the steps and even deleted the pod file.lock and still the same error
> 
> Could not build the precompiled application for the device. Lexical or Preprocessor Issue (Xcode): 'facebook_auth-Swift.h' file not found /Users/admin/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:7:8

check https://github.com/darwin-morocho/flutter-facebook-auth/issues/234#issuecomment-1120499571
https://github.com/darwin-morocho/flutter-facebook-auth/issues/4

**Comment by adar2378** [comment]
These are the steps I followed,
- removed old flutter-facebook-auth dependency
- ran `flutter clean` &  `pod install` 
- then added `^5.0.0-dev.1` version and ran `flutter pub get`
- reinstalled cocoapods, ran `pod deintegrate` & `pod install`
- added `target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end`
    
Still getting this error on iOS for `5.0.0-dev.1` Works perfectly on version `^4.3.4+2`
`Lexical or Preprocessor Issue (Xcode): 'facebook_auth-Swift.h' file not found
/Users/adar/Development/flutter_1.17/flutter_17/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5
.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:7:8`
