### ISSUE TITLE
web/flutter_facebook_auth.js missing

### ISSUE THREAD

**Issue by mannnish** [darwin-morocho/flutter-facebook-auth#249]
i am using version 2.x.x of the package and i cannot find `flutter-facebook-auth/master/facebook_auth/example/web/flutter_facebook_auth.js` this file

**Comment by darwin-morocho** [comment]
> i am using version 2.x.x of the package and i cannot find `flutter-facebook-auth/master/facebook_auth/example/web/flutter_facebook_auth.js` this file

that version is obsolete and that file is not more available on the master branch.

that file could be found here https://github.com/darwin-morocho/flutter-facebook-auth/blob/3.0.0/facebook_auth/example/web/flutter_facebook_auth.js
