### ISSUE TITLE
MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by kldawad** [darwin-morocho/flutter-facebook-auth#252]
i keep getting this error, i've checked multiple times and nothing is missing 

* i've did flutter clean, and re-run the project

is there a fix for this ?

**Comment by darwin-morocho** [comment]
> i keep getting this error, i've checked multiple times and nothing is missing
> 
> * i've did flutter clean, and re-run the project
> 
> is there a fix for this ?

Please follow the issue template

**Comment by SalsabeelaHasan** [comment]
@darwin-morocho @kldawad 
see here : 
https://github.com/darwin-morocho/flutter-facebook-auth/issues/253

**Comment by darwin-morocho** [comment]
@kldawad please open a new issue following the issue form that I have added
