### ISSUE TITLE
MissingPluginException- No implementation found for method login on channel app.meedu/flutter_facebook_auth

### ISSUE THREAD

**Issue by SalsabeelaHasan** [darwin-morocho/flutter-facebook-auth#253]
**Describe the bug**
the code I wrote to implement the latest version (4.3.4) of the Facebook auth plugin in **Android** device is attached, it always goes to the "catch error section" and the error is:
> I/flutter (10220): :: catch error :: MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth).

  I can't understand the.. what the problem is and what should I do?

**Environment**

Add your `flutter doctor -v`

>  [✓] Flutter (Channel stable, 2.5.3, on macOS 12.2.1 21D62 darwin-x64,)
>     • Flutter version 2.5.3 at /Applications/SDKs/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 18116933e7 (8 months ago), 2021-10-15 10:46:35 -0700
>     • Dart version 2.14.4
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
>     ✗ cmdline-tools component is missing
>       Run `path/to/sdkmanager --install "cmdline-tools;latest"`
>       See https://developer.android.com/studio/command-line for more details.
>     ✗ Android license status unknown.
>       Run `flutter doctor --android-licenses` to accept the SDK licenses.
>       See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 13.2.1, Build version 13C100
>     • CocoaPods version 1.11.3
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2021.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

Add your `pubspec.yaml` 
>  flutter_facebook_auth: 4.3.4

Add your `AndroidManifest.xml`
>   meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />

Add your `/app/res/values/strings.xml`

>  string name="facebook_app_id">**********</string>
> string name="fb_login_protocol_scheme">fb**********</string>

**To Reproduce**
```
 try {
      FacebookAuth _instance = FacebookAuth.instance;
      if (Platform.isAndroid) {
        result = await _instance.login(
          loginBehavior: LoginBehavior.dialogOnly,
          permissions: ['email', 'public_profile'],
        ).catchError((error){
          print(":: catchError :: ${error}");
        });
      }
```

**Expected behaviour**
enter the Facebook UI interface to complete the login process.

**Screenshots**
there is nothing to provide.

**Comment by darwin-morocho** [comment]
@SalsabeelaHasan please follow the issue template. If you don't do it I will close this

**Comment by SalsabeelaHasan** [comment]
@darwin-morocho done, see now!

**Comment by darwin-morocho** [comment]
> android:name="com.facebook.sdk.ApplicationId"

@SalsabeelaHasan your AndroidManifest is incomplete

**Comment by SalsabeelaHasan** [comment]
@darwin-morocho these are the facebook values in AndroidManifest.xml , 
I used it previously in the old version and everything runs fine, what is the missing part? 
`   <meta-data
            android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id" />`

**Comment by darwin-morocho** [comment]
> @darwin-morocho these are the facebook values in AndroidManifest.xml , I used it previously in the old version and everything runs fine, what is the missing part? ` <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id" />`

@SalsabeelaHasan  I will  close this because you don't provide me the enough info

**Comment by SalsabeelaHasan** [comment]
@darwin-morocho 
Wow!
This is so terrible, u don't help me by doing that! 
Please explain what u mean and what u want or answer my questions, this is unacceptable!

In previous comment I mentioned what I have and all is good, but In latest version is not.

**Comment by darwin-morocho** [comment]
> @darwin-morocho Wow! This is so terrible, u don't help me by doing that! Please explain what u mean and what u want or answer my questions, this is unacceptable!
> 
> In previous comment I mentioned what I have and all is good, but In latest version is not.

@SalsabeelaHasan  all info provided by you is incomplete. Example your pubspec.yaml, MainActivity and AndroidManifest are incomplete,

**Comment by SalsabeelaHasan** [comment]
@darwin-morocho, thanks for your effort, but you have to be patient before closing issues, to help us know what is required.. anyway, the information has been modified and now it is complete as you explained the last thing.

**Comment by darwin-morocho** [comment]
@SalsabeelaHasan your android manifest is wrong. 

check https://facebook.meedu.app/docs/4.x.x/android
