### ISSUE TITLE
ios device log failed

### ISSUE THREAD

**Issue by fangxuan0** [darwin-morocho/flutter-facebook-auth#256]
### What version are you using?

flutter_facebook_auth:4.0.1

### What OS and version are you using to local deploy your application?

macOS 12.4

### What platforms are you seeing the problem on?

iOS

### Describe the Bug

On ios devices, after logging in to facebook with the Safari browser, log in with facebook authorization, and then log out. The facebook app logs in to a new account, and the login with facebook authorization will fail again.

### Expected Behavior

Use facebook authorization to log in, then log out of our app, then log out of the facebook account from the facebook official website of the Safari browser, log in to the new facebook account in the facebook app, and then use our own app to authorize the login with facebook, and the prompt fails.

### To Reproduce

no

### flutter doctor -v

```shell
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (3 months ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by darwin-morocho** [comment]
for mobile apps the Facebook sdk doesn't support switch accounts. 

https://github.com/facebook/facebook-ios-sdk/issues/1147

**Comment by neobie** [comment]
> for mobile apps the Facebook sdk doesn't support switch accounts.
> 
> [facebook/facebook-ios-sdk#1147](https://github.com/facebook/facebook-ios-sdk/issues/1147)

Terrible design.
