### ISSUE TITLE
How to exchange use the Facebook access token to authenticate with AWS Cognito User Pool

### ISSUE THREAD

**Issue by juskek** [darwin-morocho/flutter-facebook-auth#267]
### What version are you using?

4.4.0+1

### What OS and version are you using to local deploy your application?

iOS 15.5

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
NA
```

### Describe the Bug

I am receiving a LoginStatus.success response, and the following AccessToken:

```{userId: XXX, token: XXX, expires: XXX, lastRefresh: XXX, applicationId: XXX, graphDomain: XXX, isExpired: XXX, grantedPermissions: [public_profile, openid, email], declinedPermissions: []}```

I had a couple of questions about the flow of this package, as I am trying to integrate it with an AWS Cognito User Pool, where I have been using an OAuth authorization grant flow for social sign in.

1. Which type of [token](https://developers.facebook.com/docs/facebook-login/guides/access-tokens) is the "token" field in Access Token? 
2. Is there any way I can get an authorization code from this package?

### Expected Behavior

NA

### To Reproduce

NA

### Relevant log output

```shell
NA
```

### flutter doctor -v

```shell
NA
```

**Comment by darwin-morocho** [comment]
Just go to the AccessToken class and check the field definition. token is a String

**Comment by juskek** [comment]
Hi Darwin, apologies for not being clear. 

What I meant was what type of Facebook token was it, not the Dart variable type. 

I attached a hyper link to my previous post under token, which links to the various types of Facebook tokens

**Comment by juskek** [comment]
2. Also, would you happen to know if the OAuth authorisation grant flow is available with this package?

**Comment by darwin-morocho** [comment]
this plugin allows you to get an user access token

**Comment by jaysonsaavedra** [comment]
bump
