### ISSUE TITLE
Facebook login doesn't work on Android

### ISSUE THREAD

**Issue by amani27** [darwin-morocho/flutter-facebook-auth#279]
### What version are you using?

flutter_facebook_auth:4.3.4+2

### What OS and version are you using to local deploy your application?

macOS 11.4

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
flutter_facebook_auth:4.3.4+2
```

### Describe the Bug

Facebook login with the plugin. flutter_facebook_auth works nicely on iOS, also shows mobile app ownership confirmed. 
But in Android devices shows - `Login Error: There is an error in logging you into this application. Please try again later. `
My App is Live in Facebook developer console, I've added all required terms, privacy policies URL and key hashes. But for Android ownership verification fails. It shows message on Facebook Developers Console that` Error found while validating app-ads.txt. PACKAGE NAME: We couldn't find your developer website URL in your app's store listing`, but I've followed the steps, and added app-ads.txt file on my websites's root, also added my site URL on Google Play Store Listing - Contact Details. 
Has anyone else also face such issue? What could be possible reasons for this issue? Does the app need to be published on Google Play Store, or should I wait for 7days since adding the developer website to the play store listing?

### Expected Behavior

Expected to login like on iOS.

### To Reproduce

```    await FacebookAuth.instance.logOut(); // disconnect user
    final LoginResult result = await FacebookAuth.instance.login();```
I used this code to login with Facebook.

### Relevant log output

_No response_

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.0.4, on macOS 11.4 20F71 darwin-arm, locale
    en-GB)
    • Flutter version 3.0.4 at /Users/appifylab/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 85684f9300 (8 weeks ago), 2022-06-30 13:22:47 -0700
    • Engine revision 6ba2af10bb
    • Dart version 2.17.5
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version
    33.0.0-rc1)
    • Android SDK at /Users/appifylab/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc1
    • Java binary at: /Users/appifylab/Downloads/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/appifylab/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.61.0)
    • VS Code at /Users/appifylab/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
      (API 31) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.4
      20F71 darwin-arm
    • Chrome (web)                • chrome        • web-javascript • Google
      Chrome 104.0.5112.101

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by etienneyoufeel** [comment]
Got the same problem on `flutter_facebook_auth: ^4.4.1`, android 13 API 33

**Comment by darwin-morocho** [comment]
This is not an issue of this plugin. Please check the closed issues and also this issue must be here https://github.com/facebook/facebook-android-sdk

**Comment by darwin-morocho** [comment]
> ### What version are you using?
> flutter_facebook_auth:4.3.4+2
> 
> ### What OS and version are you using to local deploy your application?
> macOS 11.4
> 
> ### What platforms are you seeing the problem on?
> Android
> 
> ### pubspec.yaml
> ```yaml
> flutter_facebook_auth:4.3.4+2
> ```
> 
> ### Describe the Bug
> Facebook login with the plugin. flutter_facebook_auth works nicely on iOS, also shows mobile app ownership confirmed. But in Android devices shows - `Login Error: There is an error in logging you into this application. Please try again later. ` My App is Live in Facebook developer console, I've added all required terms, privacy policies URL and key hashes. But for Android ownership verification fails. It shows message on Facebook Developers Console that` Error found while validating app-ads.txt. PACKAGE NAME: We couldn't find your developer website URL in your app's store listing`, but I've followed the steps, and added app-ads.txt file on my websites's root, also added my site URL on Google Play Store Listing - Contact Details. Has anyone else also face such issue? What could be possible reasons for this issue? Does the app need to be published on Google Play Store, or should I wait for 7days since adding the developer website to the play store listing?
> 
> ### Expected Behavior
> Expected to login like on iOS.
> 
> ### To Reproduce
> ```
>     final LoginResult result = await FacebookAuth.instance.login();```
> I used this code to login with Facebook.
> 
> ### Relevant log output
> 
> _No response_
> 
> ### flutter doctor -v
> 
> ```shell
> [✓] Flutter (Channel stable, 3.0.4, on macOS 11.4 20F71 darwin-arm, locale
>     en-GB)
>     • Flutter version 3.0.4 at /Users/appifylab/development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 85684f9300 (8 weeks ago), 2022-06-30 13:22:47 -0700
>     • Engine revision 6ba2af10bb
>     • Dart version 2.17.5
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version
>     33.0.0-rc1)
>     • Android SDK at /Users/appifylab/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.0-rc1
>     • Java binary at: /Users/appifylab/Downloads/Android
>       Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Users/appifylab/Downloads/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.61.0)
>     • VS Code at /Users/appifylab/Downloads/Visual Studio Code.app/Contents
>     • Flutter extension version 3.29.0
> 
> [✓] Connected device (3 available)
>     • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
>       (API 31) (emulator)
>     • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.4
>       20F71 darwin-arm
>     • Chrome (web)                • chrome        • web-javascript • Google
>       Chrome 104.0.5112.101
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> ```
> 
> ### Info.plist (iOS)
> _No response_
> 
> ### Podfile (iOS)
> _No response_
> 
> ### AndroidManifest.xml
> _No response_
> 
> ### MainActivity.java
> _No response_
> 
> ### MainActivity.kt
> _No response_
> 
> ### index.html
> _No response_
> 
> ### Info.plist (macOS)
> _No response_

Please fill the all Android requirements

**Comment by saypadith** [comment]
Got the same problem on `flutter_facebook_auth: ^4.4.1`

**Comment by saypadith** [comment]
> ### What version are you using?
> flutter_facebook_auth:4.3.4+2
> 
> ### What OS and version are you using to local deploy your application?
> macOS 11.4
> 
> ### What platforms are you seeing the problem on?
> Android
> 
> ### pubspec.yaml
> ```yaml
> flutter_facebook_auth:4.3.4+2
> ```
> 
> ### Describe the Bug
> Facebook login with the plugin. flutter_facebook_auth works nicely on iOS, also shows mobile app ownership confirmed. But in Android devices shows - `Login Error: There is an error in logging you into this application. Please try again later. ` My App is Live in Facebook developer console, I've added all required terms, privacy policies URL and key hashes. But for Android ownership verification fails. It shows message on Facebook Developers Console that` Error found while validating app-ads.txt. PACKAGE NAME: We couldn't find your developer website URL in your app's store listing`, but I've followed the steps, and added app-ads.txt file on my websites's root, also added my site URL on Google Play Store Listing - Contact Details. Has anyone else also face such issue? What could be possible reasons for this issue? Does the app need to be published on Google Play Store, or should I wait for 7days since adding the developer website to the play store listing?
> 
> ### Expected Behavior
> Expected to login like on iOS.
> 
> ### To Reproduce
> ```
>     final LoginResult result = await FacebookAuth.instance.login();```
> I used this code to login with Facebook.
> 
> ### Relevant log output
> 
> _No response_
> 
> ### flutter doctor -v
> 
> ```shell
> [✓] Flutter (Channel stable, 3.0.4, on macOS 11.4 20F71 darwin-arm, locale
>     en-GB)
>     • Flutter version 3.0.4 at /Users/appifylab/development/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 85684f9300 (8 weeks ago), 2022-06-30 13:22:47 -0700
>     • Engine revision 6ba2af10bb
>     • Dart version 2.17.5
>     • DevTools version 2.12.2
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version
>     33.0.0-rc1)
>     • Android SDK at /Users/appifylab/Library/Android/sdk
>     • Platform android-33, build-tools 33.0.0-rc1
>     • Java binary at: /Users/appifylab/Downloads/Android
>       Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Users/appifylab/Downloads/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
> 
> [✓] VS Code (version 1.61.0)
>     • VS Code at /Users/appifylab/Downloads/Visual Studio Code.app/Contents
>     • Flutter extension version 3.29.0
> 
> [✓] Connected device (3 available)
>     • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64  • Android 12
>       (API 31) (emulator)
>     • macOS (desktop)             • macos         • darwin-arm64   • macOS 11.4
>       20F71 darwin-arm
>     • Chrome (web)                • chrome        • web-javascript • Google
>       Chrome 104.0.5112.101
> 
> [✓] HTTP Host Availability
>     • All required HTTP hosts are available
> 
> • No issues found!
> ```
> 
> ### Info.plist (iOS)
> _No response_
> 
> ### Podfile (iOS)
> _No response_
> 
> ### AndroidManifest.xml
> _No response_
> 
> ### MainActivity.java
> _No response_
> 
> ### MainActivity.kt
> _No response_
> 
> ### index.html
> _No response_
> 
> ### Info.plist (macOS)
> _No response_

I solved the problem by adding `<meta-data 
           android:name="com.facebook.sdk.ClientToken" 
           android:value="@string/facebook_client_token"/>
` and `<queries>
        <provider android:authorities="com.facebook.katana.provider.PlatformProvider" />
    </queries>`
 to AndroidManifest

**Comment by 2shrestha22** [comment]
Use latest facebook login sdk and here is how - https://github.com/darwin-morocho/flutter-facebook-auth/issues/284#issuecomment-1243147580

**Comment by darwin-morocho** [comment]
@closed due to no response from author
