### ISSUE TITLE
App crashes on start on Android (iOS filne)

### ISSUE THREAD

**Issue by AlexBacich** [darwin-morocho/flutter-facebook-auth#3]
After installing plugin Android crashes on start. Can't even do a thing.

**Comment by darwin-morocho** [comment]
Please check your android configuration https://pub.dev/packages/flutter_facebook_auth#install-on-android.

If you can provide us your android configuration to detect the posible error

**Comment by AlexBacich** [comment]
You are right. Thank you. Once added it started working. Thanks again.
