### ISSUE TITLE
iOS 16 App not launching when using version 5 of the package. Android works

### ISSUE THREAD

**Issue by mashegoindustries** [darwin-morocho/flutter-facebook-auth#300]
Version 4 working without issues

dyld[10178]: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <421700C1-D9B8-3DC8-80AE-5E896A43F549> /Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Runner
  Reason: tried: '/Users/apps_by_koketso/Library/Developer/Xcode/DerivedData/Runner-gwverkqqismtghfiorcolgakhntk/Build/Products/Debug-iphonesimulator/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2)
Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <421700C1-D9B8-3DC8-80AE-5E896A43F549> /Users/apps_by_koketso/Library/Developer/CoreSimulator/Devices/955346C0-9960-4AF6-BE99-E2EF80B4E4D2/data/Containers/Bundle/Application/5BD2DD9C-CECE-4670-893E-086BD1BD336A/Runner.app/Runner
  Reason: tried: '/Users/apps_by_koketso/Library/Developer/Xcode/DerivedData/Runner-gwverkqqismtghfiorcolgakhntk/Build/Products/Debug-iphonesimulator/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, not in dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framew
dyld config: DYLD_SHARED_CACHE_DIR=/Users/apps_by_koketso/Library/Developer/CoreSimulator/Caches/dyld/21G72/com.apple.CoreSimulator.SimRuntime.iOS-16-0.20A360 DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot DYLD_LIBRARY_PATH=/Users/apps_by_koketso/Library/Developer/Xcode/DerivedData/Runner-gwverkqqismtghfiorcolgakhntk/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libMainThreadChecker.dylib:/usr/lib/libRPAC.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib DYLD_FRAMEWORK_PATH=/Users/apps_by_koketso/Library/Developer/Xcode/DerivedData/Runner-gwverkqqismtghfiorcolgakhntk/Build/Products/Debug-iphonesimulator DYLD_FALLBACK_FRAMEWORK_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks DYLD_FALLBACK_LIBRARY_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib
(lldb)

**Comment by darwin-morocho** [comment]
@mashegoindustries after upgrade to 5.x.x you must delete your Pods folder next run 
```
cd ios
pod update flutter_facebook_auth
```


Also you add manually add FBSDKCoreKit  in your pod file
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FBSDKCoreKit' , '15.0.0' ## <----- like this
end
```

**Comment by mashegoindustries** [comment]
@darwin-morocho I just tried that still no good

I did the below
- updated to version 5
- flutter clean
- pub upgrade
- Deleted Pods folder
- Deleted Podfile.lock
- ran pod install, pod update,pod install --repo-update [non of these made a difference]
- pod update flutter_facebook_auth

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FBSDKCoreKit' , '15.0.0' ## <----- like this
end


Still it doesnt work

**Comment by mashegoindustries** [comment]
The moment I switch back to version 4 (deleting pods folder, etc)

Everything just work

**Comment by Tom3652** [comment]
I have updated my pods and when i try to build my iOS app is see the following using `flutter_facebook_auth: ^5.0.1` : 

```
(lldb) dyld[1852]: Symbol not found: _FBLinkable_NSNotificationCenter_NotificationDelivering
  Referenced from: <66419806-6AD3-3599-A5AF-DC1D8A94E700> /private/var/containers/Bundle/Application/9A86F6EF-C7AC-4A7C-A27A-79CA2E0F5C99/Runner.app/Frameworks/FBAEMKit.framework/FBAEMKit
  Expected in:     <2C1FABE1-6807-396C-9F57-A6F7E0C503AE> /private/var/containers/Bundle/Application/9A86F6EF-C7AC-4A7C-A27A-79CA2E0F5C99/Runner.app/Frameworks/FBSDKCoreKit_Basics.framework/FBSDKCoreKit_Basics
* thread #1, stop reason = signal SIGABRT
    frame #0: 0x00000001e2f74ce0 dyld`__abort_with_payload + 8
dyld`:
->  0x1e2f74ce0 <+8>:  b.lo   0x1e2f74cfc               ; <+36>
    0x1e2f74ce4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1e2f74ce8 <+16>: mov    x29, sp
    0x1e2f74cec <+20>: bl     0x1e2f18de4               ; cerror_nocancel
```

**Comment by migdev-br** [comment]
>  I had to switch back to version 4 as well

**Comment by darwin-morocho** [comment]
@Tom3652 @mashegoindustries check ios documentation facebook.meedu.app  and  don't forget to set your Facebook client token

**Comment by Tom3652** [comment]
Thanks for your reply @darwin-morocho , however i have already read the documentation and done all the steps. It works perfectly fine using `4.x.x` version so i know my setup is correct and i have not seen any difference for the setup between the `5.0.1` and the `4.x.x`. 

Please correct me if i am wrong of course

**Comment by darwin-morocho** [comment]
> Thanks for your reply @darwin-morocho , however i have already read the documentation and done all the steps. It works perfectly fine using `4.x.x` version so i know my setup is correct and i have not seen any difference for the setup between the `5.0.1` and the `4.x.x`.
> 
> Please correct me if i am wrong of course
> 
> I have these two lines difference in the `Info.plist` that are not in the documentation anymore apparently :
> 
> ```
> <string>fbauth2</string>
> <string>fbshareextension</string>
> ```
> 
> But removing thoses didn't prevent the crash

please run `flutter doctor -v`  and add the logs here

**Comment by Tom3652** [comment]
```
[✓] Flutter (Channel stable, 3.3.6, on macOS 13.0 22A380 darwin-x64, locale fr-FR)
    • Flutter version 3.3.6 on channel stable at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6928314d50 (7 days ago), 2022-10-25 16:34:41 -0400
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.72.2)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.46.0

[✓] Connected device (3 available)
    • Tommy’s iPhone (mobile) • 700c28e00d8978a132f439820a90d99c6327a990 • ios            • iOS 16.1 20B82
    • macOS (desktop)         • macos                                    • darwin-x64     • macOS 13.0 22A380 darwin-x64
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 107.0.5304.87

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by darwin-morocho** [comment]
@Tom3652 sorry but I couldn't reproduce the error. Please check this example https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/examples/with_provider and replace with your credentials and let me know if the error persists.

Al please open a new issue with all info requested in the issue template because this issue is not related with your error

**Comment by darwin-morocho** [comment]
@mashegoindustries please follow the issue template and add all info requested

**Comment by mtallenca** [comment]
I had 3 macs with XCode 14.1 - all would build / install ipa, 2 of the builds would produce the FBSDKCoreKit error. Running xcode-select --install fixed those 2.

**Comment by stenlee** [comment]
I can confirm this issue persists. I think it has something to do with Apple Silicon chips
Version 4.x is working fine.
Version 5.x is crashing just after app start.

exception in runner:
```
Warning: Error creating LLDB target at path '/Users/stenlee/Library/Developer/Xcode/DerivedData/Runner-eypgetmmsmqegsbiiteplbvzzspn/Build/Products/Debug-iphonesimulator/Runner.app'- using an empty LLDB target which can cause slow memory reads from remote devices: the specified architecture 'arm64-*-*' is not compatible with 'x86_64-apple-ios14.0.0-simulator' in '/Users/stenlee/Library/Developer/Xcode/DerivedData/Runner-eypgetmmsmqegsbiiteplbvzzspn/Build/Products/Debug-iphonesimulator/Runner.app/Runner'
dyld[85090]: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <498866CA-7B07-3FB3-AD52-8EE913A19AFE> /Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Runner
  Reason: tried: '/Users/stenlee/Library/Developer/Xcode/DerivedData/Runner-eypgetmmsmqegsbiiteplbvzzspn/Build/Products/Debug-iphonesimulator/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, no dyld cache), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/usr/lib/swift/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2, no dyld cache), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Users/stenlee/Library/Developer/CoreSimulator/Devices/1DA06744-3A2D-4C54-A7D7-E0751D2DAF47/data/Containers/Bundle/Application/170CBF9B-546C-45DF-BF55-8EC487250144/Runner.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit' (errno=2)
Message from debugger: Terminated due to signal 6

```

Flutter doctor output
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0.1 22A400 darwin-arm, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2.2)
[✓] VS Code (version 1.74.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by vixez** [comment]
Looks like this is a temporary workaround: https://github.com/facebook/facebook-ios-sdk/issues/2121#issuecomment-1346174464
