### ISSUE TITLE
I can't make ipa

### ISSUE THREAD

**Issue by osamamohammed98** [darwin-morocho/flutter-facebook-auth#307]
### What version are you using?

flutter_facebook_auth: 5.0.3

### What OS and version are you using to local deploy your application?

macOS m1 

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
sdk: '>=2.13.0 <3.0.0'
flutter_facebook_auth: 5.0.3
```

### Describe the Bug

I can't export the ios version to the apple store
flutter clean && flutter pub get && cd ios && pod update && flutter build ipa --no-sound-null-safety

### Expected Behavior

I can't export the ios version to the apple store
flutter clean && flutter pub get && cd ios && pod update && flutter build ipa --no-sound-null-safety

### To Reproduce

flutter clean && flutter pub get && cd ios && pod update && flutter build ipa --no-sound-null-safety

### Relevant log output

```shell
'/Users/osama/Library/Developer/Xcode/DerivedData/Runner-gzmcgtntofbubkcdyaloulhirbab/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/
    XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/FBSDKCoreKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE),
    obtain an updated library from the vendor, or disable bitcode for this target. file
    '/Users/osama/Library/Developer/Xcode/DerivedData/Runner-gzmcgtntofbubkcdyaloulhirbab/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/
    XCFrameworkIntermediates/FBSDKCoreKit/FBSDKCoreKit.framework/FBSDKCoreKit' for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/c1/n793nbbs7ss_83h2kfzccw300000gn/T/flutter_tools.MpnaIv/flutter_ios_build_temp_dirWyINbq/temporary_xcresult_bundle
```

### flutter doctor -v

```shell
osama@Osamas-MacBook-Pro homekitchens % flutter doctor -v
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.3.1 21E258 darwin-arm, locale en-PS)
    • Flutter version 3.3.7 on channel stable at /Users/osama/flutter_sdk/flutter_two_three_upgrade
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (7 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/osama/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13E113
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
```

**Comment by osamamohammed98** [comment]
Running pod install...                                              7.0s
Running Xcode build...                                                  
Xcode archive done.                                         25.3s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[44048]: Class AppleTypeCRetimerRestoreInfoHelper is implemented in both /usr/lib/libauthinstall.dylib (0x1e0889eb0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd44f8). One of the two will be used. Which one is undefined.
    objc[44048]: Class AppleTypeCRetimerFirmwareAggregateRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e0889f00) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd4548). One of the two will be used. Which one is undefined.
    objc[44048]: Class AppleTypeCRetimerFirmwareRequestCreator is implemented in both /usr/lib/libauthinstall.dylib (0x1e0889f50) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd4598). One of the two will be used. Which one is undefined.
    objc[44048]: Class ATCRTRestoreInfoFTABFile is implemented in both /usr/lib/libauthinstall.dylib (0x1e0889fa0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd45e8). One of the two will be used. Which one is undefined.
    objc[44048]: Class AppleTypeCRetimerFirmwareCopier is implemented in both /usr/lib/libauthinstall.dylib (0x1e0889ff0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd4638). One of the two will be used. Which one is undefined.
    objc[44048]: Class ATCRTRestoreInfoFTABSubfile is implemented in both /usr/lib/libauthinstall.dylib (0x1e088a040) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105bd4688). One of the two will be used. Which one is undefined.
    2022-11-08 18:07:51.007 xcodebuild[44048:148510] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension
    Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    2022-11-08 18:07:51.007 xcodebuild[44048:148510] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension
    Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
    ** ARCHIVE FAILED **

**Comment by darwin-morocho** [comment]
@osamamohammed98  could you try to use xcode to generate the ipa file?

**Comment by darwin-morocho** [comment]
@try upgrading to xcode 14.x

**Comment by osamamohammed98** [comment]
> @Try upgrading to xcode 14.x
> 
> next run `flutter clean` before building

Ok I'll do it

**Comment by bansalgaurav852** [comment]
[same issue ](ld: '/Users/dr.mac/Library/Developer/Xcode/DerivedData/Runner-hfrxcrjnqofvrccfytccoeddkrjm/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBSDKLoginKit/FBSDKLoginKit.framework/FBSDKLoginKit' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/dr.mac/Library/Developer/Xcode/DerivedData/Runner-hfrxcrjnqofvrccfytccoeddkrjm/Build/Products/Debug-iphoneos/XCFrameworkIntermediates/FBSDKLoginKit/FBSDKLoginKit.framework/FBSDKLoginKit' for architecture arm64)

**Comment by osamamohammed98** [comment]
Thanks, after I updated the xcode and the system, the problem was solved

**Comment by osamamohammed98** [comment]
> bansalgaurav852

@bansalgaurav852  try this

**Comment by dovydaskaupas** [comment]
After updating MacOS and Xcode I am getting the following when trying to build the IPA:

Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: <DBF06067-1E50-3767-AC62-A1464E0F00B7> /Users/dovydaskaupas/Library/Developer/CoreSimulator/Devices/A025ECAC-9214-4391-8339-6AC7E8264197/data/Containers/Bundle/Application/704A362F-5AF1-410A-B5B6-4BBDF713A070/Runner.app/Runner
  
 Plugin version: 5.0.6, that's after flutter clean, installing and updating pods.

**Comment by darwin-morocho** [comment]
> After updating MacOS and Xcode I am getting the following when trying to build the IPA:
> 
> Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit Referenced from: /Users/dovydaskaupas/Library/Developer/CoreSimulator/Devices/A025ECAC-9214-4391-8339-6AC7E8264197/data/Containers/Bundle/Application/704A362F-5AF1-410A-B5B6-4BBDF713A070/Runner.app/Runner
> 
> Plugin version: 5.0.6, that's after flutter clean, installing and updating pods.

It seems a issue of the native sdk check https://github.com/darwin-morocho/flutter-facebook-auth/issues/302

**Comment by bansalgaurav852** [comment]
using flutter_facebook_auth: ^4.4.1+1 version solved my problem
