### ISSUE TITLE
facebook_app_id and facebook_client_token can not be move from string.xml

### ISSUE THREAD

**Issue by suryamin** [darwin-morocho/flutter-facebook-auth#314]
### What version are you using?

^5.0.0+2

### What OS and version are you using to local deploy your application?

Windows 11 R2

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
not a problem
```

### Describe the Bug

not a bug

### Expected Behavior

Would it be possible to enable facebook_app_id and facebook_client_token in AndroidManifest.xml or in the class FacebookAuth.instance.login(), so I am able to secure the key with the available package via .env? At the moment the id and the token is sitting in android/app/src/main/res/values/string.xml and no ways to route into .env. Is there any solution you can advise me on in order to secure the id and the token?
Thank you. Regards

### To Reproduce

not a bug

### Relevant log output

```shell
no log
```

### flutter doctor -v

```shell
not a bug
```

**Comment by darwin-morocho** [comment]
Hi @suryamin this is more a question to the facebook community https://developers.facebook.com/community/

**Comment by suryamin** [comment]
Thank you. I'll move it to the link
