### ISSUE TITLE
Error al inicializar sesión. No se pudo acceder a su cuenta a través de esta aplicación. Inténtelo de nuevo más tarde.

### ISSUE THREAD

**Issue by kauemurakami** [darwin-morocho/flutter-facebook-auth#34]
Estoy usando su paquete para intentar autenticarme a través de Facebook, seguí sus pasos y vi el video, pero este error persiste.
También traté de usarlo aplicando una implementación de él con [Flutterfire,](https://firebase.flutter.dev/docs/auth/social/) pero independientemente, permanece en este error, sé que puede que no sea un error de lib, pero no necesitas algo más.
Al resolver problemas en los que se nos pide que insertemos un "OnCreate" en MainActivity.java, no coincide con mi código generado por el aleteo donde solo tengo MainActiviy.kt, pero quiero tomar esta duda, ¿ha cambiado algo de lo que está escrito hasta hoy? ¿O podría ser mi error de configuración?
Gracias por su atención ahora.
![WhatsApp Image 2020-11-24 at 09 06 48](https://user-images.githubusercontent.com/16777838/100106622-88f14100-2e47-11eb-893f-c923ac441a44.jpeg)

**Comment by darwin-morocho** [comment]
Saludos @kauemurakami estos errores por lo general no son de la librería si no mas bien de una configuración en facebook developers. Estas usando macOS o windows?

**Comment by kauemurakami** [comment]
Windows, fue donde intenté resolver problemas debajo de la configuración de los desarrolladores de Facebook, y se refiere a mainacivity.java, el mismo no se encuentra en mi proyecto Flutter. la clave ya ha sido generada y está configurada en el proyecto como en el video.

**Comment by darwin-morocho** [comment]
> Windows, fue donde intenté resolver problemas debajo de la configuración de los desarrolladores de Facebook, y se refiere a mainacivity.java, el mismo no se encuentra en mi proyecto Flutter. la clave ya ha sido generada y está configurada en el proyecto como en el video.

La clave de hash fue generada por linea de comandos o usando el código java?

**Comment by kauemurakami** [comment]
openssl

**Comment by darwin-morocho** [comment]
> openssl
> No pude reproducir onCreate porque no tengo MainActivity.java, en .kt no pude ejecutar el proyecto.
> ![Sem título](https://user-images.githubusercontent.com/16777838/100116443-821bfb80-2e52-11eb-9bd9-58725fd80a52.png)
> así que siguiendo tu tutorial no pude reproducir esta parte

Puedes eliminar el MainActivity.kt y crear un MainActivity.java que contenga una clase MainActivity que debe extender de FlutterActivity

**Comment by kauemurakami** [comment]
Hmm, esto parece viable, lo haré ahora.
Volveré con los resultados, este tema también puede ser útil para otras personas.
Gracias

**Comment by kauemurakami** [comment]
No parece funcionar, ¿puedo comprobar sus importaciones? ¿El repositorio del proyecto contiene su clase principal?
`D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java:10: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                                      ^
  symbol:   class Bundle
  location: class MainActivity
D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java:18: error: cannot find symbol
                MessageDigest md = MessageDigest.getInstance("SHA");
                ^
  symbol:   class MessageDigest
  location: class MainActivity
D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java:18: error: cannot find symbol
                MessageDigest md = MessageDigest.getInstance("SHA");
                                   ^
  symbol:   variable MessageDigest
  location: class MainActivity
D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java:22: error: cannot find symbol
        } catch (NameNotFoundException e) {
                 ^
  symbol:   class NameNotFoundException
  location: class MainActivity
D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java:24: error: cannot find symbol
        } catch (NoSuchAlgorithmException e) {
                 ^
  symbol:   class NoSuchAlgorithmException
  location: class MainActivity
Note: D:\projetos\dart-barb\barber_app\android\app\src\main\kotlin\com\example\barber\MainActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by kauemurakami** [comment]
De hecho, su clase principal en el ejemplo no tiene estos códigos, y tengo problemas con las importaciones.
Si no encuentra una solución en los próximos minutos, cerraré el problema, gracias por su ayuda.

**Comment by darwin-morocho** [comment]
> De hecho, su clase principal en el ejemplo no tiene estos códigos, y tengo problemas con las importaciones.
> Si yo no encuentra una solución en los próximos minutos, cerraré el problema, gracias por su ayuda.
> De lo contrario volveré con la respuesta.

En mi caso como uso macOS no era necesario generar la clave de hash usando código java pero puedes verlo en el video tutorial

**Comment by darwin-morocho** [comment]
@kauemurakami 

```java


import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.Signature;
import android.os.Bundle;
import android.util.Base64;
import android.util.Log;

import androidx.annotation.Nullable;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        try {
            PackageInfo info = getPackageManager().getPackageInfo(
                    "{your-package-name}",                  //Insert your own package name.
                    PackageManager.GET_SIGNATURES);
            for (Signature signature : info.signatures) {
                MessageDigest md = MessageDigest.getInstance("SHA");
                md.update(signature.toByteArray());
                Log.d("KeyHash:", Base64.encodeToString(md.digest(), Base64.DEFAULT));
            }
        } catch (PackageManager.NameNotFoundException e) {

        } catch (NoSuchAlgorithmException e) {

        }

    }
}

```

**Comment by kauemurakami** [comment]
las importaciones para el código no tienen automáticamente en mi AS, en el video se cortan algunas importaciones, no las obtuve todas.
Estuvo un tiempo sin usar AS, veré si puedo resolver

**Comment by kauemurakami** [comment]
Iba a ser esto, muchas gracias amigo, solucionaré este "problema", puede ser útil para otros en el futuro, gracias por su atención.
