### ISSUE TITLE
Incompatibility Issue between http version and Flutter Facebook Auth Packages

### ISSUE THREAD

**Issue by zitob9** [darwin-morocho/flutter-facebook-auth#352]
### What version are you using?

6.0.0

### What OS and version are you using to local deploy your application?

macOS 14.4

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
flutter_facebook_auth: ^6.0.0
```

### Describe the Bug

I encountered an incompatibility issue while attempting to install the dependencies for my project. The conflict arises between the Algolia and Flutter Facebook Auth packages. The error message suggests that version solving failed due to conflicting dependency requirements.

Error Message:

`Because no versions of algolia match >1.1.2 <2.0.0 and algolia 1.1.2 depends on http ^0.13.0, algolia ^1.1.2 requires http ^0.13.0. And because flutter_facebook_auth >=6.0.0 depends on facebook_auth_desktop ^1.0.0 which depends on http ^1.0.0, algolia ^1.1.2 is incompatible with flutter_facebook_auth >=6.0.0. So, because doctor_consultation depends on both flutter_facebook_auth ^6.0.0 and algolia ^1.1.2, version solving failed.`

### Expected Behavior

...

### To Reproduce

Create a new Flutter project or use an existing project.
Open the project's pubspec.yaml file.
Add flutter_facebook_auth and algolia as dependencies with the following version constraints:
flutter_facebook_auth: ^6.0.0
algolia: ">1.1.2 <2.0.0"
Save the pubspec.yaml file and run the package installation process.

### flutter doctor -v

```shell
[✓] Flutter (Channel stable, 3.10.5, on macOS 12.6.6 21G646 darwin-x64, locale
    en-FR)
    • Flutter version 3.10.5 on channel stable at /Users/mac/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (7 days ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1
```

**Comment by darwin-morocho** [comment]
Since 6.x.x flutter_facebook_auth uses http:^1.0.0  for macos apps. You must use a previous version of 6.x.x please go to https://pub.dev/packages/flutter_facebook_auth/versions

**Comment by fullflash** [comment]
so no plans to upgrade http dependency to http 1.0.0 ?
