### ISSUE TITLE
A problem occurred configuring project ':flutter_secure_storage'.> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

### ISSUE THREAD

**Issue by moliearnvincent** [darwin-morocho/flutter-facebook-auth#359]
### What version are you using?

flutter_facebook_auth: ^6.0.1

### What OS and version are you using to local deploy your application?

windows 10

### What platforms are you seeing the problem on?

Android

### pubspec.yaml

```yaml
firebase_auth: ^4.7.3
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
```

### Describe the Bug

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_secure_storage'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:

### Expected Behavior

A problem occurred configuring project ':flutter_secure_storage'.

### To Reproduce

A problem occurred configuring project ':flutter_secure_storage'.

### flutter doctor -v

```shell
Flutter version 3.13.0 on channel stable at -
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision efbf63d9c6 (3 days ago), 
    • Engine revision 1ac611c64e
    • Dart version 3.1.0
    • DevTools version 2.25.0
```

**Comment by darwin-morocho** [comment]
Sorry but this seems to be a problem with your build.gradle file please check your logs. It seems that you don't have your android name space https://developer.android.com/build/configure-app-module#set-namespace

**Comment by moliearnvincent** [comment]
> Sorry but this seems to be a problem with your build.gradle file please check your logs. It seems that you don't have your android name space https://developer.android.com/build/configure-app-module#set-namespace


But remove "flutter_facebook_auth", it works fine.

Thank you for your reply

**Comment by moliearnvincent** [comment]
> > Sorry but this seems to be a problem with your build.gradle file please check your logs. It seems that you don't have your android name space https://developer.android.com/build/configure-app-module#set-namespace
> 
> But remove "flutter_facebook_auth", it works fine.
> 
> Thank you for your reply


Solution:
facebook_auth_desktop -> flutter_secure_storage: ^8.0.0

https://github.com/mogol/flutter_secure_storage/commit/1f5d984584331e7f7122e2778060ffcdb8379947#diff-ffddade55f2f00b7d9c9ec91faea40fe83495ffd2bc9a801ff985a28b5c90f2e

if (project.android.hasProperty("namespace")) {
        namespace("com.it_nomads.fluttersecurestorage")
    }

    buildFeatures {
        buildConfig = true
    }

Thank you
