### ISSUE TITLE
No implementation found for method

### ISSUE THREAD

**Issue by oscarshaitan** [darwin-morocho/flutter-facebook-auth#36]
**Describe the bug**
On a new peroyect without any code, just this libraries on the yaml
multiimage_picker 
image_picker 
google_places_picker 
share_preferences 

they works just fine 

but the inclusion of 
flutter-facebook-auth 
the yaml 
the libraries above start to fail 
throwing  _No implementation found for method_

![image](https://user-images.githubusercontent.com/9093952/101291378-454aef80-37d6-11eb-866c-dd28b2514687.png)

removing the flutter-facebook-auth from the yaml everything works just fine

**Comment by darwin-morocho** [comment]
when you install this plugin you need first configure the plugin on Android and iOS. If you don't do it you will have that error
