### ISSUE TITLE
Segmentation fault 11 in target FBSDKCoreKit

### ISSUE THREAD

**Issue by marcoprodata** [darwin-morocho/flutter-facebook-auth#38]
Dears,

I'm trying to compile my app in Macos, but get this error:
![image](https://user-images.githubusercontent.com/16479713/102279946-ffdf9e00-3f0a-11eb-9a27-0469ec7a4656.png)

How  to solve this?

Thanks to advance and sorry for my bad english

**Comment by darwin-morocho** [comment]
> Dears,
> 
> I'm trying to compile my app in Macos, but get this error:
> ![image](https://user-images.githubusercontent.com/16479713/102279946-ffdf9e00-3f0a-11eb-9a27-0469ec7a4656.png)
> 
> How to solve this?
> 
> Thanks to advance and sorry for my bad english

You have installed cocoapods on your mac?

**Comment by darwin-morocho** [comment]
@marcoprodata  when you create a new issue you has a template. This template helps me to find the problem

Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**Comment by marcoprodata** [comment]
flutter doctor -v:
![image](https://user-images.githubusercontent.com/16479713/102359039-0f082f80-3f8f-11eb-8351-65cae4e1de46.png)

**Comment by marcoprodata** [comment]
Other files:
[files_analise.zip](https://github.com/darwin-morocho/flutter-facebook-auth/files/5703223/files_analise.zip)

**Comment by darwin-morocho** [comment]
> Other files:
> [files_analise.zip](https://github.com/darwin-morocho/flutter-facebook-auth/files/5703223/files_analise.zip)

also add your Podfile

**Comment by marcoprodata** [comment]
[Podfile.zip](https://github.com/darwin-morocho/flutter-facebook-auth/files/5705617/Podfile.zip)

My podfile, i will try to update xcode and test again, i used many times flutter clean, flutter pub get, rm ios/Podfile.lock, pod repo update.

**Comment by darwin-morocho** [comment]
> [Podfile.zip](https://github.com/darwin-morocho/flutter-facebook-auth/files/5705617/Podfile.zip)
> 
> My podfile, i will try to update xcode and test again, i used many times flutter clean, flutter pub get, rm ios/Podfile.lock, pod repo update.

Please. Let me know if the problem was solved.

**Comment by marcoprodata** [comment]
Yes, after reinstall cocoapods the problem was solved, thansk to advance
