### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by christophemacabiau** [darwin-morocho/flutter-facebook-auth#39]
Thanks for the package! Is it planned to have web support soon for it?

**Comment by darwin-morocho** [comment]
> Thanks for the package! Is it planned to have web support soon for it?

@christophemacabiau  you have web support using the pre-release version of this plugin https://pub.dev/packages/flutter_facebook_auth/versions/2.0.0-web.9

**Comment by christophemacabiau** [comment]
Thanks for your reponse. I will give it a try.
