### ISSUE TITLE
Remove loading indicator from Android

### ISSUE THREAD

**Issue by YDA93** [darwin-morocho/flutter-facebook-auth#393]
### What version are you using?

6.1.1

### What OS and version are you using to local deploy your application?

macOS Apple M1

### What platforms are you seeing the problem on?

Android

### Describe the Bug

An option to remove the loading icon is required because we already have a custom loading indicators to stick with.

### Expected Behavior

No loading icon should be displayed

### To Reproduce

Run: await FacebookAuth.instance.login() on Android mobile

**Comment by darwin-morocho** [comment]
@YDA93 this requirement is not posible due to this plugin only wraps the native android SDK. You should open an issue in the official repo https://github.com/facebook/facebook-ios-sdk/issues
