### ISSUE TITLE
flutter_facebook_auth/flutter_facebook_auth-Swift.h' file not found

### ISSUE THREAD

**Issue by khanhpro027** [darwin-morocho/flutter-facebook-auth#4]
Hi admin !
Had errors After build release . Is flutter_facebook_auth/flutter_facebook_auth-Swift.h' file not found. Maybe missing file?

**Comment by darwin-morocho** [comment]
This library was written in swift for iOS and java for Android. This is a common problem when  you create a flutter app without swift as default language for iOS. When you create a flutter app please use the command `flutter create -i swift -a java your_project_name`.
Also in your podfile you need uncomment the next line
```
#platform :ios, '9.0'
```

And in the `target 'Runner'` section check that you have the next line
```
  use_frameworks!
```

**Comment by khanhpro027** [comment]
i had add "use_frameworks!" to podfile and builder success ! thanks you for remind.

**Comment by peternagy1332** [comment]
Hi,
I've added the modifications above but I'm still getting the error in the title:
Podfile relevant part:
```
platform :ios, '11.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

```
Error:
```
   Writing result bundle at path:
    	/var/folders/rf/206cnhl96kbdgsw9vk6nryyc0000gn/T/flutter_tools.Gxs6Dj/flutter_ios_build_temp_dirbXYMYH/temporary_xcresult_bundle
/Users/nagyp/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:8:9: fatal error: 'facebook_auth-Swift.h' file not found
    #import "facebook_auth-Swift.h"
            ^~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    Result bundle written to path:
    	/var/folders/rf/206cnhl96kbdgsw9vk6nryyc0000gn/T/flutter_tools.Gxs6Dj/flutter_ios_build_temp_dirbXYMYH/temporary_xcresult_bundle
Lexical or Preprocessor Issue (Xcode): 'facebook_auth-Swift.h' file not found
/Users/nagyp/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:7:8
```

**Comment by darwin-morocho** [comment]
> Hi, I've added the modifications above but I'm still getting the error in the title: Podfile relevant part:
> 
> ```
> platform :ios, '11.0'
> 
> target 'Runner' do
>   use_frameworks!
>   use_modular_headers!
> 
>   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
> end
> ```
> 
> Error:
> 
> ```
>    Writing result bundle at path:
>     	/var/folders/rf/206cnhl96kbdgsw9vk6nryyc0000gn/T/flutter_tools.Gxs6Dj/flutter_ios_build_temp_dirbXYMYH/temporary_xcresult_bundle
> /Users/nagyp/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:8:9: fatal error: 'facebook_auth-Swift.h' file not found
>     #import "facebook_auth-Swift.h"
>             ^~~~~~~~~~~~~~~~~~~~~~~
>     1 error generated.
>     note: Using new build system
>     note: Planning
>     note: Build preparation complete
>     note: Building targets in dependency order
>     Result bundle written to path:
>     	/var/folders/rf/206cnhl96kbdgsw9vk6nryyc0000gn/T/flutter_tools.Gxs6Dj/flutter_ios_build_temp_dirbXYMYH/temporary_xcresult_bundle
> Lexical or Preprocessor Issue (Xcode): 'facebook_auth-Swift.h' file not found
> /Users/nagyp/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-5.0.0-dev.1/ios/Classes/FacebookAuthPlugin.m:7:8
> ```
check https://github.com/darwin-morocho/flutter-facebook-auth/issues/234#issuecomment-1117320064

**Comment by peternagy1332** [comment]
@darwin-morocho wow, thank you for the quick response! :)
I've already tried it this way:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      # config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end

```

**Comment by darwin-morocho** [comment]
> @darwin-morocho wow, thank you for the quick response! :) I've already tried it this way:
> 
> ```
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     flutter_additional_ios_build_settings(target)
>     target.build_configurations.each do |config|
>       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
>       # config.build_settings['SWIFT_VERSION'] = '4.2'
>     end
>   end
> end
> ```

another solution is define the deployment target in xcode instead of podfile. Also try to use 12.0 instead of 11.0 

don't forget to `flutter clean` and update cocoapods https://github.com/darwin-morocho/flutter-facebook-auth/issues/234#issuecomment-1120499571

**Comment by peternagy1332** [comment]
Using the latest cocoapod, I get the same error
```
nagyp@Peters-MacBook-Air ios % gem which cocoapods          
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods.rb
```

However, seems like the comment you are referencing throws this error. What am I doing wrong?
```
aunching lib/main.dart on iPhone 13 mini in debug mode...
lib/main.dart:1
Warning: CocoaPods is installed but broken. Skipping pod install.
  You appear to have CocoaPods installed but it is not working.
  This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
  This can usually be fixed by re-installing CocoaPods.
To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

CocoaPods not installed or not in valid state.
```

**Comment by peternagy1332** [comment]
Got it! I've had to restart vscode serveral times. After the first restart it mentioned something like some IDE files are corrupted, couldn't even start the terminal and I must reinstall vscode, but also offered to restart it. So I did it and seems like it works. Thank you again, @darwin-morocho !
