### ISSUE TITLE
Limited login email issue

### ISSUE THREAD

**Issue by blizzy312** [darwin-morocho/flutter-facebook-auth#403]
### What version are you using?

flutter_facebook_auth:7.0.0-dev.6

### What OS and version are you using to local deploy your application?

macOS 13.5.2

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
flutter_facebook_auth: ^7.0.0-dev.6
```

### Describe the Bug

Hi! Thank you for your hard work. I've been trying to test limited login for IOS in your latest dev branch [7.0.0-dev.6]. But noticed that 'userEmail' is a non-nullable string, which just fails for my test user that didn't have assigned email. I know that this is still 'dev' branch, but I hope it will be fixed in the next stable release. Thanks.

### Expected Behavior

'userEmail' is nullable string, as not all users have assigned emails.

### To Reproduce

Login with user that doesn't have assigned email

### Relevant log output

```shell
type 'Null' is not a subtype of type 'String'
flutter:  new LimitedToken.fromJson (package:flutter_facebook_auth_platform_interface/src/access_token.dart:37:22)
flutter:  FacebookAuthPlatformImplementation.accessToken (package:flutter_facebook_auth_platform_interface/src/facebook_auth_implementation.dart:106:26)
```

### flutter doctor -v

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.1, on macOS 13.5.2 22G91 darwin-arm64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] VS Code (version 1.85.0)
[✓] VS Code (version 1.85.0-insider)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by drpshtiwan** [comment]
![Screenshot 2024-05-19 at 1 15 59 AM](https://github.com/darwin-morocho/flutter-facebook-auth/assets/6718949/b7d71a61-1e57-4275-8b14-9e4f56617f9b)

**Comment by darwin-morocho** [comment]
Check 7.0.0

**Comment by zunsakai** [comment]
Hi @darwin-morocho 
I faced the same error. In this line, key used is `token`
<img width="469" alt="image" src="https://github.com/user-attachments/assets/38fe5fdb-a453-4a07-a5fe-447c652e017a">
https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth_platform_interface/lib/src/access_token.dart#L90
But in storage it is saved as `tokenString`.
<img width="918" alt="Screenshot 2024-09-08 at 17 03 17" src="https://github.com/user-attachments/assets/0f6cd656-c6b7-4691-8bd3-041a3103f770">
I used 7.1.0
Please fix. Thanks

**Comment by darwin-morocho** [comment]
> Hi @darwin-morocho I faced the same error. In this line, key used is `token` <img alt="image" width="469" src="https://private-user-images.githubusercontent.com/8158019/365429285-38fe5fdb-a453-4a07-a5fe-447c652e017a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY3MzgsIm5iZiI6MTcyNTc5NjQzOCwicGF0aCI6Ii84MTU4MDE5LzM2NTQyOTI4NS0zOGZlNWZkYi1hNDUzLTRhMDctYTVmZS00NDdjNjUyZTAxN2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMTE1MzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjQ0ODBmOTc2Mzc1YTQwYjAzMzMxMmY4MDkxZjUzZTNjOGFiZjNmNjI1NjEzMDE2MjczZTFjMTdhZjY0NDQwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8QA9MVEYRLlYJbMVW0WutHW6wBo04q4ERhfsW4weHLI"> https://github.com/darwin-morocho/flutter-facebook-auth/blob/master/facebook_auth_platform_interface/lib/src/access_token.dart#L90 But in storage it is saved as `tokenString`. <img alt="Screenshot 2024-09-08 at 17 03 17" width="918" src="https://private-user-images.githubusercontent.com/8158019/365429450-0f6cd656-c6b7-4691-8bd3-041a3103f770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTY3MzgsIm5iZiI6MTcyNTc5NjQzOCwicGF0aCI6Ii84MTU4MDE5LzM2NTQyOTQ1MC0wZjZjZDY1Ni1jNmI3LTQ2OTEtOGJkMy0wNDFhMzEwM2Y3NzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDhUMTE1MzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY1YzkwMDdiMjNjMjVmM2FjZTJjNTQ2M2EwY2Q4ODlkMTNmNzRjMTBlZDY1N2FiMGY1YTdmNjVmZjI0YTgzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4xCCs7afXY3BU-V5_hAv4wu2F0TgOvagh1DMcUAhvu8"> I used 7.1.0 Please fix. Thanks

Check 7.1.1
