### ISSUE TITLE
Compiler errors in FacebookAuth

### ISSUE THREAD

**Issue by bastaware** [darwin-morocho/flutter-facebook-auth#41]
**Describe the bug**
After adding the plugin I get 4 errors in xcode.
The project is an Objective-C projects, as that seemed to work best with Flutter. But swift was enabled following the description in the docs.
I've tried changing platform in podfile to 9.0 or 10.0 - no apparent difference.

Errors:

Swift Compiler Error Group
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.0+1/ios/Classes/FacebookAuth.swift:70:91: Extra trailing closure passed in call
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.0+1/ios/Classes/FacebookAuth.swift:70:41: Cannot convert value of type '[Permission]' to expected argument type '[String]'
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.0+1/ios/Classes/FacebookAuth.swift:70:41: Arguments to generic parameter 'Element' ('Permission' and 'String') are expected to be equal
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.0+1/ios/Classes/FacebookAuth.swift:146:46: Value of type 'AccessToken' has no member 'permissions'
/Users/xxx/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.0+1/ios/Classes/FacebookAuth.swift:147:47: Value of type 'AccessToken' has no member 'declinedPermissions'

**Environment**
`flutter doctor -v`
[✓] Flutter (Channel dev, 1.26.0-8.0.pre, on macOS 11.1 20C69 darwin-x64, locale da-DK)
    • Flutter version 1.26.0-8.0.pre at /Users/xxx/flutter
    • Framework revision b9d06fffb2 (8 days ago), 2021-01-07 18:36:48 -0800
    • Engine revision 42a8d4c681
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Google Chrome.app/Contents/MacOS/google-chrome-unsafe

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.2 Preview.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5558                        • android-x86    • Android 11 (API 30) (emulator)
    • iPhone 11 (mobile)          • 7C16F586-DEC3-471D-A849-BA4037648DBD • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • iPhone 11 Pro (mobile)      • 694AC23D-73E2-4C8C-8484-F024573FB95A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)             • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 87.0.4280.141

`pubspec.yaml`

name: xxx
description: xxx

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: "0.6.0"
  firebase_auth: "^0.19.0+1"
  google_sign_in: ^4.5.9
  flutter_facebook_auth: ^2.0.0
  get: ^3.24.0
  font_awesome_flutter: ^8.11.0
  flutter_login:
    git:
      url: git://github.com/bastaware/flutter_login.git
      ref: master

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

`Info.plist`
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>stockportfolyo</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
    
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLSchemes</key>
            
            <array>
                <string>fb228942695306565</string>
                <string>com.googleusercontent.apps.1040699615982-r5i3ibof1dbnt262smnghkkk5nf7haqi</string>
            </array>
        </dict>
    </array>
    
    <key>FacebookAppID</key>
    <string>228942695306565</string>
    <key>FacebookDisplayName</key>
    <string>Stockportfolyo</string>
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>fbapi</string>
      <string>fb-messenger-share-api</string>
      <string>fbauth2</string>
      <string>fbshareextension</string>
    </array>
</dict>
</plist>

**To Reproduce**
Add plugin and compile in Android Studio or Xcode

**Expected behavior**
No compile errors

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.
![image](https://user-images.githubusercontent.com/1000036/104813399-4d507300-5809-11eb-9337-d7b6105e3157.png)

![image](https://user-images.githubusercontent.com/1000036/104813404-55a8ae00-5809-11eb-90fd-ede7b03c947f.png)

**Comment by darwin-morocho** [comment]
@bastaware  please got to your `Podfile.lock` and let me know what version of FBSDKCoreKit and FBSDKLoginKit are you using

**Comment by darwin-morocho** [comment]
> @bastaware please got to your `Podfile.lock` and let me know what version of FBSDKCoreKit and FBSDKLoginKit are you using

@bastaware  also maybe the pod dependencies is using the `objective-c` version of  `FBSDKCoreKit` and `FBSDKLoginKit` maybe because the flutter sdk ran the `pod install` command before enable swift support. To fix that just remove `flutter_facebook_auth` from your `pubspec.yaml` and go to `ios` folder with `cd ios` and run `pod install` to remove the previous  `FBSDKCoreKit` and `FBSDKLoginKit` pods. And now just add `flutter_facebook_auth` now if you run pod install you must have the swift version of `FBSDKCoreKit` and `FBSDKLoginKit`

**Comment by bastaware** [comment]
Thanks for your prompt support! Unfortunately it doesn't solve the problem. Here is what I did:

1. Deleted flutter_facebook_auth: ^2.0.0 from pubspec.yaml
2. Pub get
3. pod install
4. insert flutter_facebook_auth: ^2.0.0 from pubspec.yaml
5. pod install

Downloading dependencies
Installing AppAuth (1.4.0)
Installing FBSDKCoreKit (8.2.0)
Installing FBSDKLoginKit (8.2.0)
Installing Firebase (6.33.0)
Installing FirebaseAuth (6.9.2)
Installing FirebaseCore (6.10.3)
Installing FirebaseCoreDiagnostics (1.7.0)
Installing Flutter (1.0.0)
Installing GTMAppAuth (1.1.0)
Installing GTMSessionFetcher (1.5.0)
Installing GoogleDataTransport (7.5.1)
Installing GoogleSignIn (5.0.2)
Installing GoogleUtilities (6.7.2)
Installing PromisesObjC (1.2.12)
Installing firebase_auth (0.19.0-1)
Installing firebase_core (0.6.0)
Installing flutter_facebook_auth (1.0.0)
Installing google_sign_in (0.0.1)
Installing integration_test (0.0.1)
Installing nanopb (1.30906.0)
Generating Pods project
Integrating client project
Pod installation complete! There are 6 dependencies from the Podfile and 20 total pods installed.

6. Try running from Android studio -> 

    ** BUILD FAILED **


Xcode's output:
↳
    /Users/christianhessenbruch/Documents/projects/Razorback/client/stockportfolyo/ios/Pods/AppAuth/Source/AppAuth/iOS/OIDExternalUserAgentIOSCustomBrowser.m:148:42: warning: 'openURL:' is deprecated: first deprecated in iOS 10.0 [-Wdeprecated-declarations]
          [[UIApplication sharedApplication] openURL:_appStoreURL];

7. try building from XCode. But get the same 4 errors.

![image](https://user-images.githubusercontent.com/1000036/104820296-1c396800-5834-11eb-91c3-a6d4bc204f0c.png)

Here is my podfile.lock

PODS:
  - AppAuth (1.4.0):
    - AppAuth/Core (= 1.4.0)
    - AppAuth/ExternalUserAgent (= 1.4.0)
  - AppAuth/Core (1.4.0)
  - AppAuth/ExternalUserAgent (1.4.0)
  - FBSDKCoreKit (8.2.0):
    - FBSDKCoreKit/Basics (= 8.2.0)
    - FBSDKCoreKit/Core (= 8.2.0)
  - FBSDKCoreKit/Basics (8.2.0)
  - FBSDKCoreKit/Core (8.2.0):
    - FBSDKCoreKit/Basics
  - FBSDKLoginKit (8.2.0):
    - FBSDKLoginKit/Login (= 8.2.0)
  - FBSDKLoginKit/Login (8.2.0):
    - FBSDKCoreKit (~> 8.2.0)
  - Firebase/Auth (6.33.0):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.9.2)
  - Firebase/CoreOnly (6.33.0):
    - FirebaseCore (= 6.10.3)
  - firebase_auth (0.19.0-1):
    - Firebase/Auth (= 6.33.0)
    - firebase_core
    - Flutter
  - firebase_core (0.6.0):
    - Firebase/CoreOnly (= 6.33.0)
    - Flutter
  - FirebaseAuth (6.9.2):
    - FirebaseCore (~> 6.10)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.7)
    - GoogleUtilities/Environment (~> 6.7)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.10.3):
    - FirebaseCoreDiagnostics (~> 1.6)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
  - FirebaseCoreDiagnostics (1.7.0):
    - GoogleDataTransport (~> 7.4)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30906.0)
  - Flutter (1.0.0)
  - flutter_facebook_auth (1.0.0):
    - FBSDKCoreKit (~> 8.2.0)
    - FBSDKLoginKit (~> 8.2.0)
    - Flutter
  - google_sign_in (0.0.1):
    - Flutter
    - GoogleSignIn (~> 5.0)
  - GoogleDataTransport (7.5.1):
    - nanopb (~> 1.30906.0)
  - GoogleSignIn (5.0.2):
    - AppAuth (~> 1.2)
    - GTMAppAuth (~> 1.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - GoogleUtilities/AppDelegateSwizzler (6.7.2):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.2):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.2):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (6.7.2):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.2)"
  - GoogleUtilities/Reachability (6.7.2):
    - GoogleUtilities/Logger
  - GTMAppAuth (1.1.0):
    - AppAuth/Core (~> 1.4)
    - GTMSessionFetcher (~> 1.4)
  - GTMSessionFetcher (1.5.0):
    - GTMSessionFetcher/Full (= 1.5.0)
  - GTMSessionFetcher/Core (1.5.0)
  - GTMSessionFetcher/Full (1.5.0):
    - GTMSessionFetcher/Core (= 1.5.0)
  - integration_test (0.0.1):
    - Flutter
  - nanopb (1.30906.0):
    - nanopb/decode (= 1.30906.0)
    - nanopb/encode (= 1.30906.0)
  - nanopb/decode (1.30906.0)
  - nanopb/encode (1.30906.0)
  - PromisesObjC (1.2.12)

DEPENDENCIES:
  - firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)
  - firebase_core (from `.symlinks/plugins/firebase_core/ios`)
  - Flutter (from `Flutter`)
  - flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`)
  - google_sign_in (from `.symlinks/plugins/google_sign_in/ios`)
  - integration_test (from `.symlinks/plugins/integration_test/ios`)

SPEC REPOS:
  trunk:
    - AppAuth
    - FBSDKCoreKit
    - FBSDKLoginKit
    - Firebase
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - GoogleDataTransport
    - GoogleSignIn
    - GoogleUtilities
    - GTMAppAuth
    - GTMSessionFetcher
    - nanopb
    - PromisesObjC

EXTERNAL SOURCES:
  firebase_auth:
    :path: ".symlinks/plugins/firebase_auth/ios"
  firebase_core:
    :path: ".symlinks/plugins/firebase_core/ios"
  Flutter:
    :path: Flutter
  flutter_facebook_auth:
    :path: ".symlinks/plugins/flutter_facebook_auth/ios"
  google_sign_in:
    :path: ".symlinks/plugins/google_sign_in/ios"
  integration_test:
    :path: ".symlinks/plugins/integration_test/ios"

SPEC CHECKSUMS:
  AppAuth: 31bcec809a638d7bd2f86ea8a52bd45f6e81e7c7
  FBSDKCoreKit: 4afd6ff53d8133a433dbcda44451c9498f8c6ce4
  FBSDKLoginKit: 7181765f2524d7ebf82d9629066c8e6caafc99d0
  Firebase: 8db6f2d1b2c5e2984efba4949a145875a8f65fe5
  firebase_auth: 93671a45e6729e0965119c99f0d18ccd107f593b
  firebase_core: e221fff1a563728844a0271bf995eda1e6c20f27
  FirebaseAuth: c92d49ada7948d1a23466e3db17bc4c2039dddc3
  FirebaseCore: d889d9e12535b7f36ac8bfbf1713a0836a3012cd
  FirebaseCoreDiagnostics: 770ac5958e1372ce67959ae4b4f31d8e127c3ac1
  Flutter: 434fef37c0980e73bb6479ef766c45957d4b510c
  flutter_facebook_auth: bad08a3d465e7b7ba9d8468a9dc7df3f69c136b8
  google_sign_in: 6bd214b9c154f881422f5fe27b66aaa7bbd580cc
  GoogleDataTransport: f56af7caa4ed338dc8e138a5d7c5973e66440833
  GoogleSignIn: 7137d297ddc022a7e0aa4619c86d72c909fa7213
  GoogleUtilities: 7f2f5a07f888cdb145101d6042bc4422f57e70b3
  GTMAppAuth: 197a8dabfea5d665224aa00d17f164fc2248dab9
  GTMSessionFetcher: b3503b20a988c4e20cc189aa798fd18220133f52
  integration_test: 6eb66a19f7104200dcfdd62bc0077e1b09686e4f
  nanopb: 59317e09cf1f1a0af72f12af412d54edf52603fc
  PromisesObjC: 3113f7f76903778cf4a0586bd1ab89329a0b7b97

PODFILE CHECKSUM: 69241d3f507d9e0de25e3e69aaec8c6ac758c29b

COCOAPODS: 1.10.1

**Comment by darwin-morocho** [comment]
@bastaware  I reproduced the same error. 
![image](https://user-images.githubusercontent.com/15864336/104824933-7b8f7c00-5824-11eb-8ec9-9887d7c21b19.png)

Unfortunately enabling `swift support` in the current `facebook sdk` version dont fix this issue. This plugin was written with swift so you need use swift by default in your flutter project. You can delete your `ios` folder and run the command `flutter create  -i swift .` to generate the ios folder again using swift by default.

Remember flutter and apple recommends use swift for ios projects.

**Comment by bastaware** [comment]
God damn! It works. Thanks a lot. Saved me a bunch of time.

THX!

**Comment by akhilmorya** [comment]
I am getting the same error. Tried with deleting the iOS folder and then running command to create swift iOS project. But the issue is still there. Also tried other method to migrate project to swift, but with no success.

**Comment by darwin-morocho** [comment]
> I am getting the same error. Tried with deleting the iOS folder and then running command to create swift iOS project. But the issue is still there. Also tried other method to migrate project to swift, but with no success.

If the issue is still there your project is not using swift as a default language

**Comment by darwin-morocho** [comment]
> Any specific steps to set it to default language through xcode or somewhere else?

There is not way to do this from xcode, you must do it when you create the futter project or deleting the ios folder and running the command `flutter create -i swift .` on your root folder
