### ISSUE TITLE
Support for FB SDK 9.0

### ISSUE THREAD

**Issue by MyBuzzTechnologies** [darwin-morocho/flutter-facebook-auth#42]
We’ve recently received an email from Facebook saying that we should use SDK 9.0 with support for the new classic mode and limited login mode for iOS.

Could you upgrade your components to use SDK 9.0.

For reference, the email message is below:

Update your Facebook iOS SDK or Facebook SDK for Unity to version 9.0+ on January 19, 2021 for the new version of Facebook Login.

This new version of Facebook Login supports two distinct modes: Limited and Classic. Your app will pass Facebook a flag indicating the mode you have chosen for each of your users.

Limited Login mode implements safeguards designed to prevent the fact that a person used Facebook to log into your iOS app from being used to target advertising or measure advertising effectiveness. The mode is based on the OpenID Connect standard and allows users to create new accounts or access existing accounts on your app while only sharing their name, profile pic, and (optionally) email address. Note that Limited Login mode utilizes a JSON Web Token, which does not support Graph API queries.

Classic Login mode remains unchanged from the login product you and your users already know and love. It allows users to create new accounts or access existing accounts while granting your app the ability to access (with Facebook approval and user consent) certain Facebook data intended to improve their experience in your app. Note that Classic Login mode utilizes an oAuth 2.0 Access Token which supports Graph API queries.

You can choose either mode uniformly for all of your users, or choose one of the two modes conditionally.

Go to Limited Login for iOS 14 for more information, including implementation documentation and FAQs.

**Comment by darwin-morocho** [comment]
hi @MyBuzzTechnologies I'll check the Facebook sdk 9.0 to ensure that we don't have a breaking changes.

**Comment by darwin-morocho** [comment]
@MyBuzzTechnologies  the new version of this plugin has support for FSDK 9.0.0 on iOS
