### ISSUE TITLE
Facebook SDK makes calls to graph.facebook.com even though SDK is not initialized nor used

### ISSUE THREAD

**Issue by PhantomRay** [darwin-morocho/flutter-facebook-auth#425]
### What version are you using?

7.1.0

### What OS and version are you using to local deploy your application?

macOS

### What platforms are you seeing the problem on?

iOS

### pubspec.yaml

```yaml
flutter_facebook_auth: 7.1.0
```

### Describe the Bug

From app start log, I can see the following:

```
FBSDKLog: starting with Graph API v2.4, GET requests for /<ID>/model_asset should contain an explicit "fields" parameter
FBSDKLog: starting with Graph API v2.4, GET requests for /<ID>/ios_skadnetwork_conversion_config should contain an explicit "fields" parameter
```

### Expected Behavior

It's creepy to send this request to Facebook without user/developer's consent.

There are ppl talking about this:

- https://www.reddit.com/r/iOSProgramming/comments/l2mt8z/facebook_sdk_makes_calls_to_graphfacebookcom_even/
- https://news.ycombinator.com/item?id=23098715

### To Reproduce

Launch app and see logs from Xcode.

### flutter doctor -v

```shell
N/A
```

**Comment by darwin-morocho** [comment]
@PhantomRay this issue must be opened in the official sdk repo

https://github.com/facebook/facebook-ios-sdk/issues
