### ISSUE TITLE
flutter_facebook_auth failing in login on Samsung and few other devices

### ISSUE THREAD

**Issue by moolchand** [darwin-morocho/flutter-facebook-auth#43]
**Describe the bug**
On few of the devices, we arent being able to login in our app using facebook account

Code Sample:-

Following is the code snippet which we are using to do facebook login:-
```dart
Future<bool> signInWithFacebook(BuildContext context) async {
try {
AccessToken result = await FacebookAuth.instance.login();
final AuthCredential credential = FacebookAuthProvider.credential(
result.token,
);
await _auth.signInWithCredential(credential);
DateTime now = new DateTime.now();
createDocIfNewUser('facebook', now);
_user.setData(await DatabaseService.getUser(_auth.currentUser));
_user.loggedInUsing = 'facebook';
_user.lastLoggedIn = now;
_user.defaultLanguage = _language;
_user.country = _country;
DatabaseService.updateUserInFirebase(_auth.currentUser.uid, _user);
_status = Status.VerifiedOTP;
notifyListeners();
Toast.show('Logged into Facebook', context);
return true;
} on FacebookAuthException catch (e) {
print(e.message);
_status = Status.Unauthenticated;
notifyListeners();
// TODO: remove error logs
Toast.show("Failed to sign in with Facebook: ${e.message}", context,
duration: 3);
return false;
}
}
```

**Environment**
Samsung devices.
**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
@moolchand  you did not provide enough information about the problem. I've tested this plugin using in a samsung Galaxy S8+ and everything is ok. 

Please add a error log if you have one.
Also you are using firebase make sure that you have firebase_auth correctly set up.

**Comment by moolchand** [comment]
@darwin-morocho  we get following screen in the error:-
![facebookerror](https://user-images.githubusercontent.com/58115278/105520919-480b9080-5d01-11eb-9dda-13955b12f952.jpg)

**Comment by moolchand** [comment]
The error comes only for specific android devices, for other devices it works like a charm.

**Comment by darwin-morocho** [comment]
> The error comes only for specific android devices, for other devices it works like a charm.

@moolchand  check this https://stackoverflow.com/questions/39051517/login-error-there-is-an-error-in-logging-you-into-this-application-please-try

**Comment by moolchand** [comment]
Thanks @darwin-morocho  would try the suggestions of this stackover flow question.

**Comment by moolchand** [comment]
@darwin-morocho  we tried the suggestions of the stackoverflow question, but issue still seems to be persisting.

**Comment by darwin-morocho** [comment]
> @darwin-morocho we tried the suggestions of the stackoverflow question, but issue still seems to be persisting.

@moolchand  I cannot help you more because this is not an issue of the plugin. This "issue" is a common mistake for windows developers because the key hash that you have been added is not the correct key. Other solution could be delete the facebook app in your console and create a new app. Also if you are running this app in release mode in other devices you will need to add a release hash in your facebook developer console.

Here you have more info of the same issue https://github.com/facebook/react-native-fbsdk/issues/633

Maybe your facebook developer configuration doesn't allow you use the default login behaviour, try using
```dart
await FacebookAuth.instance.login(loginBehavior:LoginBehavior.NATIVE_WITH_FALLBACK);
```

**Comment by darwin-morocho** [comment]
closed by inactivity
