### ISSUE TITLE
Unhandled error MissingPluginException when running on Android + use google_sign_in package, no issues in iOS

### ISSUE THREAD

**Issue by jorjyeah** [darwin-morocho/flutter-facebook-auth#46]
```
E/flutter (25706): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Unhandled error MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in) occurred in bloc Instance of 'SocmedSignInBloc'.
E/flutter (25706): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (25706): <asynchronous suspension>
E/flutter (25706): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (25706): #2      MethodChannelGoogleSignIn.init (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:28:20)
E/flutter (25706): #3      GoogleSignIn._ensureInitialized (package:google_sign_in/google_sign_in.dart:249:62)
E/flutter (25706): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:231:11)
E/flutter (25706): #5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:288:18)
E/flutter (25706): #6      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:359:9)
....
```
Here is the error when I use flutter_facebook_auth with google_sign_in and I try to log in with google_sign_in. The same error happens when I try to log in with flutter_facebook_auth.

![image](https://user-images.githubusercontent.com/33625457/107170083-06adfd00-69f2-11eb-9ecc-c1051c733e89.png)

![image](https://user-images.githubusercontent.com/33625457/107170107-188fa000-69f2-11eb-98f9-0c9e0dcc725d.png)

I don't know why this package always makes an error such as that. So, I use another package called flutter_facebook_login for Facebook authentication, and all safe. Is there something wrong with this package? Does this package use the same resource and code with google_sign_in?

**Comment by darwin-morocho** [comment]
flutter_facebook_login uses an old facebook sdk version that doesn't need an initial set up. Please read the documenation you need first configure the plugin on Android and iOS before run the project.

**Comment by darwin-morocho** [comment]
> flutter_facebook_login uses an old facebook sdk version that doesn't need an initial set up. Please read the documenation you need first configure the plugin on Android and iOS before run the project.

For more info https://github.com/flutter/flutter/issues/14137

**Comment by darwin-morocho** [comment]
closed by inactivity
