### ISSUE TITLE
MissingPluginException(No implementation found for method login on channel app.meedu/flutter_facebook_auth)

### ISSUE THREAD

**Issue by TranPhuHung98** [darwin-morocho/flutter-facebook-auth#48]
I followed Android set up on pub but this error still happen on Android device. It works fine on iOS.

**Comment by darwin-morocho** [comment]
> I followed Android set up on pub but this error still happen on Android device. It works fine on iOS.

Have you tried run `flutter clean`?

**Comment by darwin-morocho** [comment]
> > I followed Android set up on pub but this error still happen on Android device. It works fine on iOS.
> 
> Have you tried run `flutter clean`?

If the error persists maybe your android configuration is wrong. Please check the next example to see a good configuration https://github.com/meedu-app/flutter-facebook-login-example/tree/firebase_auth

**Comment by TranPhuHung98** [comment]
> > > I followed Android set up on pub but this error still happen on Android device. It works fine on iOS.
> > 
> > 
> > Have you tried run `flutter clean`?
> 
> If the error persists maybe your android configuration is wrong. Please check the next example to see a good configuration https://github.com/meedu-app/flutter-facebook-login-example/tree/firebase_auth

I'm using classpath 'com.android.tools.build:gradle:4.0.1' and can not build the app if I change it to classpath 'com.android.tools.build:gradle:3.5.0' like your example.
It told "The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility."

**Comment by darwin-morocho** [comment]
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.

https://stackoverflow.com/questions/56539737/how-to-fix-flutter-androidx-incompatibility

**Comment by ZaifSenpai** [comment]
Many developers are having issue due to this plugin. Please checkout the following issue. The solution is simply to remove this facebook login issue
[flutter-permission-handler #308](https://github.com/Baseflow/flutter-permission-handler/issues/308)

**Comment by darwin-morocho** [comment]
> Many developers are having issue due to this plugin. Please checkout the following issue. The solution is simply to remove this facebook login issue
> [flutter-permission-handler #308](https://github.com/Baseflow/flutter-permission-handler/issues/308)

This is a problem of the Facebook sdk on Android. If you don't configure the plugin before run the app flutter cannot find the others plugins because the Facebook sdk will try to find the configuration.

**Comment by darwin-morocho** [comment]
@ZaifSenpai  I've been created a new flutter project to reproduce the issue

pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_facebook_auth: ^2.0.2+1
  permission_handler: ^5.1.0+2
```

And if I use the next code before configure the facebook sdk on Android
```dart
  void _requestPermission() async {
    final status = await Permission.storage.request();
    print(status);
  }
```
I will have the next error
```
Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
```

Now I've been configured the facebook SDK on Android and run the project again and everything works.
<img src="https://user-images.githubusercontent.com/15864336/109662096-add90c80-7b38-11eb-9cb6-71678aafdfd7.png" width="300"/>

**Comment by aniketsongara** [comment]
> @ZaifSenpai I've been created a new flutter project to reproduce the issue
> 
> pubspec.yaml
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^1.0.0
>   flutter_facebook_auth: ^2.0.2+1
>   permission_handler: ^5.1.0+2
> ```
> 
> And if I use the next code before configure the facebook sdk on Android
> 
> ```dart
>   void _requestPermission() async {
>     final status = await Permission.storage.request();
>     print(status);
>   }
> ```
> 
> I will have the next error
> 
> ```
> Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
> ```
> 
> Now I've been configured the facebook SDK on Android and run the project again and everything works.
> <img alt="" width="300" src="https://user-images.githubusercontent.com/15864336/109662096-add90c80-7b38-11eb-9cb6-71678aafdfd7.png">

Having same with issue in release mode of the app with 

pubspec.yaml

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^2.1.6
  permission_handler: ^5.1.0+2
```
Please help me out from this issue

**Comment by Faisalkc4u** [comment]
I also get the same error when I use both 'permission_handler' and 'flutter_facebook_auth'. After removing flutter_facebook_auth it's working fine

**Comment by darwin-morocho** [comment]
> I also get the same error when I use both 'permission_handler' and 'flutter_facebook_auth'. After removing flutter_facebook_auth it's working fine

@Faisalkc4u  please read the documentation before use the plugin.

https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth#-important-

**Comment by darwin-morocho** [comment]
closed by inactivity

**Comment by FaizanAhmad127** [comment]
Read the documentation
https://facebook.meedu.app/#/

**Comment by TanvirMahin24** [comment]
I solved my issue by doing the configuration. [https://facebook.meedu.app/#/android][1] checkout the documentation for the full configuration details. Please `flutter clean` before starting the app. 


  [1]: https://facebook.meedu.app/#/android

**Comment by RameshMJ23** [comment]
> @ZaifSenpai I've been created a new flutter project to reproduce the issue
> 
> pubspec.yaml
> 
> ```
> dependencies:
>   flutter:
>     sdk: flutter
>   cupertino_icons: ^1.0.0
>   flutter_facebook_auth: ^2.0.2+1
>   permission_handler: ^5.1.0+2
> ```
> 
> And if I use the next code before configure the facebook sdk on Android
> 
> ```dart
>   void _requestPermission() async {
>     final status = await Permission.storage.request();
>     print(status);
>   }
> ```
> 
> I will have the next error
> 
> ```
> Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
> ```
> 
> Now I've been configured the facebook SDK on Android and run the project again and everything works. <img alt="" width="300" src="https://user-images.githubusercontent.com/15864336/109662096-add90c80-7b38-11eb-9cb6-71678aafdfd7.png">

What is configuring Facebook SDK (It is also in your documentation) ?

**Comment by darwin-morocho** [comment]
@RameshMJ23  you have an explanation here https://facebook.meedu.app/#/android

**Comment by RameshMJ23** [comment]
> @RameshMJ23 you have an explanation here https://facebook.meedu.app/#/android

Thanks for your quick response @darwin-morocho, I configured the android SDK(even tried changing it) but I am unsure of "Facebook SDK"

**Comment by yadegithub** [comment]
I solved my issue by doing  by addiing flutter_faccebook_login pakage in my pubspuk.yamel file thanks
