### ISSUE TITLE
Android black screen after starting login 

### ISSUE THREAD

**Issue by piotrseed** [darwin-morocho/flutter-facebook-auth#50]
**Describe the bug**
I/behavior::(21007): DIALOG_ONLY
I/WebViewFactory(21007): Loading com.google.android.webview version 83.0.4103.106 (code 410410683)
I/xxx.meditat(21007): The ClassLoaderContext is a special shared library.
D/nativeloader(21007): classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/arm64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
I/xxx.meditat(21007): The ClassLoaderContext is a special shared library.
D/nativeloader(21007): classloader namespace configured for unbundled product apk. library_path=/product/app/WebViewGoogle/lib/arm64:/product/app/WebViewGoogle/WebViewGoogle.apk!/lib/arm64-v8a:/product/app/TrichromeLibrary/TrichromeLibrary.apk!/lib/arm64-v8a:/product/lib64:/system/product/lib64
I/cr_LibraryLoader(21007): Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder(21007): Flushed 3 samples from 3 histograms.
E/AndroidRuntime(21113): FATAL EXCEPTION: main
E/AndroidRuntime(21113): Process: com.android.chrome, PID: 21113
E/AndroidRuntime(21113): Zr0: errorCode=4
E/AndroidRuntime(21113): 	at Vl1.B(chromium-TrichromeChromeGoogle.aab-stable-410410683:1)
E/AndroidRuntime(21113): 	at Am1.a(chromium-TrichromeChromeGoogle.aab-stable-410410683:3)
E/AndroidRuntime(21113): 	at Rl1.d(chromium-TrichromeChromeGoogle.aab-stable-410410683:12)
E/AndroidRuntime(21113): 	at Nl1.run(chromium-TrichromeChromeGoogle.aab-stable-410410683:1)
E/AndroidRuntime(21113): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(21113): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(21113): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(21113): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(21113): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(21113): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(21113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(21113): Caused by: Zr0: errorCode=2
E/AndroidRuntime(21113): 	at Ur0.f(chromium-TrichromeChromeGoogle.aab-stable-410410683:16)
E/AndroidRuntime(21113): 	at Ur0.b(chromium-TrichromeChromeGoogle.aab-stable-410410683:4)
E/AndroidRuntime(21113): 	at Ur0.a(chromium-TrichromeChromeGoogle.aab-stable-410410683:2)
E/AndroidRuntime(21113): 	at Ml1.run(chromium-TrichromeChromeGoogle.aab-stable-410410683:3)
E/AndroidRuntime(21113): 	at java.lang.Thread.run(Thread.java:923)
E/AndroidRuntime(21113): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libchromium_android_linker.so" not found
E/AndroidRuntime(21113): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/AndroidRuntime(21113): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime(21113): 	at java.lang.System.loadLibrary(System.java:1664)

Everything works fine on iOS however the problem only appears on android. At the same time in emulator / physical device.

**Comment by darwin-morocho** [comment]
> Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libchromium_android_linker.so" not found

@piotrseed please follow the issue template. Also add more information like your android version

**Comment by darwin-morocho** [comment]
Closed by inactivity
