### ISSUE TITLE
Login failed for published apps

### ISSUE THREAD

**Issue by olzii** [darwin-morocho/flutter-facebook-auth#53]
I have used this plugin to make Facebook login. In development environment everything works OK without any problem, i can login using my FB. But after i have published Test Version to Playstore, people are saying can not login using FB.

What is the problem ? How can i solve the issue ?

![image](https://user-images.githubusercontent.com/5012289/108621324-02abc180-746d-11eb-8498-5193219bda2f.png)

One of our users said he can not find our app in Facebook App listing. So why our app is not in this list ?

**Comment by darwin-morocho** [comment]
When you create a release version you need to add a release key hash in your facebook developer console

**Comment by olzii** [comment]
> When you create a release version you need to add a release key hash in your facebook developer console.
> 
> This is not an issue. Please close it.

I have did it already, but it is not working...

**Comment by darwin-morocho** [comment]
the google play console sign the app with a new hash you need go to your Google play and find your new hash.

https://stackoverflow.com/questions/44798378/google-play-app-signing-keyhash-mismatch/52785464

**Comment by olzii** [comment]
> https://stackoverflow.com/questions/44798378/google-play-app-signing-keyhash-mismatch/52785464

Thank you, I will try it
