### ISSUE TITLE
i am getting a blank page rather than facebook login page

### ISSUE THREAD

**Issue by mohadel92** [darwin-morocho/flutter-facebook-auth#54]
**Describe the bug**
i have followed all the steps to login with facebook Android 
and  i couldn't login to with my facebook account[blank page]

**Environment**
`
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.14.6 18G8012, locale en-EG)
    • Flutter version 1.22.3 at /Users/mohammedadelalisorour/Developer/flutter
    • Framework revision 8874f21e79 (4 months ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/mohammedadelalisorour/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.10.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Redmi Note 5 (mobile) • 47c30211 • android-arm64 • Android 9 (API 28)

• No issues found!
`

`
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_dialog: ^0.9.3
  badges: ^1.1.6
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  firebase_messaging: ^7.0.3
  flushbar: ^1.10.4
  flutter_facebook_auth: ^2.0.2
  flutter_signin_button: ^1.1.0
  flutter_spinkit: ^4.1.2+1
  flutter_svg: null
  get: ^3.24.0
  get_storage: ^1.4.0
  introduction_screen: ^1.0.9
  number_animation: ^0.1.2
  photo_view: ^0.10.3
  rflutter_alert: ^1.1.0
  shimmer: ^1.1.2
  smooth_star_rating: ^1.1.1
  url_launcher: ^5.7.10
  circular_check_box: ^1.0.4
  smart_select: ^4.3.2
  image_picker: ^0.6.7+22
  liquid_progress_indicator: ^0.3.2
  cached_network_image: ^2.2.0+1
  flutter_staggered_animations: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

`

`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.seven_square.mylook_customer">

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <application

        android:name="com.seven_square.mylook.Application"
        android:label="My Look"
        android:icon="@mipmap/ic_launcher">

        <meta-data android:name="com.facebook.sdk.ApplicationId"
            android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />
        <activity
            android:name="com.facebook.CustomTabActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

        <activity
            android:screenOrientation="portrait"
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">

            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

    </application>

    <uses-permission android:name="android.permission.INTERNET"/>
</manifest>
`
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_notification_channel_id" translatable="false">fcm_default_channel</string>
    <string name="app_name">My Look</string>
    <string name="facebook_app_id">495723724429126</string>

    <string name="fb_login_protocol_scheme">fb495723724429126</string>
</resources>`

**To Reproduce**
follow the required implementation

**Expected behavior**
show normal facbook login

**Screenshots**
<a href="https://ibb.co/hR363dY"><img src="https://i.ibb.co/jvnNnwJ/Screenshot-2021-02-21-16-39-35-853-com-android-chrome.jpg" alt="Screenshot-2021-02-21-16-39-35-853-com-android-chrome" border="0"></a><br />

**Comment by darwin-morocho** [comment]
hi @mohadel92, I've never give that error maybe is a problem with your network or with your ssl cache. Test the login using a diferent Android device

**Comment by mohadel92** [comment]
thanks for your immediate response
i tried on another device
and i think the  login  worked as expected

i got these errors
`/flutter (22226): login failed
D/View    (22226): [Warning] assignParent to null: this = DecorView@d80d27[FacebookActivity]
D/WindowClient(22226): Remove from mViews: DecorView@d80d27[FacebookActivity], this = android.view.WindowManagerGlobal@17de669
I/System.out(22226): isEmailSend:POST
I/System.out(22226): Check isMmsSendPdu
I/System.out(22226): [OkHttp] sendRequest<<
`
but at least i found any interaction with my app
on my first device[Redmi Note 5] i have no facebook app nor Facebook account
is it a must to have a facebook app installed to use this feature

**Comment by darwin-morocho** [comment]
by default the Facebook sdk use the native app if you don't have the app installed in that case uses the web login

**Comment by mohadel92** [comment]
@darwin-morocho  in my case i cannot open any webview
to get the login properly 
is there is anyway to debug this issue
on phones without facebook app?

**Comment by darwin-morocho** [comment]
> @darwin-morocho in my case i cannot open any webview
> to get the login properly
> is there is anyway to debug this issue
> on phones without facebook app?

I've never had this issue. I allways use the web login using an Android emulador without any problem. 

Please clone and run the next example and let me know if you have the same issue

**Comment by darwin-morocho** [comment]
closed by inactivity
