### ISSUE TITLE
FacebookAuth.swift:139:47: error: value of type 'AccessToken' has no member 'declinedPermissions'

### ISSUE THREAD

**Issue by luckyseven** [darwin-morocho/flutter-facebook-auth#55]
Hi, i'm trying to build my Flutter app for iOS but i get this error:

    /Users/luckyseven/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.2/ios/Classes/FacebookAuth.swift:138:46: error: value of type 'AccessToken' has no member 'permissions'
                "grantedPermissions":accessToken.permissions.map {item in item.name},
                                     ~~~~~~~~~~~ ^~~~~~~~~~~

    /Users/luckyseven/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.2/ios/Classes/FacebookAuth.swift:139:47: error: value of type 'AccessToken' has no member 'declinedPermissions'
                "declinedPermissions":accessToken.declinedPermissions.map {item in item.name},
                                      ~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~

I'm using flutter_facebook_auth 2.0.2

Thank you

**Comment by darwin-morocho** [comment]
> Hi, i'm trying to build my Flutter app for iOS but i get this error:
> 
> ```
> /Users/luckyseven/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.2/ios/Classes/FacebookAuth.swift:138:46: error: value of type 'AccessToken' has no member 'permissions'
>             "grantedPermissions":accessToken.permissions.map {item in item.name},
>                                  ~~~~~~~~~~~ ^~~~~~~~~~~
> 
> /Users/luckyseven/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-2.0.2/ios/Classes/FacebookAuth.swift:139:47: error: value of type 'AccessToken' has no member 'declinedPermissions'
>             "declinedPermissions":accessToken.declinedPermissions.map {item in item.name},
>                                   ~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
> ```
> 
> I'm using flutter_facebook_auth 2.0.2
> 
> Thank you

Hi the problem is because your project uses objective-c, for some reasons the swift facebook sdk don't work correctly with flutter for objective-c projects.

Please change your ios project to use swift

**Comment by luckyseven** [comment]
Great, thank you!
