### ISSUE TITLE
Get images from the user

### ISSUE THREAD

**Issue by jonhygg99** [darwin-morocho/flutter-facebook-auth#57]
Hello, I think this feature is not implemented, but I need to have the images from the person from Facebook.
I saw that the `getUserData()` is only available for fields. Is there any way to do or have the Edges part?
https://developers.facebook.com/docs/graph-api/reference/user/
Thanks in advance.

**Comment by darwin-morocho** [comment]
hi when you call to the login method you need to add the photos permission and then you can use the getUserData to get the user images using the field

**Comment by jonhygg99** [comment]
Thank you so much!
