### ISSUE TITLE
Update plugin_platform_interface to 2.0.0

### ISSUE THREAD

**Issue by felixgabler** [darwin-morocho/flutter-facebook-auth#58]
Other packages are already using plugin_platform_interface 2.0.0 for null-safety and I got a version solving error because this package is using ^1.1.0-nullsafety.2. Would it be possible to update?

**Comment by darwin-morocho** [comment]
> Other packages are already using plugin_platform_interface 2.0.0 for null-safety and I got a version solving error because this package is using ^1.1.0-nullsafety.2. Would it be possible to update?

Hi @felixgabler today I will update the plugin_platform_interface

**Comment by darwin-morocho** [comment]
@felixgabler  please use the version  `3.0.0-nullsafety.1`

**Comment by felixgabler** [comment]
Thank you very much!
