### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by subhash279** [darwin-morocho/flutter-facebook-auth#59]
**Describe the bug**
Hi, Great work on the plugin. This is not a bug but do you plan to support MacOS flutter apps

**Environment**
-

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**
-

**Comment by darwin-morocho** [comment]
hi @subhash279   facebook doesn't have a sdk for desktop apps but you can create a manual flow 
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
