### ISSUE TITLE
Version error

### ISSUE THREAD

**Issue by mergengerel** [darwin-morocho/flutter-facebook-auth#60]
Because firebase_messaging >=9.0.0 depends on firebase_core_platform_interface ^4.0.0 which depends on plugin_platform_interface ^2.0.0, firebase_messaging >=9.0.0 requires plugin_platform_interface ^2.0.0.
And because flutter_facebook_auth >=2.0.0-web.8 <3.0.0-nullsafety.0 depends on flutter_facebook_auth_platform_interface ^1.0.1 which depends on plugin_platform_interface ^1.0.1, firebase_messaging >=9.0.0 is incompatible with flutter_facebook_auth >=2.0.0-web.8 <3.0.0-nullsafety.0.
So, because msm_flutter depends on both flutter_facebook_auth ^2.0.2+1 and firebase_messaging ^9.0.0, version solving failed.
pub get failed (1; So, because msm_flutter depends on both flutter_facebook_auth ^2.0.2+1 and firebase_messaging ^9.0.0, version solving failed.)

**Comment by darwin-morocho** [comment]
@mergengerel you need to use the pre-release version https://pub.dev/packages/flutter_facebook_auth/versions/3.0.0-nullsafety.1
