### ISSUE TITLE
Android app - Plugins - uses or overrides a deprecated API

### ISSUE THREAD

**Issue by JigneshPatel23** [darwin-morocho/flutter-facebook-auth#61]
I am ignoring these warnings till now but thought let's lookout for way to get rid of these if is there any quick fix..?

```
Note: Recompile with -Xlint:deprecation for details.
Note: /.../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.0.0+1/android/src/main/java/app/meedu/flutter_facebook_auth/FlutterFacebookAuthPlugin.java uses or overrides a deprecated API.
```

**Comment by darwin-morocho** [comment]
this plugin uses the Facebook sdk 8.0 maybe that version uses a deprecated api, the Facebook sdk has a pre release 9.0 version but I need to test it to update

**Comment by darwin-morocho** [comment]
> I am ignoring these warnings till now but thought let's lookout for way to get rid of these if is there any quick fix..?
> 
> ```
> Note: Recompile with -Xlint:deprecation for details.
> Note: /.../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.0.0+1/android/src/main/java/app/meedu/flutter_facebook_auth/FlutterFacebookAuthPlugin.java uses or overrides a deprecated API.
> ```

After check, the problem is because your app has support for `since Android 4.1 or higher` (minSdkVersion:16) to remove the warning you need increase the `minSdkVersion` to 21 (since Android 5.0 or higher) in your `android/app/build.gradle` file.

**Comment by JigneshPatel23** [comment]
@darwin-morocho thanks for much info.. I will check those things.
