### ISSUE TITLE
can't logOut

### ISSUE THREAD

**Issue by tagby-haedongJeon** [darwin-morocho/flutter-facebook-auth#62]
**Describe the bug**
I can log in. but I can not log out.

**Environment**

> [✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-arm, locale ko-KR)
>     • Flutter version 2.0.2 at /Users/jeonhaedong/Downloads/flutter
>     • Framework revision 8962f6dc68 (4 days ago), 2021-03-11 13:22:20 -0800
>     • Engine revision 5d8bf811b3
>     • Dart version 2.12.1
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
>     • Android SDK at /Users/jeonhaedong/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.1
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 12.4, Build version 12D4e
>     • CocoaPods version 1.10.1
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 4.1)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] Connected device (3 available)
>     • iPhone 12 (mobile) • 3718D6B8-71E2-493D-9538-5164BDD07050 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
>     • macOS (desktop)    • macos                                • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
>     • Chrome (web)       • chrome                               • web-javascript • Google Chrome 89.0.4389.90
> 
> • No issues found!
> 

**To Reproduce**
try facebook login. then go other screen(something like 'user page'). try logout in that screen.

**Expected behavior**
should be logged out. __But nothing happens.__

> ElevatedButton(    
>     style: ElevatedButton.styleFrom(primary: Colors.indigo),    
>     onPressed: () async {    
>         await FacebookAuth.instance.logOut();    
>         Navigator.of(context).pop();    
>     },    
>     child: Text('logout'),    
> ),    

this is my log out button. My intention was to log out and return to the previous screen by touching the logout button.     
But when I press the logout button, __nothing happens.__

**Comment by darwin-morocho** [comment]
@tagby-haedongJeon please add your pubspec.yaml, the error is on Android or ios?, Also make sure that you are not calling to the logout method twice.

**Comment by tagby-haedongJeon** [comment]
> @tagby-haedongJeon maybe are you trying logout and and log in again but with a different account? that feature is not possible in mobile devices.
> 
> [facebook/facebook-ios-sdk#1472](https://github.com/facebook/facebook-ios-sdk/issues/1472)

oh.... I want to test the code with multiple accounts. What to do if account conversion is not possible? Even if I delete the app and reinstall it, the old account is still alive. Is there any way to end the token validity period?

**Comment by darwin-morocho** [comment]
> > @tagby-haedongJeon maybe are you trying logout and and log in again but with a different account? that feature is not possible in mobile devices.
> > [facebook/facebook-ios-sdk#1472](https://github.com/facebook/facebook-ios-sdk/issues/1472)
> 
> oh.... I want to test the code with multiple accounts. What to do if account conversion is not possible? Even if I delete the app and reinstall it, the old account is still alive. Is there any way to end the token validity period?

You need to go  to your Facebook account and delete the app from your applications

**Comment by darwin-morocho** [comment]
I am closinng this because is not an issue from this plugin
