### ISSUE TITLE
flutter_facebook_auth >=3.1.0+1 requires plugin_platform_interface ^2.0.0.

### ISSUE THREAD

**Issue by developerflutter** [darwin-morocho/flutter-facebook-auth#67]
flutter_facebook_auth >=3.1.0+1 depends on flutter_facebook_auth_platform_interface ^2.1.1 which depends on plugin_platform_interface ^2.0.0, flutter_facebook_auth >=3.1.0+1 requires plugin_platform_interface ^2.0.0.

**Comment by darwin-morocho** [comment]
Maybe this can  help you https://github.com/darwin-morocho/flutter-facebook-auth/issues/67#issue-836743477

**Comment by jonhygg99** [comment]
I have this error if I `cd ios` and then `pod install`.

> [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
  In snapshot (Podfile.lock):
    FBSDKCoreKit (= 9.0.1, ~> 9.0.0, ~> 9.0.1)

  In Podfile:
    flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 2.0.0, which depends on
      FBSDKCoreKit (~> 9.1.0)

Specs satisfying the `FBSDKCoreKit (= 9.0.1, ~> 9.0.0, ~> 9.0.1), FBSDKCoreKit (~> 9.1.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by darwin-morocho** [comment]
> I have this error if I `cd ios` and then `pod install`.
> 
> > [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
> > In snapshot (Podfile.lock):
> > FBSDKCoreKit (= 9.0.1, ~> 9.0.0, ~> 9.0.1)
> 
> > In Podfile:
> > flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 2.0.0, which depends on
> > FBSDKCoreKit (~> 9.1.0)
> 
> > Specs satisfying the `FBSDKCoreKit (= 9.0.1, ~> 9.0.0, ~> 9.0.1), FBSDKCoreKit (~> 9.1.0)` dependency were found, but they required a higher minimum deployment target.

Check the migration guide https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth#migration-guide

**Comment by jonhygg99** [comment]
It works for me! Thanks for the quick response!
