### ISSUE TITLE
IOS build error

### ISSUE THREAD

**Issue by cuong0993** [darwin-morocho/flutter-facebook-auth#68]
**Describe the bug**
Hi,
I tried to add flutter_facebook_auth: ^3.1.1 to dependency and try to run in IOS
And I got error
    [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 1.0.0, which depends on
          FBSDKCoreKit (~> 9.1.0)

    None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit (~> 9.1.0)`.

Version 2.x worked fine but 3.x got this issue.

**Environment**
Add your `flutter doctor -v`
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2.3 20D91 darwin-arm, locale en-VN)
    • Flutter version 2.0.2 at /Users/cuong/flutter
    • Framework revision 8962f6dc68 (9 days ago), 2021-03-11 13:22:20 -0800
    • Engine revision 5d8bf811b3
    • Dart version 2.12.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/cuong/Library/Android/sdk
    • Platform android-S, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 53.1.5
    • Dart plugin version 203.7759

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

**To Reproduce**
https://github.com/cuong0993/issue.git

**Expected behavior**
App can be built

**Screenshots**
Got error when build ios

flutter --no-color build ios
Building com.example.untitled for device (ios-release)...
Signing iOS app for device deployment using developer identity: 
Running pod install...                                             719ms
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_facebook_auth
      - Flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `flutter_facebook_auth` from `.symlinks/plugins/flutter_facebook_auth/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_9_b_5.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/9/b/5/FBSDKCoreKit/9.0.1/FBSDKCoreKit.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_b_3_c.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/b/3/c/FBSDKLoginKit/9.0.1/FBSDKLoginKit.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "FBSDKCoreKit":
      In Podfile:
        flutter_facebook_auth (from `.symlinks/plugins/flutter_facebook_auth/ios`) was resolved to 1.0.0, which depends on
          FBSDKCoreKit (~> 9.1.0)

    None of your spec sources contain a spec satisfying the dependency: `FBSDKCoreKit (~> 9.1.0)`.
<img width="1438" alt="ảnh" src="https://user-images.githubusercontent.com/8237154/111865859-0bc07d80-899c-11eb-9af1-6cd0751189c1.png">

**Comment by darwin-morocho** [comment]
maybe this can help you https://github.com/darwin-morocho/flutter-facebook-auth/issues/67#issue-836743477

**Comment by darwin-morocho** [comment]
Duplicated https://github.com/darwin-morocho/flutter-facebook-auth/issues/67
