### ISSUE TITLE
Token is getting printed

### ISSUE THREAD

**Issue by pgudivadaDiligent** [darwin-morocho/flutter-facebook-auth#7]
Line # 54 of **flutter_facebook_auth.dart** has a print statement

``` flutter
print("isLogged result $result");
```

I believe this can be removed.  

Thanks for sharing the library.

**Comment by darwin-morocho** [comment]
> Line # 54 of **flutter_facebook_auth.dart** has a print statement
> 
> ```
> print("isLogged result $result");
> ```
> 
> I believe this can be removed.
> 
> Thanks for sharing the library.

thanks for your feedback. I will remove this print
