### ISSUE TITLE
Logout get stuck if user is not logged in

### ISSUE THREAD

**Issue by llucie** [darwin-morocho/flutter-facebook-auth#71]
**Describe the bug**
The call of `FacebookAuth.instance.logOut();` stays stuck if we did not previously logged in with `FacebookAuth.instance.login()`.
Consider the following sample, containing a method that logs out from all our login providers:

```dart
Future<void> signOut() async {
    // sign-out Firebase Auth
    await firebaseAuth.signOut();

    // sign-out Google Sign-in
    await googleSignIn.signOut();

    // sign out Facebook login
    log('Before facebook logout');
    await facebookAuth.logOut();
    log('After facebook logout');
}
```

We get this in the console:
```bash
Before facebook logout
FB.logout() called without an access token.
```
The second log is never called, neither is the rest of the code supposed to be called afterwards.

**Environment**

```
flutter doctor -v
[✓] Flutter (Channel master, 2.1.0-11.0.pre.98, on Linux, locale fr_FR.UTF-8)
    • Flutter version 2.1.0-11.0.pre.98 at /usr/share/flutter
    • Framework revision 2f7d9d3d26 (il y a 3 semaines), 2021-03-04 03:25:49 -0500
    • Engine revision 91120b358a
    • Dart version 2.13.0 (build 2.13.0-101.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /usr/share/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /usr/share/Android/sdk
    • Java binary at: /snap/android-studio/101/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /usr/share/android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.1)
    • Android Studio at /snap/android-studio/101/android-studio
    • Flutter plugin version 52.2.1
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.90

• No issues found!

```

My pubspec.yaml contains the package:
`flutter_facebook_auth: ^3.2.0`

**To Reproduce**
Call the logout method without login first.

**Expected behavior**
The code should not be stuck, an exception could be raised for instance, or just the log.

**Comment by darwin-morocho** [comment]
you can check if you have a previos session using FacebookAuth.instance.accessToken. before calling logOut()

**Comment by llucie** [comment]
What kind of exception? Indeed I tried to put the logout call in a try catch block,


```dart
try {
    await FacebookAuth.instance.logOut();
  } catch (e) {
    log.warning('Failed to log out');
  }
```
But nothing is caught.

Thanks for the workaround with the check of accessToken, I opened this issue because this part of my code hasn't changed for months, and it did not cause any problem beforwards, calling logout without being logged in.
I guess I'm not the only one having this, and I could not find the information about the exceptions in the documentation.

**Comment by darwin-morocho** [comment]
> What kind of exception? Indeed I tried to put the logout call in a try catch block,
> 
> ```dart
> try {
>     await FacebookAuth.instance.logOut();
>   } catch (e) {
>     log.warning('Failed to log out');
>   }
> ```
> 
> But nothing is caught.
> 
> Thanks for the workaround with the check of accessToken, I opened this issue because this part of my code hasn't changed for months, and it did not cause any problem beforwards, calling logout without being logged in.
> I guess I'm not the only one having this, and I could not find the information about the exceptions in the documentation.

I will check if the Exception is not calling from native code

**Comment by darwin-morocho** [comment]
@llucie  Could you tell me if the error is in iOS, Android or web?
