### ISSUE TITLE
Error on IOS

### ISSUE THREAD

**Issue by arcas0803** [darwin-morocho/flutter-facebook-auth#73]
I get an error on ios:
error: value of type 'AccessToken' has no member 'declinedPermissions'
                "declinedPermissions":accessToken.declinedPermissions.map {item in item.name}
It seems like access token no longer have declinePermissions and Permissions fields. Do i hace to use a specific version of Facebook SDK. I'm using ios 12.0 target on pod file.

**Comment by darwin-morocho** [comment]
duplicated https://github.com/darwin-morocho/flutter-facebook-auth/issues/69
