### ISSUE TITLE
Can not get other field like users birthday

### ISSUE THREAD

**Issue by npanic87** [darwin-morocho/flutter-facebook-auth#76]
**Describe the bug**
Can not get user's birthday even though it is specified in the filed and permission for getting this info from the user is also specified.

**Environment**
flutter_facebook_auth: ^2.0.2+1

**To Reproduce**
```
final AccessToken accessToken = await FacebookAuth.instance
    .login(permissions: ['email', 'public_profile', 'user_birthday']);
 final userData = await FacebookAuth.instance.getUserData(
            fields : "name,email,picture.width(200),birthday");
```

**Expected behavior**
I expect that I get the birthday filed in the map that I get when calling `getUserData` method.

**Comment by darwin-morocho** [comment]
hi @npanic87 the `user_birthday` permissions requires the facebook approval, if you app is in debug mode you can test this permission only with the facebook developer account. Also you can use the instance of AccessToken to check if you have the birthday permission in the granted list.

**Comment by npanic87** [comment]
Hi @darwin-morocho,
Thank you for your quick response!

I think the app has been published and it is not in debug mode, but I have to confirm that.
When I checked the access token I can see that only two permissions are granted, `email` and `public_profile`, and when calling `FacebookAuth.instance.getUserData('name,email,picture.width(200),birthday')`,  I get only the data related to these two permissions. The declined permission list from the access token is empty.
Even if the application is in debug mode, I would expect that other permissions, like user_birthday, is in the declined permission list.

Also, I tried to get this data via HTTP request and there as well I only get the same data as above, picture, name and email, there is no filed for birthday.

**Comment by darwin-morocho** [comment]
> Hi @darwin-morocho,
> Thank you for your quick response!
> 
> I think the app has been published and it is not in debug mode, but I have to confirm that.
> When I checked the access token I can see that only two permissions are granted, `email` and `public_profile`, and when calling `FacebookAuth.instance.getUserData('name,email,picture.width(200),birthday')`, I get only the data related to these two permissions. The declined permission list from the access token is empty.
> Even if the application is in debug mode, I would expect that other permissions, like user_birthday, is in the declined permission list.
> 
> Also, I tried to get this data via HTTP request and there as well I only get the same data as above, picture, name and email, there is no filed for birthday.

Have you tested using the Facebook account that created the app in the Facebook developers console?

**Comment by darwin-morocho** [comment]
> > Hi @darwin-morocho,
> > Thank you for your quick response!
> > I think the app has been published and it is not in debug mode, but I have to confirm that.
> > When I checked the access token I can see that only two permissions are granted, `email` and `public_profile`, and when calling `FacebookAuth.instance.getUserData('name,email,picture.width(200),birthday')`, I get only the data related to these two permissions. The declined permission list from the access token is empty.
> > Even if the application is in debug mode, I would expect that other permissions, like user_birthday, is in the declined permission list.
> > Also, I tried to get this data via HTTP request and there as well I only get the same data as above, picture, name and email, there is no filed for birthday.
> 
> Have you tested using the Facebook account that created the app in the Facebook developers console?

If your app in the Facebook developers console is in production mode maybe you need send a the birthday permission to review https://developers.facebook.com/docs/app-review/submission-guide

**Comment by npanic87** [comment]
Thanks! I will check that and get back to you if it works.
