### ISSUE TITLE
Can't switch Facebook account

### ISSUE THREAD

**Issue by Froszen** [darwin-morocho/flutter-facebook-auth#78]
**Describe the bug**
After successfully signout and logout from facebook through my app, when I try to login through facebook again, I have no way of login with another account.
I didn't see anywhere a mean to do it in the documentation.

**Environment**
flutter_facebook_auth: ^3.3.2

**To Reproduce**
I only call the methods FacebookAuth.instance.login() and FacebookAuth.instance.logout().

**Expected behavior**
After FacebookAuth.instance.logout(), I expected a behavior where the user can login via Facebook again but with a way to enter another account.
I only have to choices : Continue or Cancel. 
"Continue" forces me to use the first user with who I first logged in.
"Cancel" aborts the connection.

**Thank you for your help !**

**Comment by darwin-morocho** [comment]
> **Describe the bug**
> After successfully signout and logout from facebook through my app, when I try to login through facebook again, I have no way of login with another account.
> I didn't see anywhere a mean to do it in the documentation.
> 
> **Environment**
> flutter_facebook_auth: ^3.3.2
> 
> **To Reproduce**
> I only call the methods FacebookAuth.instance.login() and FacebookAuth.instance.logout().
> 
> **Expected behavior**
> After FacebookAuth.instance.logout(), I expected a behavior where the user can login via Facebook again but with a way to enter another account.
> I only have to choices : Continue or Cancel.
> "Continue" forces me to use the first user with who I first logged in.
> "Cancel" aborts the connection.
> 
> **Thank you for your help !**

https://github.com/darwin-morocho/flutter-facebook-auth/issues/62#issuecomment-799895330

**Comment by Froszen** [comment]
thank you for your fast reply ! :)
