### ISSUE TITLE
Facebook error message after provide credentials [Android]

### ISSUE THREAD

**Issue by giaur500** [darwin-morocho/flutter-facebook-auth#79]
Sometimes I'm getting error message:

> Sorry, something went wrong
> We could not verify that your request came from actions on our site.
> If you are using software which hides the origin of a request please try turning it off temporarily.

Sometimes it works, sometimes Facebook throws this message. What's wrong here?

**Comment by darwin-morocho** [comment]
> Sometimes I'm getting error message:
> 
> > Sorry, something went wrong
> > We could not verify that your request came from actions on our site.
> > If you are using software which hides the origin of a request please try turning it off temporarily.
> 
> Sometimes it works, sometimes Facebook throws this message. What's wrong here?

Please add more info
Witch platform has the problem?
Add a code to reproduce and  are  you in debug mode?

**Comment by darwin-morocho** [comment]
I th

> Sometimes I'm getting error message:
> 
> > Sorry, something went wrong
> > We could not verify that your request came from actions on our site.
> > If you are using software which hides the origin of a request please try turning it off temporarily.
> 
> Sometimes it works, sometimes Facebook throws this message. What's wrong here?

Please add all the requirements in the issue template to allows me reproduce the problem.

Also it could be a problem with your network connection, a bad configuración, a invalid key hash in your Facebook developers console.

Please go to https://github.com/facebook/facebook-android-sdk and open the issue here

**Comment by giaur500** [comment]
The problem is I am not able to reproduce it anymore so far. That's on Android, the same Facebook app is linked to native Android app and it's confirmed working on production. As soon as I reproduce it again, I will try to get more info. That was completly random, it also may be some problem at Faceboko side or even network issue.

I have no idea, to be honest.
