### ISSUE TITLE
'flutter_facebook_auth/flutter_facebook_auth-Swift.h' file not found

### ISSUE THREAD

**Issue by AminPlusPlus** [darwin-morocho/flutter-facebook-auth#8]
Project created with Objective-c, but I added Swift App Delegate file manually.

Running Xcode getting this issue.
'flutter_facebook_auth/flutter_facebook_auth-Swift.h' file not found

**Comment by darwin-morocho** [comment]
duplicated https://github.com/darwin-morocho/flutter-facebook-auth/issues/4
