### ISSUE TITLE
Value of type 'AccessToken' has no member 'permissions' and Value of type 'AccessToken' has no member 'declinedPermissions' during XCode build

### ISSUE THREAD

**Issue by AlokMishra01** [darwin-morocho/flutter-facebook-auth#81]
**Describe the bug**

**Environment**
Add your `flutter doctor -v`
Add your `pubspec.yaml`
Add your `Info.plist`
Add your `AndroidManifest.xml`
Add your `/app/res/values/strings.xml`

**To Reproduce**
Please add your code to reproduce the issue

**Expected behavior**

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Comment by darwin-morocho** [comment]
Your project uses objective-c to use this plugin you need to use swift as a default language https://github.com/darwin-morocho/flutter-facebook-auth/issues/69

**Comment by darwin-morocho** [comment]
closed by duplicated
