### ISSUE TITLE
User logged in as a different facebook user

### ISSUE THREAD

**Issue by kaarens93** [darwin-morocho/flutter-facebook-auth#82]
I don't know why I'm getting this error message. I removed the app from FB settings and tried logging in but I keep getting this error. I've also only been using 1 facebook account

**Comment by darwin-morocho** [comment]
> I don't know why I'm getting this error message. I removed the app from FB settings and tried logging in but I keep getting this error. I've also only been using 1 facebook account

please add more information

**Comment by kaarens93** [comment]
Understood. Thanks a lot!
