### ISSUE TITLE
[Feature] Support iOS URL scheme suffix

### ISSUE THREAD

**Issue by flavienbert** [darwin-morocho/flutter-facebook-auth#83]
I want to submit a feature request

### Description

In order to use the same Facebook Id in multiple applications on iOS, custom URL scheme suffix would need to be use (see screenshot from the Facebook developer console). Unfortunately, this is not yet possible with the current version of this plugin.

### Goal

If URL scheme suffix are not used, nothing should be added and different than with actual version of the plugin respectively -Info.plit should not be modified

If URL scheme suffix should be use, -Info.plit should contains a new child and value for FacebookUrlSchemeSuffix and the suffix should be added after the APP_ID in the CFBundleURLSchemes value

### Documentation

Facebook SDK: https://developers.facebook.com/docs/reference/ios/current/constants/FBSDKSettings/

### Screenshot

<img width="973" alt="screen" src="https://user-images.githubusercontent.com/11570111/115070905-d9039980-9ef5-11eb-92c5-f06d1a7edd0c.png">

**Comment by darwin-morocho** [comment]
Hi this is not a New feature because that what you will do is  a configuration so you need configure the Facebook sdk acording to the Facebook documentation

**Comment by flavienbert** [comment]
Ho yes, You are right, the config FacebookUrlSchemeSuffix seems good!
