### ISSUE TITLE
incompatibility with image picker

### ISSUE THREAD

**Issue by Cyphontin** [darwin-morocho/flutter-facebook-auth#84]
With flutter-facebook-auth image picker has an error:

**Code:**
Future getImage() async {
final pickedFile = await picker.getImage(source: ImageSource.gallery);

**Error:**
[ +90 ms] E/flutter (24519): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation
found for method pickImage on channel plugins.flutter.io/image_picker)
[ +1 ms] E/flutter (24519): #0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
[ ] E/flutter (24519):
[ ] E/flutter (24519): #1 MethodChannelImagePicker.pickImage
(package:image_picker_platform_interface/src/method_channel/method_channel_image_picker.dart:29:20)
[ ] E/flutter (24519):
[ ] E/flutter (24519): #2 _Test.getImage (package:leepr/pages/testbdd.dart:25:24)
[ ] E/flutter (24519):
[ ] E/flutter (24519):

**Comment by darwin-morocho** [comment]
HI please read the documentation of this plugin. YOU need too configure the plugin before run the oroject.

https://facebook.meedu.app/#/android

**Comment by Cyphontin** [comment]
Absolutely! I forgotten something in the AndroidManifest
