### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Thirulogachandarkt** [darwin-morocho/flutter-facebook-auth#87]
Launching lib\main.dart on Redmi K20 Pro in debug mode...
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.3.0+2/lib/flutter_facebook_auth.dart:3:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:flutter_facebook_auth_platform_interface/flutter_facebook_auth_platform_interface.dart';
^

/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.3.0+2/lib/flutter_facebook_auth.dart:6:7: Error: The non-abstract class 'FacebookAuth' is missing implementations for these members:
 - FacebookAuthPlatform.permissions
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class FacebookAuth implements FacebookAuthPlatform {
      ^^^^^^^^^^^^
/D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth_platform_interface-2.4.0-no-nullsafety/lib/flutter_facebook_auth_platform_interface.dart:78:35: Context: 'FacebookAuthPlatform.permissions' is defined here.
  Future<FacebookPermissions> get permissions;
                                  ^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)`

**Comment by darwin-morocho** [comment]
> Launching lib\main.dart on Redmi K20 Pro in debug mode...
> /D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.3.0+2/lib/flutter_facebook_auth.dart:3:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
> export 'package:flutter_facebook_auth_platform_interface/flutter_facebook_auth_platform_interface.dart';
> ^
> 
> /D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth-3.3.0+2/lib/flutter_facebook_auth.dart:6:7: Error: The non-abstract class 'FacebookAuth' is missing implementations for these members:
> 
> * FacebookAuthPlatform.permissions
>   Try to either
> * provide an implementation,
> * inherit an implementation from a superclass or mixin,
> * mark the class as abstract, or
> * provide a 'noSuchMethod' implementation.
> 
> class FacebookAuth implements FacebookAuthPlatform {
> ^^^^^^^^^^^^
> /D:/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_facebook_auth_platform_interface-2.4.0-no-nullsafety/lib/flutter_facebook_auth_platform_interface.dart:78:35: Context: 'FacebookAuthPlatform.permissions' is defined here.
> Future get permissions;
> ^^^^^^^^^^^
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
>   Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 991
> * What went wrong:
>   Execution failed for task ':app:compileFlutterBuildDebug'.
> 
> > Process 'command 'D:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 20s
> Exception: Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)`

HI, PLEASE follow the issue template and add all the information required to understand the problem

**Comment by darwin-morocho** [comment]
closed by inactivity

**Comment by osamamohammed98** [comment]
where the solution

**Comment by darwin-morocho** [comment]
> where the solution

Is not a valid issue because the information requested into the issue template were not provided
