### ISSUE TITLE
Unable to get package. Fails with error depends on both firebase_messaging ^7.0.3 and flutter_facebook_auth ^3.3.3+1

### ISSUE THREAD

**Issue by pbhuvanesh** [darwin-morocho/flutter-facebook-auth#88]
**Describe the bug**
I was trying to install flutter_facebook_auth 3.3.3+1 but the get failed with `depends on both firebase_messaging ^7.0.3 and flutter_facebook_auth ^3.3.3+1`.

I think the issue is related to firebase_messaging version 7.0.3. Could you please confirm if it is the same? Which version of fb_auth should I use for this error be resolved?

**Comment by darwin-morocho** [comment]
Hi I am not sure what is the problem could you add your logs
?

**Comment by pbhuvanesh** [comment]
`Because flutter_facebook_auth >=3.3.3 depends on flutter_facebook_auth_platform_interface ^2.4.2 which depends on plugin_platform_interface ^2.0.0, flutter_facebook_auth >=3.3.3 requires plugin_platform_interface ^2.0.0.
And because firebase_core_platform_interface >=1.0.4 <3.0.2-nullsafety.0 depends on plugin_platform_interface ^1.0.2, flutter_facebook_auth >=3.3.3 is incompatible with firebase_core_platform_interface >=1.0.4 <3.0.2-nullsafety.0.
Because firebase_core ^0.5.2+1 depends on firebase_core_platform_interface ^2.1.0 and firebase_core >=0.5.0 <=0.5.2 depends on firebase_core_platform_interface ^2.0.0, firebase_core ^0.5.0 requires firebase_core_platform_interface ^2.0.0.
Thus, flutter_facebook_auth >=3.3.3 is incompatible with firebase_core ^0.5.0.
And because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, flutter_facebook_auth >=3.3.3 is incompatible with firebase_messaging ^7.0.3.
So, because kaadhal_client depends on both firebase_messaging ^7.0.3 and flutter_facebook_auth ^3.3.3+1, version solving failed.`

**Comment by darwin-morocho** [comment]
Hi the problem is the version of platform_interface you could override that  dependency using dependency_overrides on your pubspec.yaml and use plugin_platform_interface:^2.0.0

**Comment by darwin-morocho** [comment]
the problem is that your project doesn't have support for null safety so you need to use
  flutter_facebook_auth: ^3.3.3

**Comment by pbhuvanesh** [comment]
Please correct me if I am wrong I am using
`environment:
  sdk: ">=2.12.0 <3.0.0"
`
I tired the above solution. It works but will have to see its side effects. Thank you @darwin-morocho

**Comment by darwin-morocho** [comment]
> Please correct me if I am wrong I am using
> `environment: sdk: ">=2.12.0 <3.0.0" `
> Is this not null safety enabled?
> I tired the above solution. It works but will have to see its side effects. Thank you @darwin-morocho

yes null safety is enabled but your firebase depencies need to be updated because firebase messaging 7 doesn't have support for null safety

**Comment by pbhuvanesh** [comment]
Okay! Thank you @darwin-morocho. Your help resolved my issue.

**Comment by darwin-morocho** [comment]
> Okay! Thank you @darwin-morocho. Your help resolved my issue.

Great I am closinng this 🤓
