### ISSUE TITLE
Web version doesn't login, https://flutter-facebook-auth.web.app/#/ doesn't work either

### ISSUE THREAD

**Issue by mokus** [darwin-morocho/flutter-facebook-auth#91]
I'm trying to login with the web version but FacebookAuth.instance.login never returns any result and doesn't throw an exception.
Web example on https://flutter-facebook-auth.web.app/#/ doesn't work either.

Android version works fine.

**Environment**
Since your demo doesn't work as well, there is no reason to provide details. But let me know if it's needed.

**To Reproduce**
Go to https://flutter-facebook-auth.web.app/#/

**Expected behavior**
App should login

**Comment by darwin-morocho** [comment]
> I'm trying to login with the web version but FacebookAuth.instance.login never returns any result and doesn't throw an exception.
> Web example on https://flutter-facebook-auth.web.app/#/ doesn't work either.
> 
> Android version works fine.
> 
> **Environment**
> Since your demo doesn't work as well, there is no reason to provide details. But let me know if it's needed.
> 
> **To Reproduce**
> Go to https://flutter-facebook-auth.web.app/#/
> 
> **Expected behavior**
> App should login

Hi apparently is a problem with the facebook javascript sdk they recently has been released the v10 sdk but is not working. I've been created a pure javascript example to check if there is some error in this plugin but the pure javascript example is no working too.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <button onclick="check()">LOGIN</button>

    <script>
      window.fbAsyncInit = function () {
        console.log("jajajajaj");
        FB.init({
          appId: "1329834907365798",
          autoLogAppEvents: false,
          xfbml: true,
          version: "v10.0",
        });
      };

      function check() {
        console.log("checking status");
        FB.getLoginStatus(function (response) {
          console.log("FB response", response);
        });
      }
    </script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
  </body>
</html>

```

**Comment by darwin-morocho** [comment]
@mokus  you can check this error here https://developers.facebook.com/status/issues

**Comment by mokus** [comment]
Thank you for a quick response. You saved me the day.
