### ISSUE TITLE
Using of facebook_auth in iOS 14.5 or newer.

### ISSUE THREAD

**Issue by sharath12345678** [darwin-morocho/flutter-facebook-auth#92]
Whether using of Facebook auth in iOS tracks the user or it collects any data related to user from the app. Refer [this link from apple](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).

If Yes, how to disable all the tracking functionalities and only use authentication. (as of now facebook related string in our app's info.plist, which is not mentioned in package readme is `<key>FacebookAutoLogAppEventsEnabled</key><false/>` ) 

Further, in firebase, if we want to disable firebase analytics we could set `FIREBASE_ANALYTICS_COLLECTION_DEACTIVATED` to `YES` (Boolean) in app's Info.plist file, we are looking for something similar.

**Comment by darwin-morocho** [comment]
Hi @sharath12345678  you only need to go to `ios/runner/info.plist` and add 
```
<key>FacebookAutoLogAppEventsEnabled</key>
<false/>
```

**Comment by sharath12345678** [comment]
Thanks Man.

**Comment by Artur110** [comment]
@darwin-morocho, so I shouldn't set 'Data Used to Track You' in App Store Connect to use this package? Just add key that you noticed above in info.plist, right?
