### ISSUE TITLE
How do I write test case for flutter-facebook-auth?

### ISSUE THREAD

**Issue by pbhuvanesh** [darwin-morocho/flutter-facebook-auth#94]
Hi,

First off thanks for the package. However, I would like to know how can I write test cases if I include your package? At the moment I am using this package and I would like to know how to test it. Could you please provide me with a sample test case? Or how do I use mockito to stub it?

**Comment by darwin-morocho** [comment]
Hi you could use the test folder inside facebook_auth here you will found how to mock the responses from the native code or you can use mockito or mocktail to simulate the responses for each method of this plugin

**Comment by pbhuvanesh** [comment]
Thank you. I think I was able to figure it out.
