### ISSUE TITLE
Wrong CocoaPods dependencies

### ISSUE THREAD

**Issue by OctavianLfrd** [darwin-morocho/flutter-facebook-auth#95]
Please, consider replacing FBSDKCoreKit and FBSDKLoginKit with FacebookCore and FacebookLogin dependencies, to get rid of such issues like:  #81 (Value of type 'AccessToken' has no member 'permissions' and Value of type 'AccessToken' has no member 'declinedPermissions').

![Screenshot 2021-05-05 at 18 22 07](https://user-images.githubusercontent.com/45371490/117166452-0f368980-adcf-11eb-936d-150f1791c512.png)
Seems like this info from https://github.com/facebook/facebook-ios-sdk is relevant for CocoaPods' users too.

Example:
![Screenshot 2021-05-05 at 18 26 18](https://user-images.githubusercontent.com/45371490/117166863-705e5d00-adcf-11eb-9a0e-7e571045be76.png)
Seems to work without any issue.

**Comment by darwin-morocho** [comment]
Hi @OctavianLfrd according to the cocoapods [page](https://cocoapods.org/pods/FacebookCore) that libraries are in BETA, also the github repo is archived https://github.com/facebookarchive/facebook-swift-sdk
