### ISSUE TITLE
Content blockers / tracking protection makes SDK not work

### ISSUE THREAD

**Issue by rbozan** [darwin-morocho/flutter-facebook-auth#98]
**Describe the bug**
When the FB SDK does not load (for example: because of content blockers) your whole application does not function anymore after calling `FacebookAuth.instance.webInitialize` without `try catch`. This is especially important as Firefox standard security already blocks this SDK, so Firefox users can not use my application at all if I did not have the `try catch`.

**Environment**
Add your `flutter doctor -v`

```
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on Linux, locale en_NL.UTF-8)
    • Flutter version 2.2.0-10.2.pre at /home/rbozan/development/flutter
    • Framework revision b5017bf8de (2 weeks ago), 2021-04-28 17:09:53 -0700
    • Engine revision 91ed51e05c
    • Dart version 2.13.0 (build 2.13.0-211.13.beta)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Chromium 90.0.4430.93

! Doctor found issues in 2 categories.

```

**To Reproduce**
Under `main`:
```
 if (kIsWeb) {
    print('initialize');
    FacebookAuth.instance.webInitialize(
      appId: "800865374072290",
      cookie: true,
      xfbml: true,
      version: "v9.0",
    );
    print('done initialize');
  }
```

**Expected behavior**
While you can surround it with a  `try, catch`, it was not apparent in the documentation and you can not know within the library if the Facebook SDK loading failed or not. Would be nice if when it failed, it would set something like `FacebookAuth.instance.available` to false.

**Screenshots**
![image](https://user-images.githubusercontent.com/7997154/118107269-d609a500-b3de-11eb-8da1-03b0b0c68f17.png)

**Comment by darwin-morocho** [comment]
@rbozan  I couldn't reproduce the issue on Firefox, please let me known how to reproduce it and what extensions Should I install

**Comment by darwin-morocho** [comment]
> @rbozan I couldn't reproduce the issue on Firefox, please let me known how to reproduce it and what extensions Should I install

The example https://flutter-facebook-auth.web.app works fine on Firefox using adBlock
