### ISSUE TITLE
Why is it using a webview to log in?

### ISSUE THREAD

**Issue by najibghadri** [darwin-morocho/flutter-facebook-auth#99]
**Describe the bug**
I set up everything in Facebook, it worked and first it used the nice Facebook modal and it knew about my logged in FB account. Then suddenly it started using this webview and it's terrible. I tried setting stuff in Facebook console, but nothing happened. I am using it with firebase auth.

**Environment**
flutter_facebook_auth: 3.3.3
`flutter doctor -v`: https://gist.github.com/najibghadri/edbb787bf85c658a9c6f3762c2fada82
`AndroidManifest.xml` : https://gist.github.com/najibghadri/4498b194d9782f5d4b0db620e51db3e3

**To Reproduce**
My code:
```
  /// Throws a [LogInWithFacebookFailure] if an exception occurs.
  Future<firebase_auth.UserCredential> logInWithFacebook() async {
    try {
      final result = await FacebookAuth.instance.login();

      if (result.status == LoginStatus.failed) {
        throw LogInWithFacebookFailure(); // Not sure that was the cause
      }

      if (result.status == LoginStatus.cancelled) {
        throw LogInWithFacebookPaused(); // Not sure that was the cause
      }

      // Create a credential from the access token
      final facebookAuthCredential =
          firebase_auth.FacebookAuthProvider.credential(
              result.accessToken!.token);

      // Once signed in, return the UserCredential
      return await firebaseAuthInstance
          .signInWithCredential(facebookAuthCredential);
    } on LogInWithFacebookPaused catch (e) {
      throw e;
    } on Exception catch (e) {
      print('SHIT did not log in $e');
      throw LogInWithFacebookFailure();
    }
  }
```

**Expected behavior**

**Screenshots**
![Screenshot_2021-05-20-14-17-19-592_com joinmycity join](https://user-images.githubusercontent.com/11639734/118977780-d671e500-b976-11eb-8317-44a21d8eaff1.jpg)

**Comment by darwin-morocho** [comment]
> **Describe the bug**
> I set up everything in Facebook, it worked and first it used the nice Facebook modal and it knew about my logged in FB account. Then suddenly it started using this webview and it's terrible. I tried setting stuff in Facebook console, but nothing happened. I am using it with firebase auth.
> 
> **Environment**
> flutter_facebook_auth: 3.3.3
> `flutter doctor -v`: https://gist.github.com/najibghadri/edbb787bf85c658a9c6f3762c2fada82
> `AndroidManifest.xml` : https://gist.github.com/najibghadri/4498b194d9782f5d4b0db620e51db3e3
> 
> **To Reproduce**
> My code:
> 
> ```
>   /// Throws a [LogInWithFacebookFailure] if an exception occurs.
>   Future<firebase_auth.UserCredential> logInWithFacebook() async {
>     try {
>       final result = await FacebookAuth.instance.login();
> 
>       if (result.status == LoginStatus.failed) {
>         throw LogInWithFacebookFailure(); // Not sure that was the cause
>       }
> 
>       if (result.status == LoginStatus.cancelled) {
>         throw LogInWithFacebookPaused(); // Not sure that was the cause
>       }
> 
>       // Create a credential from the access token
>       final facebookAuthCredential =
>           firebase_auth.FacebookAuthProvider.credential(
>               result.accessToken!.token);
> 
>       // Once signed in, return the UserCredential
>       return await firebaseAuthInstance
>           .signInWithCredential(facebookAuthCredential);
>     } on LogInWithFacebookPaused catch (e) {
>       throw e;
>     } on Exception catch (e) {
>       print('SHIT did not log in $e');
>       throw LogInWithFacebookFailure();
>     }
>   }
> ```
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> ![Screenshot_2021-05-20-14-17-19-592_com joinmycity join](https://user-images.githubusercontent.com/11639734/118977780-d671e500-b976-11eb-8317-44a21d8eaff1.jpg)

The plugin by default use the dialog only behavior on Android if the Facebook sdk cannot open the dialog using the native app it will open a webview if you don't want this behavior you can use the loginBehavior param in the  login method

**Comment by najibghadri** [comment]
Found it!! https://developers.facebook.com/docs/reference/androidsdk/current/facebook/com/facebook/login/loginbehavior.html/

**Comment by najibghadri** [comment]
Thank you very much! ❤️

**Comment by najibghadri** [comment]
Thank you very much! ❤️
